### ISSUE TITLE
 Show problem type checkbox on problem page

### ISSUE THREAD

**Issue by Xyene** [DMOJ/site#1]
Checkbox defaulted to false to avoid spoils; useful for teachers. Checking it should add another column to the table.

That field is `ManyToMany`, implementation should not cause one query per row. That page is already slow enough as it with only one query for the entire table.

**Comment by quantum5** [comment]
Implemented in 89ce5d6a2af3a32ac1bebf4950865306c8e1be75...4ee4e6466e13e04e341e2082fef3af9435b42a08 ages ago.
