### ISSUE TITLE
Disallow quick email providers

### ISSUE THREAD

**Issue by Xyene** [DMOJ/site#102]
We haven't had any issue with spam accounts yet, but as a preventive measure we should disallow creating accounts with disposable email addresses. This [XenForo article](https://xenforo.com/community/threads/ban-quick-email-providers-from-your-forum-prevent-spam.10308/) puts it nicely:

> Spammers love to use email providers that are 100% registration free, and dosent require any personal information to use. It gives them a very quick and easy way to register on your forum, and if you have email activation on, they can quickly activate their accounts using the quick email providers.

> All they do is go to the email provider's website and choose a quick name they want to use for their email and enter it, and then they can get the emails from websites they register to very quickly and then activate them, which helps them to spam forums very easily as it is a quick process. You can prevent spam like this by blocking those email providers from your boards, so people cant use these emails during registration on your forums, which is a great way to prevent unwanted spam. There are many ways to prevent spam, but this is just one out of the thousands of ways.

If we ever face this issue, we'd do well to be prepared. For example, StartSSL has the following list on their registration page:

> Mail accounts from the following providers are not allowed: qq.com freemail.com rambler.ru mailnull.com laposte.fr yopmail.com trbvm.com teleworm.us dayrep.com mailinator.com devnullmail.com safetymail.info tradermail.info chammy.info suremail.info zippymail.info guerrillamail. tempinbox.com smellfear.com lookugly.com dingbone.com fudgerub.com grr.la spam4.me tempemail.net hmamail.com spamobox.com opayq.com mailmetrash.com mt2014.com coldemail.info mailrock.biz hopemail.biz toomail.biz mailpick.biz mailtemp.info burstmail.info mailcat.biz solvemail.info sharklasers.com anonbox.net bobmail.info 6paq.com monmail.fr armyspy.com mailismagic.com tafmail.com 33mail.com guerrillamailblock.com trash-mail.com you-spam.com fake-box.com re-gister.com trash-me.com opentrash.com mailcatch.com byom.de

**Comment by quantum5** [comment]
Now if we want Chinese users, then `qq.com` probably should be allowed.

**Comment by Xyene** [comment]
qq

**Comment by quantum5** [comment]
If only the error message shows up right. @Xyene really needs to make #90 better.

**Comment by quantum5** [comment]
On a second thought may be we should ban `qq.com` simply because delivery fails half of the time if not more.

**Comment by FatalEagle** [comment]
Or just require a survey instead of email verification. $$$

**Comment by quantum5** [comment]
Email verification is not a spam deterrent. Email verification is so that we can actually contact the user about contests and so that they can use forget password.

**Comment by FatalEagle** [comment]
Just disable forget password for users without verified emails.

**Comment by quantum5** [comment]
Forget password asks you for an email, so umm...

**Comment by FatalEagle** [comment]
Yeah, just warn user that they cannot recover password without verified email.

**Comment by quantum5** [comment]
But wait it gets worse, `django-registration` probably breaks at this thought. But that shouldn't be too big of a deal, because #50.

**Comment by quantum5** [comment]
@Xyene only one form to fix and we can close this issue.

**Comment by Xyene** [comment]
@quantum5 Done.
