### ISSUE TITLE
Rating circles become empty when language is set to anything except English

### ISSUE THREAD

**Issue by maxgodfrey2004** [DMOJ/site#1025]
If the dropdown language menu on the footer of the site is selected, and the language is set to anything except English, the rating circles become empty.

It may be worth mentioning that I am running Chrome 74 and Firefox 60 on Windows 10 - the problem exists on both browsers.

For example, on my account profile (these screenshots were taken on Chrome), when I have set the language to English, the rating circles have their appropriate level of colour set.
![image](https://user-images.githubusercontent.com/34620214/61793332-7d57c980-ae51-11e9-813c-d48e351bf987.png)
However, if I set the language to something else that isn't English, such as German, the rating circles disappear!
![image](https://user-images.githubusercontent.com/34620214/61793427-b42ddf80-ae51-11e9-9491-975634546c1f.png)

**Comment by TheAvidDev** [comment]
This seems to be caused by css like `height: 0.730em` being converted to `height: 0,730em` replacing the dot with a comma, causing invalid css.
