### ISSUE TITLE
PROBLEM_DATA_ROOT not working

### ISSUE THREAD

**Issue by AkitakiKou** [DMOJ/site#1037]
I've added `PROBLEM_DATA_ROOT='/oj/problems/'` to my `local_settings.py` file, but still when I add test data `.zip` file from the site interface, a directory with the problem id is still created under the site folder. Am I doing anything wrong here?

**Comment by Xyene** [comment]
The variable you need to set is `DMOJ_PROBLEM_DATA_ROOT`, not `PROBLEM_DATA_ROOT`.
