### ISSUE TITLE
Ability to close announcement bubble

### ISSUE THREAD

**Issue by FatalEagle** [DMOJ/site#106]
It gets kinda annoying after seeing it for hours on end without any way to remove it.

**Comment by quantum5** [comment]
How would we store that info though? I guess you are to manually dismiss it every time? The closest thing you can do is to hash the string and store it as a cookie or in the local storage, and if the announcement hashes the same, hide it. But that seems really, really sketchy.

**Comment by FatalEagle** [comment]
Or maybe announcement should be a thin bar under the navbar, and in-contest announcements as alerts.

**Comment by Xyene** [comment]
Superseded by #378 and #56. The announcement feature referenced in this issue hasn't been used for a very long time, though it still exists.
