### ISSUE TITLE
Edit Profile Page Broken

### ISSUE THREAD

**Issue by ehhthing** [DMOJ/site#1064]
https://dmoj.ca/edit/profile/ is broken because jQuery is not being correctly loaded.

It appears that `jQuery` is defined while `$` is undefined, thus something is probably overriding `$`

**Comment by Xyene** [comment]
Cause: somehow `jquery.init.js` is being pulled in by the preview widget, which contains `var django=django||{};django.jQuery=jQuery.noConflict(true);`. https://api.jquery.com/jQuery.noConflict/

**Comment by quantum5** [comment]
True cause: https://github.com/jazzband/django-sortedm2m/blob/master/sortedm2m/forms.py#L16
