### ISSUE TITLE
Contest-wide partial output disabling

### ISSUE THREAD

**Issue by FatalEagle** [DMOJ/site#108]
It's inconsistent and inconvenient to disable partial output manually for each contest, and re-enable it after the contest.

**Comment by quantum5** [comment]
Protocol change required. Partial output is a setting on the judge side.

**Comment by FatalEagle** [comment]
On the submission result page, don't display the partial output. The actual output should still be kept for post-contest viewing.

**Comment by quantum5** [comment]
That makes it easier. Requires one schema change.

**Comment by FatalEagle** [comment]
Also, this allows verdicts for problems to be hidden until contest ends, like COCI.

**Comment by Xyene** [comment]
This was completed sometime ago.
