### ISSUE TITLE
Automatically hide problem tags in contest

### ISSUE THREAD

**Issue by FatalEagle** [DMOJ/site#109]

**Comment by Xyene** [comment]
There might be contests where the problem setters decide to show problem types.

**Comment by FatalEagle** [comment]
Manual override then.

**Comment by FatalEagle** [comment]
Or they could put the hint in the statement itself.

**Comment by quantum5** [comment]
This is already doable by selecting `???` problem type. No need to complicate the system for every single little "feature".

**Comment by FatalEagle** [comment]
Yes, but then it requires the admin or problem organizers to manually add tags back after the contest. This is quite annoying, given the slow loading times of the problem edit page.

**Comment by Xyene** [comment]
The slow loading times have been fixed by #333, but this feature wouldn't be hard to implement. Would be smoother user-side, anyways.

**Comment by Xyene** [comment]
This has been implemented as requested.
