### ISSUE TITLE
Judge Pools

### ISSUE THREAD

**Issue by FatalEagle** [DMOJ/site#11]
Ability to specify which pool of judges should judge a particular problem, to ensure consistent timings.

**Comment by quantum5** [comment]
We currently achieve this through controlling which judge has the data for the problem. The ability to specify through another way will cause a lot of disk space to be wasted, as some judges would then possess files that they don't need.

**Comment by FatalEagle** [comment]
True, but this is very cumbersome to manipulate as moving testdata may be expensive. Also, the number of subsets of judges we need to make private folders for grows exponentially.

**Comment by Xyene** [comment]
Timing consistency has been a non-issue since the move to DigitalOcean, so code solutions to this problem are now unwarranted. The issue of private folders is alleviated by #467.
