### ISSUE TITLE
Geolocation for registration and edit profile

### ISSUE THREAD

**Issue by quantum5** [DMOJ/site#118]
Extending #49, we should provide Geolocation to locate. We can use the Geolocation API in JS to get the latitude and longitude. While we already have a database to map it to IANA timezones, it doesn't really detect the timezone at all that well since it checks the nearest timezone centre on the map, instead of the actual timezone. There is https://askgeo.com/ which provides the information that we need.

**Comment by quantum5** [comment]
However, it would seem like you have to specifically email them showing you are an open source project to use it for free.

**Comment by quantum5** [comment]
[AskGeo is supposedly created to be more high quality than geonames.org.](http://stackoverflow.com/a/5519523/1090657)

**Comment by quantum5** [comment]
Google is much easier to use.

**Comment by quantum5** [comment]
Edit profile page depends on #65 being finished by @Xyene.

**Comment by Xyene** [comment]
Finishing DMOPC April > unwrapping the table
