### ISSUE TITLE
Blockquotes in comments visual difference

### ISSUE THREAD

**Issue by lolzballs** [DMOJ/site#119]
Blockquotes in comments do not have any visual difference from non-blockquoted text.

The only difference is that there is an indentation, but it still makes it hard to differentiate between blockquotes and normal text.

On github, blockquotes are rendered
> like this.

DMOJ comment example:
![image](https://cloud.githubusercontent.com/assets/1562553/6997613/f4e0f8f8-db8f-11e4-8c2e-f1e287ec46d4.png)

**Comment by Xyene** [comment]
The [`content-description`](https://github.com/DMOJ/site/blob/master/resources/content-description.css) stylesheet is not really used for comments, though it should be. The shades may look awkward on the non-white background of comments versus the white background of problem statements for which it was written.

**Comment by Xyene** [comment]
Seems legit.

![](https://sc-cdn.scaleengine.net/i/c06c69e4f1f5b19cb5f1e8d727437b63.png)

**Comment by Xyene** [comment]
Note to future self: the border-right of blockquotes should be shaded with `rgba` so it scales with the shade of the content (which is not static for comments).

**Comment by quantum5** [comment]
Doesn't work in editor, or history.

**Comment by Xyene** [comment]
tfw the editor stylesheet is different from the display stylesheet.

**Comment by quantum5** [comment]
The easy solution is to add the class in with a JS. Pagedown hardcodes the class it seems.

**Comment by Xyene** [comment]
`content-description` is now applied for comment history as well.

![](https://sc-cdn.scaleengine.net/i/83cbaac820d8e9ea80f624f8b88251af.png)

The issue of the editor not being styled correctly is completely different and not related to this issue, however.

**Comment by Xyene** [comment]
Editor continued in #120.
