### ISSUE TITLE
Use CloudFlare when possible

### ISSUE THREAD

**Issue by quantum5** [DMOJ/site#122]
CloudFlare doesn't work with Windows XP's certificate verification, and we can't change their certificate. Therefore, it it impossible to use CloudFlare on Windows XP. This is why `dmoj.ga` was created to serve static files. However it remains rather slow to not use a CDN, so I think we might have to detect Windows XP and `s:"//dmoj.ga:"//dmoj.ml/:g` in a middleware. Not sure if actually worth.

**Comment by Xyene** [comment]
tfw its actually slower

**Comment by quantum5** [comment]
There is no consistent data to support that either way is actually faster.

I have done some testing in Chrome incognito, with fresh restarts for every test visiting `dmoj.ca` over HTTP and doing the redirect to HTTPS, similar to a first time user.

Results:

    dmoj.ml 2.00s 1.76s 1.70s 1.59s 1.79s -> 1.77s avg
    dmoj.ga 1.68s 1.74s 1.65s 1.86s 1.72s -> 1.73s avg

**Comment by quantum5** [comment]
Seems like CloudFlare has benefits if you don't use a proxy or tunnel or whatever. Regardless it's kept.
