### ISSUE TITLE
Penalty Time Display

### ISSUE THREAD

**Issue by FatalEagle** [DMOJ/site#125]
On contest.

**Comment by Xyene** [comment]
...expand? Do you mean another column showing penalty time?

**Comment by FatalEagle** [comment]
Or hover over score.

**Comment by Xyene** [comment]
Or it could be a subtotal displayed underneath the score like the last submission times are displayed under each problem column. Thoughts?

**Comment by FatalEagle** [comment]
That works too. Probably better than my original suggestion.

**Comment by Xyene** [comment]
Not sure why this took two years to get to, but it was implemented fairly recently.
