### ISSUE TITLE
Post-Contest Private Points

### ISSUE THREAD

**Issue by Phoenix1369** [DMOJ/site#126]
Since the ratings are private for a while after the contest, nobody received contest points.
However, once I submitted a problem post-contest, the private points are revealed for my account

**Comment by quantum5** [comment]
The expected solution is that admins recalculate points for every user. There is a batch operation for this purpose.

**Comment by FatalEagle** [comment]
I didn't get the memo.

**Comment by quantum5** [comment]
There is nothing to do here anymore. If there is a change, it will happen in #130.
