### ISSUE TITLE
Comments on Solutions or FlatPages in General

### ISSUE THREAD

**Issue by quantum5** [DMOJ/site#14]
Possible implementation idea includes introducing a new Solution view, possibly with its own model, that leverages our commenting system.

Another idea could be replacement flatpage views and middleware which actually have working comments.

Either way the implementation shouldn't be too hard. (famous last words)

**Comment by quantum5** [comment]
@Xyene @FatalEagle what are your thoughts?

**Comment by FatalEagle** [comment]
Seems legit, if only we had more solutions for people to look at.

**Comment by quantum5** [comment]
I meant thoughts concerning implementation.

**Comment by FatalEagle** [comment]
Well, looks like blog posts support comments, so why not use that?

**Comment by quantum5** [comment]
The choice is between implementing a `Solution` model and rewrite the flatpages app. Using blog posts for solution is not too cool because that's for announcements and interferes with the home page.
