### ISSUE TITLE
CoffeeScript

### ISSUE THREAD

**Issue by Xyene** [DMOJ/site#141]
It looks pretty tempting: http://coffeescript.org/

**Comment by Xyene** [comment]
@quantum5 @FatalEagle

**Comment by quantum5** [comment]
I am not turned on by the idea of learning another language and translating constantly between two languages. I mean, you debug js in browser, not coffeescript.

**Comment by FatalEagle** [comment]
I don't see any reason to just as many technologies you can just because you may or may not look cooler to other people with a similar mindset.

**Comment by Xyene** [comment]
It's not for the probability of looking cool that I suggest this. It's fairly clear that we'll be maintaining this judge for a long time, so we might as well make it easier on ourselves in the long run. It offers a couple of benefits over raw Javascript:

* It's significantly more Pythonlike, which fits very well in terms of readability when used in conjunction with Jade. Conditionals in particular are identically (e.g. `"yes" if something else "no"`).
* It's whitespace sensitive, and uses it for scoping.
* Ruby-style string interpolation (`"#{someVariable}"`)
* It's much easier to define classes.
* If we ever need to use raw JS we can escape it with `.
* The docs are great.
* It claims to generate highly efficient JS code.

**Comment by FatalEagle** [comment]
> It claims to generate highly efficient JS code.
Really, so if a computer can do your job better than you can...

**Comment by Xyene** [comment]
Computers generally do your job better than you can. That statement was not meant to imply that Coffeescript would generate JS that's faster than what you could write by hand, but rather that using Coffeescript would not negatively impact performance. It doesn't invalidate the rest of its benefits, either.

**Comment by Xyene** [comment]
We're reaching a point where the amount of JS we write is minimal, and maintenance fairly painless.
