### ISSUE TITLE
Turn DM::Solutions into a wiki

### ISSUE THREAD

**Issue by FatalEagle** [DMOJ/site#142]
Because nobody wants to write all the editorials.

**Comment by quantum5** [comment]
You probably don't want everyone to be able to edit it though. Any ideas as to what an individual must have to edit?

**Comment by Xyene** [comment]
You mean MediaWiki?

**Comment by quantum5** [comment]
MediaWiki is slightly painful simply because it's PHP, and the look and feel is just not DMOJ.

**Comment by FatalEagle** [comment]
Solved the problem. Although I don't really see the issue about why people shouldn't be allowed. We can always ban those guys.

**Comment by FatalEagle** [comment]
Probably goes with automatically making a solutions page for every problem if that's how it's going to work.

**Comment by quantum5** [comment]
That requires rewriting the solution system.

**Comment by FatalEagle** [comment]
So the other solution is to let anyone edit it, and show it on a "recent actions" on the home page.

**Comment by quantum5** [comment]
I was thinking more like may be you have to have a certain number of points or rating before we let you edit.

**Comment by FatalEagle** [comment]
What if anyone could suggest edits, and people with high rating (>= 1700) can approve it?

**Comment by quantum5** [comment]
Could be solved easily by having more people to work on it.

**Comment by Xyene** [comment]
Nowadays anyone who'd want to write editorials knows to get in touch on Slack.
