### ISSUE TITLE
Sitelink search

### ISSUE THREAD

**Issue by Xyene** [DMOJ/site#143]
Because it's not working right now.

**Comment by quantum5** [comment]
Google detected it.

**Comment by Xyene** [comment]
The question is whether it was detected before my commit. If it was, then there's little chance of the box appearing now.

**Comment by Xyene** [comment]
Looks like Google's algorithms don't think that a table qualifies as search results. I suggest an actual search bar above user-links, which would offer a Github-style search across problems, users, comments and contests.

**Comment by quantum5** [comment]
Oh no. That means a rather massive schema change, and MySQL lock in.
