### ISSUE TITLE
Ensure resources are downloaded in parallel

### ISSUE THREAD

**Issue by Xyene** [DMOJ/site#151]

**Comment by Xyene** [comment]
Less trivial than I thought originally.

**Comment by Xyene** [comment]
The order is now optimal; @quantum5

**Comment by Xyene** [comment]
Nice break: https://github.com/DMOJ/site/commit/8679cb2e9104dc5ec35554ff61b4cf211bcb2b63

**Comment by quantum5** [comment]
The registration somehow broken.

**Comment by Xyene** [comment]
Broke statistics info-float.

**Comment by quantum5** [comment]
IDK how much faster the site can load.
