### ISSUE TITLE
Split #{form.media} into JS and CSS

### ISSUE THREAD

**Issue by quantum5** [DMOJ/site#153]
Due to #151, `block media` is now CSS only, and all forms that uses JS are currently broken.

**Comment by quantum5** [comment]
Refuse to fix the ghetto problem edit interface. Should just be removed.

**Comment by Xyene** [comment]
[Edit problem] already goes directly to the admin site, so the ghetto problem edit interface is never even used.

**Comment by quantum5** [comment]
Should delete it.

**Comment by quantum5** [comment]
I think that's all.
