### ISSUE TITLE
Hide real points during contest

### ISSUE THREAD

**Issue by Xyene** [DMOJ/site#159]
<https://dmoj.ca/submission/78224> should not be possible.

**Comment by quantum5** [comment]
Well one little problem, he could have just exited the contest and submit outside. The problem is available of "post-contest" solving immediately after joining.

**Comment by Xyene** [comment]
Your rebuttal only applies to this contest, where contestants may upsolve problems.

**Comment by quantum5** [comment]
Did you read the code? The code allows you to see all problems from all contests which you have a participation for outside of the contest.
