### ISSUE TITLE
Free Start Auto-Start

### ISSUE THREAD

**Issue by FatalEagle** [DMOJ/site#16]
Unchecking free start to put a free start in the upcoming contests section and checking it before anyone joins when it actually starts is really tedious.

**Comment by quantum5** [comment]
This could be arranged. When the free start variable is added, its entire purpose is so that the API can return a real date.

**Comment by quantum5** [comment]
Fixed as side effect of restructuring contest system.

Implemented in 3666d308bb92ebb693b561109f2957523d6da4b7...54486f53d782c885127261261a47abe6dd8461ed.
