### ISSUE TITLE
Multiple Submissions from Same User on "Best Submissions" page

### ISSUE THREAD

**Issue by Phoenix1369** [DMOJ/site#165]
More specifically, in TSOC P3: https://dmoj.ca/problem/tsoc15c2p3/rank/

**Comment by quantum5** [comment]
Exact circumstance is that those submissions have the exact same execution time.

**Comment by quantum5** [comment]
This seems really sketchy. The subquery runs and gives perfect results, but wrapped it in `id IN (...)` makes it produce wrong results. I call MySQL bug.

**Comment by quantum5** [comment]
> Something, somewhere, somewhen, must have happened differently...
