### ISSUE TITLE
Debian jessie on servers

### ISSUE THREAD

**Issue by quantum5** [DMOJ/site#166]
Debian jessie was released yesterday. We should upgrade so that we get the latest version of everything. For example, compiling GCC 4.9.1 for full C++11 support is not the easiest thing ever.

**Comment by quantum5** [comment]
Similar to #139, this update is going to be delayed since MySQL 5.6 is not yet available for jessie, and we are not sure if this is going to work on the hosting platforms.

**Comment by quantum5** [comment]
Clearly jessie judges are possible.

**Comment by quantum5** [comment]
MySQL jessie builds are now available.

**Comment by quantum5** [comment]
Linode also has a upgrade guide, so we should be fine: https://www.linode.com/docs/security/upgrading/upgrade-to-debian-8-jessie

**Comment by quantum5** [comment]
Forgot to mention the `jessie` update on the site a couple of weeks ago.

**Comment by Xyene** [comment]
Upgrade on Herculaneum is necessary for https://github.com/DMOJ/judge/issues/36

**Comment by quantum5** [comment]
Herculaneum is now jessie.

**Comment by quantum5** [comment]
I don't think we have any server that's not jessie
