### ISSUE TITLE
Random Button should Select from Unsolved Problems if the box is checked

### ISSUE THREAD

**Issue by Phoenix1369** [DMOJ/site#170]
Also, (and this is purely my personal opinion) wouldn't it look better if the Random and Filter buttons were the same size, but different colors, or something to that extent?

**Comment by quantum5** [comment]
Implemented.

**Comment by quantum5** [comment]
Actually should probably random from selection.

**Comment by quantum5** [comment]
Closing now that I am actually fairly certain this is working.
