### ISSUE TITLE
RFC: users should be able to view details of a submission without having solved the problem

### ISSUE THREAD

**Issue by Xyene** [DMOJ/site#186]
Currently we allow users who have solved a problem to view submission details (testcases etc.) of any submission for that problem.

Should submission details (but not source) be accessible to everyone?

**Comment by Xyene** [comment]
@quantum5 @FatalEagle

**Comment by FatalEagle** [comment]
No, it's metadata that might give unfair advantage (like seeing which case others fail, and if they have a common bug, or something).

**Comment by quantum5** [comment]
This sort of reveals the points and batching structures, allowing users to decide beforehand whether to even attempt the problem, exempt from the last place when not rated for all.

**Comment by Xyene** [comment]
I understand that both of you are thinking of this in a contest situation (natural considering we just finished with the DMPG), but the target of this ticket is not contest mode. Of course, this data would be hidden during contests. It would only apply for regular submissions, similar to Codeforces (but without full source accessibility).

@quantum5, I think @FatalEagle makes a good point, but not because it reveals the points and batching structures. A contestant can just submit a `print 0` solution to probe points without penalty.

Regardless, metadata viewing should be strictly for out-of-contest submissions. There's no reason to hide it out-of-contest.

**Comment by quantum5** [comment]
@Xyene I have decided to penalize those with 0 score submissions:

```python
if not contest.rate_all:
    users = users.filter(submissions__gt=0)
````

`print 0` hence gives rating.

**Comment by Xyene** [comment]
Let's not change anything without discussing it first. I remember @FatalEagle had an opinion on zero-score submissions.

**Comment by quantum5** [comment]
No like I mean that code has been there since the very beginning.

**Comment by Xyene** [comment]
qq

anyways off the original topic.

**Comment by Xyene** [comment]
Superseded by #430.
