### ISSUE TITLE
Coloured compiler messages

### ISSUE THREAD

**Issue by quantum5** [DMOJ/site#189]
GCC since 4.9 supports fully coloured error messages. By passing `-fdiagnostics-color=always`, we can tell it to output colours to the pipe, which we can interpret on the site with https://github.com/ralphbean/ansi2html to generate colourized html error message. I am not sure how worth this is, but it's cool nonetheless.

**Comment by Xyene** [comment]
Fun read: http://insanecoding.blogspot.ca/2014/04/gcc-49-diagnostics.html

On the other hand, I think this should be judge-side, with the judge message being rendered as |safe.

**Comment by Xyene** [comment]
Working as expected.

![](https://sc-cdn.scaleengine.net/i/0d1d03c0dbece0f3a0e4faf994cea6a7.png)

**Comment by quantum5** [comment]
It is done by @Xyene.
