### ISSUE TITLE
Installation of site and judge components not obvious

### ISSUE THREAD

**Issue by Xyene** [DMOJ/site#191]
As in fairly obscure.

**Comment by Xyene** [comment]
We should have proper installation documentation.

Also, we ship `pagedown`, but `pagedown` is not in `INSTALLED_APPS` for the template `settings.py`. How are people supposed to find pagedown like this?

Installation shouldn't be this hard, so we should slowly work towards making installation easier.

**Comment by Xyene** [comment]
`django_ace` is also required for smooth operation, though nowhere do we state this.

**Comment by WallE256** [comment]
@Xyene I agree  :smile:

**Comment by quantum5** [comment]
May be #226 would help with this.

**Comment by Xyene** [comment]
Superseded by #424, I guess.
