### ISSUE TITLE
PDF improvements

### ISSUE THREAD

**Issue by Xyene** [DMOJ/site#192]
#191

We always show the "View as PDF" link, even when we can't actually render PDFs!

By default we attempt to use Pandoc + Latex, which is actually harder than installing `wkhtmltopdf`. But wait, we also have `WEBKIT_PDF` to set to `True` if we want to actually use it. I propose to remove the Pandoc + Latex renderer as the Webkit renderer performs much better in all respects and is easier to install. The `LatexPdfMaker` requires so many Latex packages to even look half-decent (where half-decent is much less decent than `WebkitPdfMaker`) it's impractical to install all.

Additionally, the `View as PDF` link should only be displayed if we can actually render PDFs.

**Comment by quantum5** [comment]
When I wrote `WebkitPdfMaker`, it was for testing. We really had no clue that it would actually work so nicely. Sort of an experimental technology that has never gotten out of that status, even though we removed the `(beta)` label already.

**Comment by quantum5** [comment]
The LaTeX-based PDF generator is still in the code yet it is completely ignored by your change.

**Comment by Xyene** [comment]
Simple because I wouldn't call it "working" by any stretch of the word. Tables are completely broken in the LaTeX generator, and there's no longer any point to fixing it.

**Comment by quantum5** [comment]
May be we should be deleting it then

**Comment by Xyene** [comment]
Maybe!
