### ISSUE TITLE
Teacher supervision support

### ISSUE THREAD

**Issue by Xyene** [DMOJ/site#200]

**Comment by quantum5** [comment]
* Securable organizations, i.e. no public joining
    * May be a secret key for joining
* Organization admins should get to see all member's submissions

**Comment by quantum5** [comment]
Now we need to add homework assignments. They could be implemented as organization-private contests.

**Comment by quantum5** [comment]
@Xyene is there anything here that cannot be done as organization-private contests as currently implemented?

**Comment by Xyene** [comment]
No, though I can't say I really remember the original scope of this issue. If we ever go for a more ambitious classroom system, that will be tracked separately.
