### ISSUE TITLE
More "modern" look

### ISSUE THREAD

**Issue by Xyene** [DMOJ/site#205]

**Comment by Xyene** [comment]
Nicer text fields:

![!!!](https://sc-cdn.scaleengine.net/i/4e808b5c74bafdc723932b36cbcf302c.png)

```css
input[type=text],input[type=password]{
    padding: 4px 8px;
    font-size: 14px;
    color: #555;
    background-color: #FFF;
    background-image: none;
    border: 1px solid #CCC;
    border-radius: 4px;
    box-shadow: 0px 1px 1px rgba(0, 0, 0, 0.075) inset;
    transition: border-color 0.15s ease-in-out 0s, box-shadow 0.15s ease-in-out 0s;
	  display: inline-block;
}
```
(Padding is love, padding is life.)

**Comment by quantum5** [comment]
Ah yes you managed it. I gave up last time.

**Comment by Xyene** [comment]
:)

The font between Filter and Random is different though...

**Comment by quantum5** [comment]
I suspect you can change `Filter` to a fake button instead of a notoriously hard-to-fake real button.

**Comment by Xyene** [comment]
![](https://sc-cdn.scaleengine.net/i/45c373b60bfab6de109fb581966f9209.png)

Relevant styles impossible to post; DOM changes necessary.

This is a big change, should ask more people about their thoughts on it. It does have a couple of benefits though:

* Significantly smaller
* No duplicate Home click area
* Branding of the DMOJ logo
* Navbar slightly taller (by a few pixels): enough room to add some more meat to user-links

**Comment by quantum5** [comment]
I can't help but ask what you are planning for "mobile" friendliness.

**Comment by Xyene** [comment]
The same mobile style, for now.

**Comment by Xyene** [comment]
Mostly implemented the navbar.

Outstanding issues:
* Dropdown menus look horrible and work even worse
* Mobile style is wrecked
* `info-float`s are not updated to the new height of the navbar

**Comment by Xyene** [comment]
Unblocked the timer with a new style.

**Comment by Xyene** [comment]
Mobile style is working again. It'll need a restyle to fit with the new theme, though.

**Comment by Xyene** [comment]
`info-float` scrolls properly again.

**Comment by Xyene** [comment]
New problem search form:

![](https://sc-cdn.scaleengine.net/i/608dd69a4492d8034991b4865f392376.png)

All inputs trigger `form.submit()`, making searching more streamlined. Would be cool if the problem table was Ajax'd as well, but there's only so much time in a day.

**Comment by Xyene** [comment]
Used a bit of media query magic to make the page scale better to large displays.

![](https://sc-cdn.scaleengine.net/i/d98b9a562c7aa42cd92471282dca44d2.png)

All content is capped to `max-width: 1380px`, with a light gray filling `body`. At the very least, this makes the Users page look a _lot_ better: no more 20cm gap between Elo rating and usernames.

**Comment by Xyene** [comment]
Made a new logo SVG. It's unoptimized, but significantly smaller than a 1024x1024px PNG.

**Comment by Xyene** [comment]
Implemented a 40px-height footer, with `misc_config.footer` controlling the content.

**Comment by Xyene** [comment]
Fixed login menu to work on small screens.

**Comment by Xyene** [comment]
Problem page tabs!

![](https://sc-cdn.scaleengine.net/i/a97c7283a0e4a0b43d0aec670ee857c5.png)

View as PDF will need a new home.

**Comment by WallE256** [comment]
This is how it looks in IE 8: http://i.imgur.com/VzaLVDV.png

**Comment by Xyene** [comment]
@WallE256 

* Logo doesn't show up due to lack of [**inline SVG support**](http://caniuse.com/#search=svg)
** Can be fixed with a switch, displaying a PNG logo where SVG is not supported
* Navbar/pagination not colored due to lack of [**CSS3 colors, namely rgba()**](http://caniuse.com/#search=rgba)
** Can provide a fallback premultiplied color that looks like `rgba(0, 0, 0, 0.77)` on a white background

**Comment by WallE256** [comment]
@Xyene 
Good to know! Anyway, according to http://www.w3schools.com/browsers/browsers_explorer.asp , IE 8 represents ~1% of web users, mainly XP computers, and usually school computers. :smile:

**Comment by FatalEagle** [comment]
> The following figures are based on W3Schools' users, and are extracted from our Browser Statistics:
Most people who visit W3Schools wouldn't be using IE anyway.

**Comment by Xyene** [comment]
@WallE256 @FatalEagle 

Stats from DMOJ analytics:

![](https://sc-cdn.scaleengine.net/i/8065a020b00947a903748c49de89f6cb.png)

0.65% of users use IE. Of those that do...

![](https://sc-cdn.scaleengine.net/i/afabae3956e8ee46eaf170ebcf42f79e.png)

14.81% of them use IE <= 8.

**Comment by WallE256** [comment]
Coc Coc? This sounds nice :) But of course, we care about the 14.81% of the IE users.

**Comment by Xyene** [comment]
[IE 8 doesn't honor noscript styling... properly.](stackoverflow.com/questions/2912175/noscript-tag-appears-even-if-javascript-is-turned-on-in-ie8)

**Comment by Xyene** [comment]
PNG logo:

![logo2](https://cloud.githubusercontent.com/assets/1403503/9706808/a63ae4ca-54c0-11e5-8711-a03f28e49a24.png)

Though on IE 8 this implies hacks with `AlphaImageLoader`, and all the performance penalties that come with it.

**Comment by Xyene** [comment]
Perhaps the user list can be tabbed between Users and Organizations, removing a navbar item. The Organizations list can also be updated to look nicer, along with #18

**Comment by quantum5** [comment]
Some work-in-progress to do mobile menu without JS.
```css
#nav-container:focus > #nav-list, #nav-container:active > #nav-list, #nav-container:hover > #nav-list {
  display: block !important;
  top: 36px;
}
```

**Comment by Xyene** [comment]
This issue is incredibly long, so long that Github omits over 200 commits by default. It's gotten to the point where it is impossible to really tell what is being done, so I'm closing this mega-ticket in favour of smaller ones to be created in the future.

The original goal, making DMOJ look less like a site from the 90s, has already been accomplished.
