### ISSUE TITLE
Cannot migrate

### ISSUE THREAD

**Issue by WallE256** [DMOJ/site#206]
Hey, I started working again on the site, and I reinstalled all the things, but now i cannot migrate. Here is the error: http://pastebin.com/MJgLxGsQ

**Comment by quantum5** [comment]
Check if the database user has the permission to `CREATE TABLE`

**Comment by WallE256** [comment]
It uses the root user

**Comment by WallE256** [comment]
I just realized that I don't need the old data and made a temporary sqlite database. Now i have another problem. Would you mind if you join irc?

**Comment by quantum5** [comment]
SQLite doesn't work with the judge at the moment.

Also, since you said "reinstalled all the things", I am led to believe that you are now using Django 1.8, which requires a minimum MySQL version of 5.5. You might want to check that.

**Comment by WallE256** [comment]
I have Django 1.7.7, as I have a "pip freeze" from Tudor at my first atempt. And for mysql i use MariaDB 5.5.44. The pip freeze I use: https://gist.github.com/WallE256/ffef02433598eb08f9f6

**Comment by WallE256** [comment]
I emailed admin@dmoj.ca for more details. Closed
