### ISSUE TITLE
Bigger submit box

### ISSUE THREAD

**Issue by Xyene** [DMOJ/site#209]
...seriously. It's hardly usable for anything more than a few snippets of Python at its current size (without fullscreening).

**Comment by quantum5** [comment]
It is bigger now...

**Comment by Xyene** [comment]
No, the issue now is that it does not take up the full screen height, just the width.

**Comment by quantum5** [comment]
Now it's done.

**Comment by Xyene** [comment]
Almost, except the resize handler isn't called on an initial page load.

![](https://sc-cdn.scaleengine.net/i/b6453daaf5dbc5965f02280db7d1ac27.png)
