### ISSUE TITLE
RFC: move editorials from navbar tab to link on problem page

### ISSUE THREAD

**Issue by Xyene** [DMOJ/site#210]

**Comment by FatalEagle** [comment]
You already removed it though.

Also its so glitchy, sometimes the hover doesn't work when I'm in a user's page.

**Comment by Xyene** [comment]
I did, now I'm asking for comments on that change.

**Comment by FatalEagle** [comment]
But you still haven't added editorials to problems, even though you removed them from the navbar already.

**Comment by Xyene** [comment]
Haveyouseen#205theressomuchtodobeforewegettoeditorialsitdoesnthelpthatimtheonlyoneonlineandavailabletodoanything.

**Comment by FatalEagle** [comment]
Okay but one would assume one would have a new system functional before completely disposing of the old system...

**Comment by Xyene** [comment]
One **might** assume that, but analytics showed few enough people ever visited the editorials in the last month to warrant it not being a priority (as opposed to a new style that would leave an impact on contestants participating in the first DMOPC).

**Comment by FatalEagle** [comment]
Okay but you already fixed the original issue that made you want to remove everything. Why not add it back in 2 minutes.

**Comment by Xyene** [comment]
I've added it back.

**Comment by Xyene** [comment]
Well, it's gone from the navbar and is now a tab on the problems page.
