### ISSUE TITLE
Yellow colored AC if score is not max

### ISSUE THREAD

**Issue by FatalEagle** [DMOJ/site#212]
It can be misleading. http://screencloud.net/v/tru1

**Comment by Xyene** [comment]
Suggested color (in hex)?

**Comment by Xyene** [comment]
Chartreuse (#DFFF00) looks nice:

![](https://sc-cdn.scaleengine.net/i/f7109996dfd7b8fc84d9163eb1b7c8de.png)

**Comment by Xyene** [comment]
It's working, though
