### ISSUE TITLE
Remove weird empty space in sidebar

### ISSUE THREAD

**Issue by kobortor** [DMOJ/site#214]
http://imgur.com/4aMBQb0

**Comment by FatalEagle** [comment]
Who even uses DMOJ like that...

**Comment by Xyene** [comment]
Clearly people *do* use the DMOJ like that. I'm not the only one! I'M NOT CRAZY!

The issue is a side-effect of #205, should be easy to fix. Will do so now.

**Comment by kobortor** [comment]
Thanks tut

**Comment by Xyene** [comment]
Fixed.

**Comment by Xyene** [comment]
Further info on ongoing progress with mobile-sized screens can be found at #96
