### ISSUE TITLE
Spam laws

### ISSUE THREAD

**Issue by Xyene** [DMOJ/site#221]
We should be OK as per <http://fightspam.gc.ca/eic/site/030.nsf/eng/home>. Summarized:

To send a commercial electronic message to an electronic address, you need to have the recipient's consent, to identify yourself, to offer an unsubscribe mechanism and to be truthful.

*    **Consent:** You must have a form of valid consent.
*    **Identification:** Clearly identify yourself and your organization. You must include your mailing address. You must also include a phone number for accessing an agent or a voice messaging system, an email address, or a web address for you or the person on whose behalf you are sending the message.
*    **Unsubscribe mechanism:** Provide an unsubscribe mechanism that is functional for 60 days.
*    **Truth in advertising:** Your messages must not be false or misleading. They must not have false or misleading sender information, subject matter information, URLs and/or metadata.

A key piece of info here is that CASL applies to *commercial electronic message*s, not *educational messages* ([even the TDSB had this issue](http://www.tdsb.on.ca/CanadaAntiSpamLegislation.aspx)).
> Electronic messages sent for informational purposes, like student progress or information nights, will continue to be sent.

So while we're in the clear, we should still provide an opt-in button on registration (should be unchecked by default to comply with CASL in case of future commercialization) to allow new users to subscribe, and the newsletter forms should be relocated to a more friendly home.

**Comment by quantum5** [comment]
We actually ask for newsletter opt-in now, and it actually works.

**Comment by Xyene** [comment]
Yeah sure, except you can't opt out on profile page edit.

**Comment by quantum5** [comment]
Your excuse to reopen this has been removed by #402.
