### ISSUE TITLE
Make site more presentable on fresh install

### ISSUE THREAD

**Issue by Xyene** [DMOJ/site#226]
![](https://sc-cdn.scaleengine.net/i/4d41f73cdc15952324a29ad60e4aa03a1.png)
![](https://sc-cdn.scaleengine.net/i/fc4f40f0617220f35ca5ed72ef385c62.png)
![](https://sc-cdn.scaleengine.net/i/58541e645dec2638cdf06a7d93fda6771.png)

A lot of tables should have a conditional on `|length`, displaying a more admin-friendly "There is no {insert relevant data name here} data yet. [Add some.]". We can also ship a fixture with a "Hello, World!" problem, a post on the main page and a comment on it.

**Comment by quantum5** [comment]
Conditional on `|length` is quite crazy as all querysets are `False` when empty.

**Comment by Xyene** [comment]
This is done.

![image](https://user-images.githubusercontent.com/1403503/33513702-3c3990dc-d716-11e7-874f-624e1a8e72ab.png)

Ships with a blog post, a comment, aplub and related problem types.
