### ISSUE TITLE
RFC: only online judges should be visible to regular users

### ISSUE THREAD

**Issue by Xyene** [DMOJ/site#233]
Do people really care that we have 10 judges for testing?

/cc @quantum5 @FatalEagle

**Comment by FatalEagle** [comment]
Probably not. Although it doesn't change much.

**Comment by Xyene** [comment]
Implemented. To be fair, it was just a one line change. Now we can add language graphs and other fun stuff below the judge table!

**Comment by Xyene** [comment]
This is what a regular user sees now:

![](https://sc-cdn.scaleengine.net/i/6199719d9315cac9167ea435de44c791.png)

For admin, it is unchanged.

**Comment by quantum5** [comment]
Umm it kinda defeats the original reason of the page, which is for users to see which judges are DOWN.

**Comment by quantum5** [comment]
Despite the debatable merits of this change, it is implemented.
