### ISSUE TITLE
RFC: code highlighting in blog posts

### ISSUE THREAD

**Issue by Xyene** [DMOJ/site#234]
We're an OJ, so it's natural that we (or others who install the DMOJ site) would want to display code on the front page. Currently, we don't support an easy way to do this, since `pygments-github.css` is not included on the main page. On the other hand, it does slow down the loading speed of the front page, which might impact PageRank. A reasonable middle ground would be requiring `<!--highlighting-->` to be declared in blog post text (similar to the trick we used to pull for math).

**Comment by quantum5** [comment]
The tag is a really bad idea since shoving that tag on one post will make it stick for half a year.

**Comment by Xyene** [comment]
To be fair, the system should not be blamed for the fact that we hardly ever publish.

**Comment by quantum5** [comment]
Might as well inline the CSS into our main stylesheet.

**Comment by Xyene** [comment]
`pygments-github` is just 367 bytes, but I wouldn't suggest directly adding it into the main stylesheet due to #240 - perhaps we can invoke the compressor for this task.

**Comment by Xyene** [comment]
Well, it's there.
