### ISSUE TITLE
More site statistics

### ISSUE THREAD

**Issue by Xyene** [DMOJ/site#237]
More than one user has recommended we add more site statistics like we had on https://dmoj.ca/post/31-statz.

**Comment by quantum5** [comment]
We could use `highcharts` for this, similar to what we already did for our user rating chart.

However, I seem to remember that @Xyene expressed sentiments against the library.

**Comment by quantum5** [comment]
What other statistics should we offer?

**Comment by Xyene** [comment]
This info is most interesting for admins, who can set up something like Graylog for monitoring.

![image](https://user-images.githubusercontent.com/1403503/33071999-bbe823d6-ce8b-11e7-8767-9a5688e10a68.png)
