### ISSUE TITLE
Lazy-load images

### ISSUE THREAD

**Issue by Xyene** [DMOJ/site#239]
Lazy-loading Gravatars sounds like a great idea, particularly because comments make up a substantial portion of the download overhead for a page. And Gravatars are *not* cached, so they're requested practically every page load.

**Comment by quantum5** [comment]
May be we need a parser for this #274, to use in comments. No one needs to load megabytes of `.gif`s in a stupid comment.

http://luis-almeida.github.io/unveil/ seems highly legit.

**Comment by quantum5** [comment]
Complete as specified.

**Comment by quantum5** [comment]
Since we lazy-load home page, unveil is now available on every page.
