### ISSUE TITLE
Virtual Participation

### ISSUE THREAD

**Issue by FatalEagle** [DMOJ/site#24]
For those people always complaining DMOPC starts too early, allow people to start at both a fixed time or at their own time. Possibly separate scoreboards for both kinds of people, or merge them both with a special indicator for virtual participants (like a small tick next to their handle). Check out virtual participation from http://codeforces.com/contests for ideas.

**Comment by quantum5** [comment]
Suggested solution: create a week long free start contest for those people.

**Comment by Xyene** [comment]
Thanks to #205 we can now have three tabs: Mixed, Real, and Virtual. Mixed would show them merged with a tick.

Apart from the UI aspect, this should be doable with a `virtual` `BooleanField` in the `ContestParticipation` model and a corresponding migration.

**Comment by quantum5** [comment]
We can trivially use the spectate flag in #405 to implement virtual contests, if we do not want to allow users that participated in the normal contest from participating in the virtual contest, in general allow only one participation.

However, we can do better. We can introduce a `virtual` integer field, that allows you to fake the participation any number of times. This would be `unique_together` with both the `contest` and `user`. A `virtual` value of zero applies during the normal contest, and current participation rules apply. Post contest, we can allow increasing `virtual` values. The first time the user joins a virtual contest, a participation with `virtual = Max(virtual) + 1` is created. The user is allowed to participate in the contest, however leaving it will seal this virtual contest forever. (To prevent abuse, if no submission is made we drop the participation.) The next join will instead create a different participation, following the same rules. This might pose some trouble for ranking though, so we can simply have chronological list of all virtual contests instead, and perhaps only rank the best virtual contests with similar logic to submission rankings (oh god another raw SQL).

/cc @FatalEagle @Xyene

**Comment by Xyene** [comment]
This sounds good; we can by default show the most recent virtual contest ranking, with right/left arrows to move between them (like for comments), and have a meaningful subtitle (like "Virtual ranking for your participation 5 hours ago"), potentially with moment.js magic.

**Comment by Xyene** [comment]
Outstanding issues:
* ranking column shouldn't be displayed in user participation table (since only live contest will have it)
* contest list buttons need to be hooked in
* contest list user count includes number of ContestParticipations, not number of distinct users (this needs a DB change to be optimal)

**Comment by Xyene** [comment]
This has been working well without any major issues.
