### ISSUE TITLE
"Report an issue with this problem" link on problems

### ISSUE THREAD

**Issue by Xyene** [DMOJ/site#241]
Would optionally email admins.

**Comment by quantum5** [comment]
May be email authors?

To prevent spam, may be we send notices daily?

**Comment by FatalEagle** [comment]
I think they could spam anyway if they wanted to, after all they have your @dmoj.ca addresses.

**Comment by quantum5** [comment]
It hurts our sending reputation when it's our servers mailing it.

**Comment by Xyene** [comment]
A user would have to write a script to be able to send enough emails to even come close to hitting our cap. By that point in time we'll have noticed the inbox flood and IP-banned the user.

**Comment by quantum5** [comment]
Once you email gmail enough times with BS, your mails goes into spam and **** hits the fan.

**Comment by Xyene** [comment]
By that logic we should be batching judge and site errors, because in the *unlikely* event that we get an Ajax error we'd "spam" 100+ times. There are more malicious things people can do *now* that nobody does (submit TLE solutions to IOI problems, spam comments, etc.) Errors in problem statements are just as mission-critical as judging errors, and should be treated as such: they disrupt the user experience.

**Comment by quantum5** [comment]
Succeeded by #327.
