### ISSUE TITLE
Users column on problem list unclear

### ISSUE THREAD

**Issue by Xyene** [DMOJ/site#242]
The number displayed is the number of people who attempted the problem, but the link is to the best submissions page.

**Comment by quantum5** [comment]
This is "intentional" since the only way to implement number of people on best submissions is to do a `LEFT OUTER JOIN` with multiple conditions, which I can't coerce Django to do.

**Comment by quantum5** [comment]
Experiment performed on #237 seems to indicate that conditional expressions introduced by #139 will solve this issue.

**Comment by quantum5** [comment]
This is done.
