### ISSUE TITLE
Upcoming contest stream

### ISSUE THREAD

**Issue by Xyene** [DMOJ/site#243]
![](https://sc-cdn.scaleengine.net/i/436422b3df1119052fd043acbe26b215.png)

Trivial to do, though it will require contest timing to be merged into the main JS file for optimal performance.

/cc @quantum5 @FatalEagle

**Comment by FatalEagle** [comment]
The new plan is to take over CodeForces?

**Comment by Xyene** [comment]
DMOJ: the melting pot of online judges.

**Comment by quantum5** [comment]
Approve.

**Comment by quantum5** [comment]
Is totally done.
