### ISSUE TITLE
Obfuscation of mailto

### ISSUE THREAD

**Issue by Xyene** [DMOJ/site#246]

**Comment by Xyene** [comment]
#274

**Comment by quantum5** [comment]
[More popular StackOverflow solution](http://stackoverflow.com/a/748804/1090657) seems to say that we should merely encode the email as entities.

**Comment by Xyene** [comment]
Empirical data for urlencode obfuscation points to it being ineffective, but nevertheless since creating this ticket I have yet to see one email on the site apart from that which we have on our contact page.

Not worth the time and resources to address.

**Comment by quantum5** [comment]
Forgot to mention that CloudFlare obfuscates the emails anyway.
