### ISSUE TITLE
Decide whether to display output prefix on site, not in init.json

### ISSUE THREAD

**Issue by FatalEagle** [DMOJ/site#247]
The current system really doesn't make sense, since it requires a complete rejudge to populate output prefixes for old submissions (that were made during the contest).

**Comment by Xyene** [comment]
You'd have the same issue when someone would like to increase the output prefix. Hence this wouldn't solve the issue, it would just defer it to another action: instead of rejudging to increase output prefixes, you'd now have to rejudge to decrease output prefixes.

**Comment by FatalEagle** [comment]
In the problem edit form, you can have "limit output prefix". You can then limit it to 0 for contests, or whatever you wanted to decrease it to.

**Comment by Xyene** [comment]
Oh, so you are referring to a site-defined override for what's specified in
the init.json?

**Comment by FatalEagle** [comment]
Yes (with the default still being what it is).

**Comment by Xyene** [comment]
For sanity reasons the output prefix length should then be `min(site_prefix, init_prefix)`.

**Comment by FatalEagle** [comment]
Wait, I meant that the judge will give its own output prefix - but then the site chooses how much to display.

**Comment by FatalEagle** [comment]
This should really be done soon, as there are already [evil users](https://dmoj.ca/submission/108537) abusing output prefix in contest.

**Comment by quantum5** [comment]
Database change would be required for this change in order to store the limit.

The actual limiting will be done in the template.

**Comment by Xyene** [comment]
Is there any use case for this outside of contests? Seems like it would be cleaner to implement the necessary changes in the contest admin form.

**Comment by quantum5** [comment]
Whether you put this on problem or contest admin has no effect on the necessity of database modification.

**Comment by Xyene** [comment]
Of course a database modification is needed, the question is where: Problem, or ContestProblem? Depends on the desired use. I'd say ContestProblem would avoid abuse by certain people (e.g., setting prefix length to 500kb on judge side and controlling displayed output on the site).

**Comment by quantum5** [comment]
Works.
