### ISSUE TITLE
Contest description template

### ISSUE THREAD

**Issue by FatalEagle** [DMOJ/site#248]
It's boring to copy paste the stuff again and again, especially since the site already knows the date, time, authors, whether it's rated or not, etc.

Automatically prepend this information to the contest info page

```
#{banner if it exists}
<hr>
<h2>General Contest Information</h2>
<strong>Start time:</strong>            #{timeanddate link with contest title}
<strong>Duration:</strong>              #{contest length}
<strong>Authors:</strong>               #{author names}
<strong>Number of problems:</strong>    #{problem count}
<strong>Expected Difficulty:</strong>   #{how many stars}
<strong>Contest style:</strong>         #{real-time or virtual}
<strong>Scoring system:</strong>        #{static, dynamic, pretests}
<strong>Hacks:</strong>                 #{hacks or not}
<strong>Registration required:</strong> #{free, list organization(s), or register in advance}
<strong>Score distribution</strong>     #{e.g. 100, 100, 100, 100, 100, 100}
<strong>This round is #{rated_or_not}</strong>
Link to tips and help pages.
<hr>
```

**Comment by FatalEagle** [comment]
Probably score distribution and scoring system can be somehow combined.

**Comment by Xyene** [comment]
A proposed, similar template:

```md

## General Contest Information
**Authors:**               #{author names}
**Number of problems:**    #{problem count}
**Hacks:**                 #{hacks or not}
**Score distribution**     #{e.g. 100, 100, 100, 100, 100, 100}
**This round is #{rated_or_not}**
Link to tips and help pages.

--
```

Start time and duration (and therefore contest style) will be added to a separate, global location as part of #205 (likely a header at the top of the page, using the new format for displaying contests as shown in the contests listing). We don't actually have more than one scoring system right now, and private organization contests are *private* and not shown on the general listing anyways.

**Comment by FatalEagle** [comment]
What about difficulty estimation? it could be fun.

**Comment by Xyene** [comment]
It would probably be something the author would add manually, since we'd require another field in the `Contest` model for it otherwise.

**Comment by Xyene** [comment]
Sounds like the time this would take to implement far outweighs the time saved cloning over contest templates. timeanddate links certainly appear by default, now.

And hey, nowadays we're not the ones who deal with writing contest descriptions up 😁
