### ISSUE TITLE
Gravatar image not visible when viewing profile

### ISSUE THREAD

**Issue by descrip** [DMOJ/site#250]
In Chromium 45, whenever I view a profile, the user's Gravatar dosn't show. The image is in the document -- I can "Right Click > View In New Tab"  and view the image separately.

![Image](https://i.imgur.com/uZUOTw4.png)

This problem doesn't occur with Firefox 40.

![](https://i.imgur.com/9eiYhdc.png)

**Comment by Xyene** [comment]
Are you able to see the 3 Gravatars on [this page](https://dmoj.ca/debug/) using Chromium 45? What extensions do you have installed in Chrome? Got an antivirus? Adblocker? Try disabling them for the debug page: Avast is known to sometimes block Gravatars with its web plugin, and adblockers might be detecting them by url to be some sort of ad.

**Comment by descrip** [comment]
The problem was on my end. [Ghostery](https://www.ghostery.com/en/) blocks the Gravatar image. I didn't think about Ghostery because I have the same addon on Firefox, but the Gravatar isn't blocked there for some reason.

**Comment by Xyene** [comment]
Aha, thought something sketchy was going on :wink:. Glad that you got it sorted out.

**Comment by FatalEagle** [comment]
@Xyene 
What's sketchy is that emoticon.

**Comment by Xyene** [comment]
Hush, hush, @FatalEagle. I wouldn't know what you are talking about.
