### ISSUE TITLE
Contest template revamp

### ISSUE THREAD

**Issue by Xyene** [DMOJ/site#252]
#205 #248 #24 #55 

![](https://sc-cdn.scaleengine.net/i/ace0f7cf4f0059441d2e2715522ea20e.png)

/cc @FatalEagle @quantum5

**Comment by Xyene** [comment]
This is implemented, though the TZ passed to timeanddate is supposedly UTC (it's not). @quantum5

**Comment by quantum5** [comment]
As I seem to have fixed the timezone issue over a month ago, there is nothing left remaining in the scope of this ticket.
