### ISSUE TITLE
info-float vs tabs

### ISSUE THREAD

**Issue by Xyene** [DMOJ/site#253]
We've been using info floats for a while now, and they're convenient on long pages like problem statements. More recently, we've started using tabs on some pages, but tabs and info floats don't exactly coexist harmoniously.

Tabs can be used to enhance practically every page:
- Contest listing can have a calendar tab (#55)
- Organization view can have a "Members" tab
  - It can also have an "Manage" tab for easy admin access
- Contest template can have a "Problems" tab (once contest has started) as well as a "Ranking" tab (once the contest has ended)
  - It can also have an "Edit" tab for easy organizer access
- Users template can have an "Organizations" tab, removing the iffy dropdown option

Tabs can be used everywhere! There's only one catch: they can't be used on problem statements, since they tend to be so long that it's inconvenient to navigate to the top of the page to switch tabs. However, this makes a disconnect between most styles and the problem pages. That's not optimal.

But the benefits are substantial. Just take a look at how nice the contest pages could look:

![](https://sc-cdn.scaleengine.net/i/6546c54314940b77dcccac81173349c7.png)

Thoughts? Should we go ahead with tabs, everywhere but on problem statements? The tabs look a bit _too_ Bootstrap-y -- perhaps they'd look better restyled?

/cc @quantum5 @FatalEagle @WallE256

**Comment by FatalEagle** [comment]
Tabs look too hipster and modern for my taste. They imply a strong relation between what they group. It feels really strange to navigate to problems and edit on the tab. I can deal with contest information and rankings grouped together though.

**Comment by Xyene** [comment]
I agree that the style can do with some work. The current tabs simply don't fit with our style. Here is an edit on them, which fits a little bit better.

![](https://sc-cdn.scaleengine.net/i/9567e400c2bd230827ac8323e42d2402.png)

Square borders, and a lighter gray for the non-active tabs instead of blue.

**Comment by Xyene** [comment]
Also, clarification: the Problems tab would only exist post-contest, @FatalEagle. It wouldn't replace the current behaviour of redirecting to the Problems menu item on join.

**Comment by Xyene** [comment]
We've been doing this for contest pages for a while.
