### ISSUE TITLE
Option to specify custom og:image in blog/contest posts

### ISSUE THREAD

**Issue by Xyene** [DMOJ/site#256]
![](https://sc-cdn.scaleengine.net/i/824e4e135e55e6c0b08e49ea6e28d4b0.png)

just won't do for contests like the DMOPC, which have their own banners.

**Comment by Xyene** [comment]
<http://www.h3xed.com/web-and-internet/how-to-use-og-image-meta-tag-facebook-reddit>

Perhaps we could do some sketchy UA sniffing...?

**Comment by quantum5** [comment]
Agree to add this feature but would require database change.

**Comment by Xyene** [comment]
![](https://sc-cdn.scaleengine.net/i/cda4c070609728786438fbf1605f37a1.png)

Implemented.
