### ISSUE TITLE
Use camo for proxying user content

### ISSUE THREAD

**Issue by Xyene** [DMOJ/site#259]

**Comment by quantum5** [comment]
Supersedes #145

**Comment by Xyene** [comment]
The current implementation uses sionide21/camo-client for integration. There are two small issues with this implementation:

* dmoj.ml content is proxied, though it shouldn't be
* // links do not get proxied

To address these issues, I've forked the project to DMOJ/camo-client.

**Comment by quantum5** [comment]
@Xyene do you agree with my assessment of putting camo under cloudflare? Camo doesn't cache apparently.

**Comment by quantum5** [comment]
Now for PDF support, we must use `<object>` tags, because using camo on an `<iframe>` is highly sketchy.

**Comment by Xyene** [comment]
Documentation for this change appears to be completed.

**Comment by quantum5** [comment]
Should we proxy organization pages? [Example](https://dmoj.ca/organization/THSS) #268 will break that page. On a second thought, that may be a good thing.
