### ISSUE TITLE
404 for contest problems if not in contest

### ISSUE THREAD

**Issue by Xyene** [DMOJ/site#262]
This can be confusing, especially for the comment stream. Instead of a 404 problem not found page, we should notify the user that they are trying to view a problem that is part of contest X, and that they can join contest X at [link].

**Comment by FatalEagle** [comment]
Users may guess contest codes, and that's bad.

**Comment by Xyene** [comment]
....because "contestxp1" gives away so much info.

**Comment by FatalEagle** [comment]
Well, although the current convention is to use that, there have been contests where codes are like "segments".

**Comment by Xyene** [comment]
Those codes are already visible in the comment links as it is... hence this would be strictly an improvement.

**Comment by FatalEagle** [comment]
Unless there are no comments :|
Something should be done about comments too (for virtual contest). Since a help request titled "why is my DP not working" is pretty sketchy to display.

**Comment by quantum5** [comment]
Where do you get these links now that they don't show up in comment stream? As far as the user is concerned, the problems *do not exist*.
