### ISSUE TITLE
Session hijacking threat via comment editing

### ISSUE THREAD

**Issue by Xyene** [DMOJ/site#266]
The Pagedown comment editor requests images as they appear in the Markdown text - that is, unsecured images are loaded. This poses a session hijacking threat to admins editing user content. Though fairly contrived, we should remove this vulnerability by coercing Pagedown to generate proxied links.

**Comment by quantum5** [comment]
DMOJ/dmoj-pagedown#1 will provide the solution to this issue.

**Comment by quantum5** [comment]
Anyways, #444 is the way to go if this is an issue.

**Comment by quantum5** [comment]
Although this attack is actually moot, since CSP prevents the loading of anything untrusted.
