### ISSUE TITLE
Change sum_time to max_time

### ISSUE THREAD

**Issue by FatalEagle** [DMOJ/site#269]
https://blog.codechef.com/2015/09/09/the-new-execution-time-for-your-submission/

Was there a reason why we used sum of time in the first place?

**Comment by quantum5** [comment]
`sum_time` more correctly shows the time the program takes to run. If your program is equally slow on small and large datasets, then your program is worse than it being fast on the small cases.

**Comment by FatalEagle** [comment]
This is true, but we inherently only care about the worst case (otherwise we would set the time limit for sum of times). Also, this is asymmetrical from the fact where we use max of memory usage. If that were to be changed to sum, some problems might end up having several dozen gigabytes of usage...

**Comment by quantum5** [comment]
You may inherently only care about worse case when solving the problem, but you don't rank programs by the time it takes to do the worst case.

**Comment by FatalEagle** [comment]
Yet we tie-break identical times by worst case memory usage. Also, sum of times doesn't really accurately represent anything - you could rank programs by time complexity if you used max time, but a program that performed strictly N^2 operations could be ranked worse than a program that performs a constant (but large) number of operations on the order of NlogN, where N is the maximum value possible no matter the input. And the only thing that decides which is ranked better is the number of test cases the author decides to supply. An example that comes to mind is precomputing primes, or factorials and inverses.

More importantly, wrong answer solutions in batches will have wildly different times depending on if they failed the first case of the 30th of the batch, affecting the rankings.

**Comment by quantum5** [comment]
Note: we do not tie break by worst case memory usage.

**Comment by FatalEagle** [comment]
Wow, that's incredibly sketchy. Anyway, sum is a pretty sketchy function with low meaningfulness behind it. We could reward strict adherence of time complexity to input size by using sum of fifth powers of times, but the numbers would get pretty ridiculous.

**Comment by quantum5** [comment]
I believe you are mistaken, the point of programming is fastest code, not most algorithmically "better" for some definition of better. For example, a sorting algorithm is useless if its average case is 50 times worse than quicksort even if it is O(n log n).

**Comment by FatalEagle** [comment]
It is true that writing the fastest code is all that matters to get AC. Using *mmintrin.h is an increasingly popular method to solve problems.

But ranking by any metric (including fastest code) is a futile endeavor anyway since we use different judges. However, the difference is larger if you add use the sum of times. Error amplification scales on the order of the number of test cases.

Still, the fact that time on short-circuited problems can be wildly incorrect is still relevant. Not to mention even if TLEs occur the time is still displayed [(see here)](https://dmoj.ca/submission/109323).

P.S. Quicksort really isn't that bad; you can fix the degenerate behavior by just randomly permuting the array beforehand. The chance of bad performance is low enough to neglect.

**Comment by quantum5** [comment]
This issue has existed for the length of two pregnancies, and to change such mechanic now would be foolish.
