### ISSUE TITLE
lxml + math

### ISSUE THREAD

**Issue by Xyene** [DMOJ/site#270]
Now that we have `lxml` (which is faster than `HTMLParser`) as a side effect of #259, we can update math to use it and decrease load times.

**Comment by quantum5** [comment]
And it saves us the trouble of #264. Also `lxml` is a C extension and it has xpath instead of sax-style. Finally why do you have to steal my ticket?

**Comment by Xyene** [comment]
[It happens.](https://github.com/DMOJ/judge/commit/b086a9d14f4e8d320b1ca43b4cc9863774066c35)

**Comment by quantum5** [comment]
This appears to work. Will be closed if no regressions are found for a while.

**Comment by quantum5** [comment]
It's been half a month without any complaints.
