### ISSUE TITLE
Blog posts should be rel="nofollow"

### ISSUE THREAD

**Issue by Xyene** [DMOJ/site#271]
We have such things going on as linking Facebook profiles, Google Drive and more, simply because blog posts are becoming more and more user-generated content.

/cc @quantum5 @FatalEagle

**Comment by FatalEagle** [comment]
Wait, which blog linkes Facebook profiles?

**Comment by Xyene** [comment]
@FatalEagle <https://dmoj.ca/post/54-gfss-spring-open-solutions-are-out>

**Comment by quantum5** [comment]
We can make a `|nofollowexternal` filter with `lxml` thanks to #274.

**Comment by quantum5** [comment]
`|nofollowexternal` filter should have a domain white list that does not get `rel="nofollow"`.

**Comment by quantum5** [comment]
Implemented. Put whitelisted domain names in `NOFOLLOW_EXCLUDED` settings, preferably as a `set`.
