### ISSUE TITLE
Previews for "trusted site" links

### ISSUE THREAD

**Issue by Xyene** [DMOJ/site#273]
@FatalEagle recommended the idea, and it works pretty well in practice:

![](https://sc-cdn.scaleengine.net/i/ad82c245567631042c791ee069174a5d.png)

https://dmoj.ca/problem/tree1

**Comment by quantum5** [comment]
Seems legit. Either ANOTHER parser or something else.

**Comment by quantum5** [comment]
@Xyene your pet rogue feature prevents mathjax and pagedown from loading while it loads the page.

**Comment by quantum5** [comment]
I am starting to think this is a rather poor idea, since it's a very domain specific customization, which should be done in the problem statement if *it's actually necessary*, which it is not. You do not know the user's workflow, and shoving this preview in their face is not helping.
