### ISSUE TITLE
Merging inline styles into style.sass

### ISSUE THREAD

**Issue by quantum5** [DMOJ/site#280]
We have so many massive inline style blocks that are downloaded on every page load, without even being compacted.

**Comment by Xyene** [comment]
@quantum5 you broke the problem pages!

![](https://sc-cdn.scaleengine.net/i/c058e14569134e57e1020a0fe02c3ebd.png)

**Comment by quantum5** [comment]
Did not. Simply forgot to reload statics.

**Comment by Xyene** [comment]
#93 addresses the same issue, so I'm closing this one so we don't have open duplicates.
