### ISSUE TITLE
Mobile is (still?) broken

### ISSUE THREAD

**Issue by FatalEagle** [DMOJ/site#286]
![image](https://cloud.githubusercontent.com/assets/3643458/10126113/f88f963c-6558-11e5-8ece-453070c5d12e.png)

**Comment by quantum5** [comment]
Most of the time the underlying issue is in the problem statement, though I can't deny that a useful set of default image styles could reduce the incidence of this problem.

**Comment by FatalEagle** [comment]
![image](https://cloud.githubusercontent.com/assets/3643458/10126134/82814a84-6559-11e5-8469-42d0bc904a92.png)
Still broken on image-less pages.

**Comment by Xyene** [comment]
This has been fixed sometime during a refactor or other; the info-float appears on top of the statement if the width of the page becomes <= 480px, so this shouldn't happen anymore.
