### ISSUE TITLE
Should PDFs be included in robots.txt?

### ISSUE THREAD

**Issue by Xyene** [DMOJ/site#287]

**Comment by Xyene** [comment]
...no.

**Comment by quantum5** [comment]
By no, do you mean they should be allowed in `robots.txt` or disallowed? This entire thing is unclear.

**Comment by Xyene** [comment]
No, they should not be allowed.

**Comment by quantum5** [comment]
If you want them excluded from search engine results, you need to put them as `Disallow:`  in `robots.txt`.
