### ISSUE TITLE
Edit button for all model views

### ISSUE THREAD

**Issue by Xyene** [DMOJ/site#290]
These include (but may not limited to):
- judges
- languages
- blog posts

It's just too painful to have to go to admin to look them up...

**Comment by quantum5** [comment]
Supersedes #260.

**Comment by quantum5** [comment]
Organization pages are not linked to admin yet.

**Comment by quantum5** [comment]
What else is there to do? I doubt we'd put a link to edit the navbar on the navbar itself, since that would be silly...

But, perhaps we can link the contest participation admin, since that's one annoying search.

**Comment by quantum5** [comment]
I don't think there is any more stuff to link to the admin page.
