### ISSUE TITLE
font-size differences

### ISSUE THREAD

**Issue by Xyene** [DMOJ/site#293]
Some places use 14px (like problems), others use 13px (like blog posts). Once you notice this you can never un-notice it.

**Comment by Xyene** [comment]
Refs #254.

**Comment by quantum5** [comment]
WHY DID YOU MAKE ME NOTICE IT THEN?

**Comment by Xyene** [comment]
I don't hate you, but...

[![](https://imgs.xkcd.com/comics/kerning.png)](https://xkcd.com/1015/)

**Comment by quantum5** [comment]
I have enough power to be able to recognize bad kerning yet remain completely unaffected by it. Apparently that's not enough for `13px` and `14px`.

**Comment by Xyene** [comment]
This has been fixed (see also #431).
