### ISSUE TITLE
Blog post comments should have math enabled

### ISSUE THREAD

**Issue by Xyene** [DMOJ/site#294]

**Comment by quantum5** [comment]
Translates to home page should have math enabled.

**Comment by Xyene** [comment]
Not necessarily, since comments aren't loaded on the home page.

**Comment by quantum5** [comment]
Well I don't think anyone can refuse to allow math on blog posts if we allow it on comments.

**Comment by Xyene** [comment]
Allowing it on blog posts would mean allowing it on main page, which is horrible for page load speeds.

**Comment by quantum5** [comment]
"Translates to home page should have math enabled."  as I have said, but you will find the temptation difficult to resist.

**Comment by Xyene** [comment]
Not sure when the change was made, but they do.

**Comment by quantum5** [comment]
More like since MathJax may not be enabled on problem pages, problem comments may fail to display math. This forces all comments to run through mathoid.
