### ISSUE TITLE
Custom ranks

### ISSUE THREAD

**Issue by Xyene** [DMOJ/site#296]
We could generate the user css on the fly, as it is being compressed into the main stylesheet. This would allow user-defined ranks like `Head Data Slave` without having to mess with `models.py`.

**Comment by WallE256** [comment]
Possible approach as said by @Xyene on Slack, written here for future reference:

> **xyene:**	there's a ticket for more ranks
anyone who wants to take a crack at it can
basically you'll need a new rank model that defines color/name, and a migration to add it + change that field for user profiles
migration will have to be two-step
i.e. create "new_rank" column, convert all ranks to `new_rank`, delete the old `rank` column, and rename `new_rank` to `rank` or w/e it is rn
then you need to create a view that autogenerates some css

**Comment by quantum5** [comment]
A view that autogenerates some CSS is a pretty poor idea. It should be generated and inlined into the main compressed css file in `base.jade`.

**Comment by Xyene** [comment]
Superseded by ranking colors. The builtin ranks will someday need to be removed too, but that's out of the scope of this ticket.
