### ISSUE TITLE
Multi-language support for problem statements

### ISSUE THREAD

**Issue by FatalEagle** [DMOJ/site#299]
Language as in natural language, for example if we added Chinese problem statements we could get hundreds more users, almost instantly!

**Comment by Xyene** [comment]
On the admin side, we could make the problem statement editor tabbed by language.

**Comment by quantum5** [comment]
On the database side, IDK where to store languages.

**Comment by quantum5** [comment]
We can define a `ProblemTranslation` model, that contains:

* `problem`: `ForeignKey` to `Problem`
* `language`: `CharField(max_length=7)` for language code
* `name`: translated problem name
* `description`: problem description

We will need to somehow `LEFT OUTER JOIN` onto this table, based on `language`, when displaying problem list. We can then display information in this model, instead of those in the `Problem` model, should the language match the current one. Those in the `Problem` model would be assumed to be in the language marked by the global setting `LANGUAGE_CODE`.

**Comment by quantum5** [comment]
Finally worked out the `LEFT OUTER JOIN` magic for Django 1.9. Here is the glorious Django-gut-poking code:

```python
from copy import copy
from django.db.models.sql.constants import LOUTER
from django.db.models.sql.datastructures import Join, BaseTable

language_field = ProblemTranslation._meta.get_field('language')

def restrictions(where_class, alias, related_alias):
    cond = where_class()
    cond.add(language_field.get_lookup('exact')(language_field.get_col(alias), DESIRED_LANGUAGE), 'AND')
    return cond

problem_field = copy(ProblemI18N._meta.get_field('problem').rel)
problem_field.get_extra_restriction = restrictions

queryset = Problem.objects.extra(select={'i18n_name': '%s.name' % ProblemTranslation._meta.db_table})
queryset.query.join(BaseTable(Problem._meta.db_table, None))
queryset.query.join(Join(ProblemTranslation._meta.db_table, Problem._meta.db_table, None, LOUTER, problem_field, True))
```

`queryset` now contain models with the `i18n_name` attribute, which is either the translated name if available, or `None`.

**Comment by quantum5** [comment]
If we actually bothered with #62, we would have realized that `prefetch_related` and [`Prefetch` objects](https://docs.djangoproject.com/en/1.9/ref/models/querysets/#prefetch-objects) would basically solve this, instead of messing with queries, though I admit the hack is faster and presents a better interface.

**Comment by quantum5** [comment]
Here is an improvement to the raw SQL version that doesn't use future deprecation, and can be more transparently replaced with the `prefetch_related` alternative:

```python
from copy import copy
from django.db.models.sql.constants import LOUTER
from django.db.models.sql.datastructures import Join
from django.db.models.expressions import RawSQL, F
from django.db.models.functions import Coalesce


language_field = ProblemTranslation._meta.get_field('language')

def restrictions(where_class, alias, related_alias):
    cond = where_class()
    cond.add(language_field.get_lookup('exact')(language_field.get_col(alias), DESIRED_LANGUAGE), 'AND')
    return cond

problem_field = copy(ProblemI18N._meta.get_field('problem').rel)
problem_field.get_extra_restriction = restrictions

queryset = Problem.objects.annotate(i18n_name=Coalesce(RawSQL('%s.name' % ProblemTranslation._meta.db_table, ()), F('name')))
queryset.query.get_initial_alias()
queryset.query.join(Join(ProblemTranslation._meta.db_table, Problem._meta.db_table, None, LOUTER, problem_field, True))
```

This makes `i18n_name` fallback to the normal `name` if unavailable, permitting it to be `@property` if we ever have to switch to the `prefetch_related` alternative.

**Comment by quantum5** [comment]
Here is the `prefetch_related` alternative, assuming `ProblemTranslation`'s `ForeignKey` to `Problem` has `related_name='translations'`:

```python
class ProblemTranslation(models.Model):
    # ...

    @property
    def i18n_name(self):
        queryset = self.translations.all()
        if not queryset:
            return self.name
        return queryset[0].name

# Query like:
from django.db.models.query import Prefetch
queryset = Problem.objects.prefetch_related(Prefetch('translations', queryset=ProblemTranslation.objects.filter(language=DESIRED_LANGUAGE)))
```

As one can perceive, this is a drop-in replacement.

**Comment by quantum5** [comment]
We can simply use Django's inlines to define these translations in the admin, may be tabbing them somehow.

**Comment by quantum5** [comment]
This is pretty much done.
