### ISSUE TITLE
Cannot add more than three specific language constraints

### ISSUE THREAD

**Issue by mrthefakeperson** [DMOJ/site#315]
There is no available list of languages to choose from in the Language Limits section of the admin page when the "add another Language Limit" option is used.

**Comment by quantum5** [comment]
Bug with `django-select2` that might be fixed with #308.

Workaround: Save problem and three extra limits will appear.

**Comment by quantum5** [comment]
#308 did not fix.

**Comment by quantum5** [comment]
It is time to rely on self and fix other people's bugs!
