### ISSUE TITLE
Termination of Django 1.7 support

### ISSUE THREAD

**Issue by quantum5** [DMOJ/site#318]
Every time we run a `manage.py` command, we receive this warning:

```
WARNINGS:
?: (1_8.W001) The standalone TEMPLATE_* settings were deprecated in Django 1.8 and the TEMPLATES dictionary takes precedence. You must put the values of the following settings into your default TEMPLATES dict: TEMPLATE_DIRS, TEMPLATE_CONTEXT_PROCESSORS, TEMPLATE_LOADERS.
```

If we terminate Django 1.7 support, this will no longer be a problem. It's likely that Django 1.7 doesn't even run the judge properly any more.

**Comment by WallE256** [comment]
As long as we will add `requirements.txt`, the future will be safe.

**Comment by quantum5** [comment]
Fixed the warning. If anything else, please reopen.
