### ISSUE TITLE
RFC: Django's quick search

### ISSUE THREAD

**Issue by Xyene** [DMOJ/site#319]
Right now it searches users, which isn't particularly useful. Perhaps it should be edited to search problems (a much more common task), or removed altogether.

**Comment by quantum5** [comment]
The search belongs to `django-suit` I would believe

**Comment by Xyene** [comment]
It does.

**Comment by Xyene** [comment]
It does.

**Comment by quantum5** [comment]
[Relevant `django-suit` documentation](http://django-suit.readthedocs.org/en/latest/configuration.html#search-url):

>We have big plans for this field in the future, by making it global search field. However right now this field works only as a search redirect to any other urls of your admin:

```python
SUIT_CONFIG = {
    'SEARCH_URL': '/admin/user',

    # Parameter also accepts url name
    'SEARCH_URL': 'admin:auth_user_changelist',

    # Set to empty string if you want to hide search from menu
    'SEARCH_URL': ''
}
```

Unless we make our own search view, we will only be able to search one type of object.

**Comment by quantum5** [comment]
There is nothing left to do. Reopen when `django-suit` finally implements the promised feature.
