### ISSUE TITLE
Django problem admin unbearably slow to load

### ISSUE THREAD

**Issue by Xyene** [DMOJ/site#320]
Does `select2` *really* need to be loaded 10 times?

![](https://sc-cdn.scaleengine.net/i/913cde0e9ce88add9710c4a89d3a7dc4.png)

Along with two JQueries? Just the page HTML itself takes 2.5s to render.

15 seconds for a full load is ridiculous, no matter what the cause. And so is a 1.5mb page.

**Comment by Xyene** [comment]
Further data:

![](https://sc-cdn.scaleengine.net/i/2f89ad08f9b660b911c3e1d8d380c74f.png)

Essentially, if the time it takes to generate the page is taken down from ~3 seconds and the `select2` redundancy is removed, problem admin should become much more usable.

**Comment by quantum5** [comment]
#308 should be done first. It might fix this total stupidity.

**Comment by quantum5** [comment]
Fixed with #326, #333, #308.
