### ISSUE TITLE
Admin-initiated rejudge should not count towards user submission limit

### ISSUE THREAD

**Issue by Xyene** [DMOJ/site#329]
As it stands, it prevents users from submitting problems during systesting.

**Comment by quantum5** [comment]
Propose a valid method of distinguishing it.

**Comment by Xyene** [comment]
Perhaps another set of values that display the same as QU/G, but identify that they're admin-initiated. Or perhaps a `rejudging` field in `Submission`. I can't think of a nice, clean way to do this, but it needs to be done.

**Comment by quantum5** [comment]
If we do this, we must need to store this in the db.

**Comment by quantum5** [comment]
Approve change.

**Comment by Xyene** [comment]
If we ever switch back to the old bridge (#399), we'll have to make that bridge set the rejudge flags as well.

**Comment by quantum5** [comment]
Is there a reason to set `is_being_rejudged` to `False` other than the fact you want to be correct?

**Comment by Xyene** [comment]
Not really, except for correctness. Granted, it could be called `was_rejudged`, but it doesn't matter too much either way.

**Comment by quantum5** [comment]
Is this done?

**Comment by Xyene** [comment]
[Looks like it](https://github.com/DMOJ/site/blob/a0f8ea627cd396513b8c8cd31edc3ab8ed375429/judge/views/problem.py#L294), except...

> If we ever switch back to the old bridge (#399), we'll have to make that bridge set the rejudge flags as well.

The old bridge does not set the proper flags anymore.

**Comment by quantum5** [comment]
This merely turns `is_being_rejudged` into `was_rejudged`.

**Comment by quantum5** [comment]
I propose just rename `is_being_rejudged` to `was_rejudged`, since the `was_rejudged` information probably more useful anyway.

**Comment by Xyene** [comment]
Sounds fine.

**Comment by quantum5** [comment]
`is_being_rejudged` is now renamed to `was_rejudged`.
