### ISSUE TITLE
Internationalization support

### ISSUE THREAD

**Issue by quantum5** [DMOJ/site#337]
Our code currently hard codes all strings as English. Django offers [translation](https://docs.djangoproject.com/en/1.9/topics/i18n/translation/) support, which uses a form of `gettext`, allowing any string to be translated into another language.

**Comment by WallE256** [comment]
This is kind of a must do before January DMOPC.

**Comment by quantum5** [comment]
An example is available in [`edit_profile.jade`](https://github.com/DMOJ/site/blob/master/templates/user/edit_profile.jade).

Template style:

* Jade files are indented with four spaces.
* In Jade, use `- trans "<string>"` if original string is on its own line, otherwise, use `{% trans %}`.

/cc @WallE256

**Comment by WallE256** [comment]
Internationalization of navbar might be required. Also, page titles.

**Comment by quantum5** [comment]
Next steps:

* Find strings missed in `.jade` files.
* Mark the UI strings that are in `.py` files.

**Comment by Xyene** [comment]
[Status codes are not staged for translation.](https://github.com/DMOJ/site/blob/4790a9c18ffc22730d6061792860da572ac9cac0/judge/models.py#L321)

**Comment by quantum5** [comment]
This issue, like #205, will probably stay open for a long, long time.

**Comment by quantum5** [comment]
More things to note: we also need to correctly declare `lang` attributes. Currently, it is defined globally as `en`. This is bad.

**Comment by Xyene** [comment]
Closing since we've had this for a long time.
