### ISSUE TITLE
Copy sample input (and all text formatted with code)

### ISSUE THREAD

**Issue by FatalEagle** [DMOJ/site#34]
Users can then click a button to copy the sample input instead of scrolling and dragging (if it's long).

**Comment by Xyene** [comment]
Could use JS to insert a hooked link into the DOM above any `pre.code code` group.

**Comment by quantum5** [comment]
Only doable with JS on IE. The rest you need to use flash.

There is https://github.com/zeroclipboard/zeroclipboard to do this.

**Comment by Xyene** [comment]
"Copy" is a bit of a misnomer - the intended action is more like "Select", since users might not enjoy the invasion of their clipboard, and simply selecting an element is easy with JS.

**Comment by quantum5** [comment]
When you press a button called copy, the user sort of expects it to be copied. But anyways, if you want to have a select all button, by all means use that JS implementation you suggested.

**Comment by quantum5** [comment]
```jade
- load clippy

block media
    script(type='text/javascript')
        $(function () {
            var clippy = $('#clippy_clippy_placeholder').html();
            $('pre.code').each(function (id, block) {
                $(clippy.replace(/clippy_placeholder/g, 'clippy_' + id)).insertBefore($(block));
                $(block).attr('id', 'clippy_' + id);
            });
        });

block description
    - clippy "clippy_placeholder"
```

Using django-clippy, that's pretty easy. HOWEVER, it has z-order problems: it only covers `box-shadow` and `background: rgba(...)` elements. We seem to use those two a lot: *cough* navbar *cough.

**Comment by quantum5** [comment]
I think may be we should just implement a select all button. `Ctrl-C` is not that bad.

**Comment by Xyene** [comment]
![](https://sc-cdn.scaleengine.net/i/acfd5f191cfcac8f398cf14d4b4a84f9.png)

#205

**Comment by Xyene** [comment]
3 options for the zerocopy-based copy button above:

* add necessary HTML directly in the pagedown converter
* run a post-processing HTML parsing step in Python to add the necessary HTML
* add the necessary HTML with JS

Thoughts?

**Comment by quantum5** [comment]
Since it will not work without JS at all, we might as well use JS to make it work, so nothing useless shows up without JS.

**Comment by quantum5** [comment]
Finally it works.

**Comment by Xyene** [comment]
Selector doesn't select syntax highlighted blocks.

**Comment by Xyene** [comment]
Removed `.code` restriction from `pre` blocks.
