### ISSUE TITLE
Use django.shortcuts where possible

### ISSUE THREAD

**Issue by Xyene** [DMOJ/site#340]
[`django.shortcuts`](https://docs.djangoproject.com/en/1.9/topics/http/shortcuts/) has a couple of neat functions like `get_object_or_404`, which would allow us to replace a lot of try/except blocks.

**Comment by quantum5** [comment]
There are not *too* useful when dealing with class-based views, but are still nice.

**Comment by Xyene** [comment]
Tickets like these are far too broad to ever hope to meaningfully close. We've certainly been using the aforementioned `get_object_or_404`, though.
