### ISSUE TITLE
$ in urlconf

### ISSUE THREAD

**Issue by quantum5** [DMOJ/site#344]
Many single page views in `urlconf` doesn't have a `$` to terminate the regex.

**Comment by Xyene** [comment]
Also on a similar topic, it's ridiculous that <https://dmoj.ca/problem/aplusb> is valid but <https://dmoj.ca/problem/aplusb/>, especially since browser autocomplete favours the latter.

**Comment by quantum5** [comment]
Ahh, about that. Django seems to frown upon the lack of the slash, and would normally auto-redirect to the version with the slash.

**Comment by quantum5** [comment]
I think it is!
