### ISSUE TITLE
PyPy 4.0.1

### ISSUE THREAD

**Issue by quantum5** [DMOJ/site#346]
The latest `PyPy` has been released for a while now.

Features can be found in the [PyPy 4.0.0 release notes](http://doc.pypy.org/en/latest/release-4.0.0.html) and that of [PyPy 4.0.1](http://doc.pypy.org/en/latest/release-4.0.1.html).

**Comment by quantum5** [comment]
Apparently this may not be a good idea:

![image](https://cloud.githubusercontent.com/assets/461885/11789362/f95ae448-a263-11e5-8a10-f81b2e3f8400.png)

**Comment by Xyene** [comment]
We recently switched back to CPython and enjoying increased performance, and PyPy 4 is outdated now regardless.
