### ISSUE TITLE
Pagination of User and Problem Pages

### ISSUE THREAD

**Issue by quantum5** [DMOJ/site#35]
As the size of these pages continue to grow, sooner or later they will impossible to send as one page. I suggest we start to encode various sorting options in the URL in anticipation of pagination, and may be experiment pagination on the users page.

**Comment by Xyene** [comment]
I am not a fan of the idea of pagination in general, rather we could have infinite scrolling, loading the next segment as needed. This goes even more so for the submissions page, where infinite scrolling would work very nice with the info-float we already have.

**Comment by quantum5** [comment]
[![](http://imgs.xkcd.com/comics/infinite_scrolling.png)](https://xkcd.com/1309/ "Maybe we should give up on the whole idea of a "back" button. "Show me that thing I was looking at a moment ago" might just be too complicated an idea for the modern web.")

**Comment by Xyene** [comment]
Could've sworn you'd use that comic, but the point still stands. Its easier for some users to Ctrl+F to find a problem by name, which is very convenient when not utilising the advanced search. Pagination would ruin this.

**Comment by quantum5** [comment]
Infinite scrolling doesn't help Ctrl-F if the relevant parts are not loaded.

**Comment by Xyene** [comment]
As I added right after posting my comment,

> Not that infinite scrolling is a solution to the Ctrl+F problem, but it does make it a bit more manageable.

**Comment by quantum5** [comment]
GitHub doesn't automagically update comments when edited.

**Comment by FatalEagle** [comment]
Infinite scrolling is terrible, I like my content organized in an random access way.

**Comment by quantum5** [comment]
Something needs to be done soon: the users page is already 183.22 KB and the problems page is 131.63 KB.

**Comment by quantum5** [comment]
Is highly necessary, with 1467 users, `356KB` of users list, taking anywhere around a full second to three to render, over half of which are basically inactive. I really think we should split into size 100 pages. If one of you truly insists, I can probably do 200.

/cc @Xyene @FatalEagle

**Comment by FatalEagle** [comment]
100 sounds good, it would give points a bit more meaning since you can call yourself "page 1".

**Comment by Xyene** [comment]
If pagination is added (and at this point it should be, for the user table at least &mdash; not sure about the problem page), it would necessitate the implementation of #48, or the removal of sorting altogether (though it makes sense to be able to sort by problems/points/rating).

**Comment by quantum5** [comment]
Like it or not, the problem page will have to be paginated at some point. Currently it takes 1.2 seconds for MySQL perform the fancy query that it needs (like check if the user has solved the problem in a contest before, since some people were too lazy to publish the problem, and the user count which is rather unnecessary). We might be able to 1. use a different approach for certain things once we paginate, and 2. pray that the query will be faster if we limit it. Nevertheless we do not want to send a massive table to torture browsers.

**Comment by Xyene** [comment]
Problems table is ready for pagination after search redesign in #431.

**Comment by Xyene** [comment]
This has been mostly implemented for problems. One outstanding issue:

* We must start encoding table sort states into the URL, since as we stand now it's impossible to meaningfully sort by anything.

**Comment by Xyene** [comment]
This has been implemented successfully, and works well.
