### ISSUE TITLE
Problem should link to solution if exists

### ISSUE THREAD

**Issue by quantum5** [DMOJ/site#352]
A solution is useless if the user is not aware of it.

/cc @Xyene @FatalEagle

**Comment by Xyene** [comment]
We have two options for the UI:

* a link below My/Best/All submissions
* a tab
    * in the case of the tab we would have to create a tab for the PDF link as well

Thoughts?

**Comment by quantum5** [comment]
A tab would imply the solutions page have to be styled similarly.

**Comment by Xyene** [comment]
Done!
