### ISSUE TITLE
Allow user to store JS to customize homepage (and maybe other pages too)

### ISSUE THREAD

**Issue by FatalEagle** [DMOJ/site#355]
For example, if the user wanted to display a picture on their home page, or if they want to display recent AC submissions when they load dmoj, or if they want to ignore showing AC cases on submit , etc.

Not sure how useful in practice this will be, but at least it will set us apart from other OJs.

**Comment by quantum5** [comment]
Wikipedia has this feature.

**Comment by Xyene** [comment]
This does sound pretty useful, not just for users but for us too: it fits really well with our way of developing new features.

**Comment by quantum5** [comment]
Well I say we have a per-user JS. The user chooses which pages it acts on, after all, it's just a bunch of regexes that I am sure even the worst of our users can understand and wield.

**Comment by Xyene** [comment]
Perhaps per-user JS**es**? So that they could specify different JS scripts for different pages.

**Comment by quantum5** [comment]
Why bother? Your JS can simple decide what pages it should act on, and we load it for every page.

**Comment by Xyene** [comment]
I'd expect user scripts to be copy/pasted around by users, and having a more organized approach would help with this. But regardless, it wouldn't be hard with just one script either.

**Comment by Xyene** [comment]
We should start off with a couple of scripts.

Possibilities:
* non-sticky header: `$("#navigation").css({position:"fixed"})`

**Comment by quantum5** [comment]
But, `#navigation` is `position: fixed` by already?

**Comment by Xyene** [comment]
I don't know what you're talking about :tongue:

**Comment by FatalEagle** [comment]
![image](https://cloud.githubusercontent.com/assets/3643458/11911646/8e421b7e-a5ea-11e5-8efc-7fe4aec85ea8.png)
Gmail gotchu bro

**Comment by Xyene** [comment]
Shh

**Comment by Xyene** [comment]
This is implemented in the backend. The question now is whether user scripts should be render-blocking or not.

**Comment by Xyene** [comment]
I've implemented this, and it seems to work fine.

![](https://sc-cdn.scaleengine.net/i/7e7e5a146b35f489f873f35053274c37.png)

Reopen if there are any outstanding issues.

**Comment by WallE256** [comment]
@Xyene If you add a user script and then you want to remove it (leave that space empty), you can't...

**Comment by Xyene** [comment]
Fixed, had forgotten blank=True.
