### ISSUE TITLE
RFC: Removal of rejudge confirmation

### ISSUE THREAD

**Issue by Xyene** [DMOJ/site#356]
/cc @quantum5 @FatalEagle

**Comment by quantum5** [comment]
It was @Xyene and @FatalEagle who complained about my accidental clicks on the button that forced the feature to be added.

**Comment by quantum5** [comment]
Suggested compromise: Ctrl+Click to avoid the confirmation?

**Comment by Xyene** [comment]
Sounds good.

**Comment by quantum5** [comment]
`e.ctrlKey` can take care of this.
