### ISSUE TITLE
Jade usage

### ISSUE THREAD

**Issue by quantum5** [DMOJ/site#364]
We use `jade` in the worst way possible in many places.

Two features comes to mind:
- Jade supports the operator `:` which allows the only child element to be placed on the same line as the parent. This removes the need to add an additional layer of indentation. Example:
  - Before:

``` jade
.source-wrap
    table
        tr
            td.source-ln
                div
                    for line in raw_source|split
                        a(href='#line-{{ forloop.counter }}', name='line-{{ forloop.counter }}')
                            pre #{forloop.counter}
            td.source-code #{highlighted_source}
```
- 
  - After:

``` jade
.source-wrap: table: tr
    td.source-ln: div
        for line in raw_source|split
            a(href='#line-{{ forloop.counter }}', name='line-{{ forloop.counter }}')
                pre #{forloop.counter}
    td.source-code #{highlighted_source}
```
- Jade supports inline tags with `#[<jade tag>]`.

**Comment by Xyene** [comment]
Read: "things learned while implementing i18n"

**Comment by Xyene** [comment]
Most new templates make use of these things, and old templates are occasionally being changed to do so too. That said, this is done without referencing this ticket, so I don't see a point in keeping it open.
