### ISSUE TITLE
Rating circles are boxes on Dolphin Browser 10.0.0

### ISSUE THREAD

**Issue by Xyene** [DMOJ/site#37]
A popular browser for Android devices. They look fine as boxes, but consistency is nice.

**Comment by quantum5** [comment]
Circles are hard when `border-radius` doesn't work. The alternatives are worse: `U+25EF LARGE CIRCLE` doesn't clip the inner span, and inline SVG is even less supported. See yesterday's The Old New Thing article for the trouble this has caused.

http://blogs.msdn.com/b/oldnewthing/archive/2015/03/24/10602182.aspx

**Comment by Xyene** [comment]
`border-radius` certainly is supported on Dolphin.

**Comment by quantum5** [comment]
I heard `border-radius` with percents is a problem with certain browsers. Let me try something.

**Comment by quantum5** [comment]
@Xyene can you confirm whether a0c08195d1c18e60a328d7a054f6c9e21b4de1e1 fixed?

**Comment by Xyene** [comment]
My phone is out of battery!

**Comment by quantum5** [comment]
Don't tell me you are STILL on a toilet and can't plug it in.

**Comment by Xyene** [comment]
shh

**Comment by Xyene** [comment]
Yes, it appears to be fixed.
