### ISSUE TITLE
Hidden Problems

### ISSUE THREAD

**Issue by cheesycake** [DMOJ/site#372]
Solving hidden problems increases problem solved count on user page.

Before solving fast bit counting:
![image](https://scontent-yyz1-1.xx.fbcdn.net/hphotos-xpa1/v/t35.0-12/12494224_1116977325001238_1440618226_o.jpg?oh=27d56eeb8e980cf645b83dcb0ca8ff41&oe=568E9D9F)

After:
![image](https://cloud.githubusercontent.com/assets/13436730/12135142/79295706-b405-11e5-8ca9-dd7612762a45.png)

**Comment by quantum5** [comment]
Fixed.
