### ISSUE TITLE
Contest labels

### ISSUE THREAD

**Issue by Xyene** [DMOJ/site#377]
Would be more versatile than our current `external` field, and we could have nice labels like `seasonal`, `external`, `unusual` (assembly contests?). Styling could be done similarly to Github labels.

But really, we need to get rid of the `external` field: it relies on /about#external-contests existing, and is hardly customizable.

**Comment by Xyene** [comment]
I propose a `ContestLabel` object containing name, color, and description. We can then generate a tag listing and links to contest label descriptions.

**Comment by quantum5** [comment]
We should just use GitHub's colours:

```
#e11d21
#eb6420
#fbca04
#009800
#006b75
#207de5
#0052cc
#5319e7
#f7c6c7
#fad8c7
#fef2c0
#bfe5bf
#bfdadc
#c7def8
#bfd4f2
#d4c5f9
```

**Comment by Xyene** [comment]
Github allows you to use your own hex as well:

![](https://sc-cdn.scaleengine.net/i/3f6340de33d0f5c7fb8aca73d3a2e7b01.png)

**Comment by quantum5** [comment]
Wait a second, what about `clist.by`? We filter `is_external=False` in the API.

**Comment by Xyene** [comment]
Notice that they don't actually use the API.

**Comment by quantum5** [comment]
We have yet to remove the `is_external` field.

**Comment by quantum5** [comment]
This is finished.
