### ISSUE TITLE
Best solutions for non-contest problem in contest

### ISSUE THREAD

**Issue by Xyene** [DMOJ/site#386]
<https://dmoj.ca/contest/vmss7wc16c3/rank/helloworld/> should give a 404.

**Comment by Xyene** [comment]
Same for <https://dmoj.ca/contest/vmss7wc16c3/submissions/Xyene/helloworld/> (I don't even have a ContestParticipation for that contest!)

**Comment by quantum5** [comment]
Is fixed.

If you want to fix https://dmoj.ca/contest/vmss7wc16c3/submissions/Xyene/vmss7wc16c3p1/ you will have to make a new ticket.

**Comment by Xyene** [comment]
This was a catch-all issue, but alright: #388.
