### ISSUE TITLE
SASS-y stylesheets

### ISSUE THREAD

**Issue by Xyene** [DMOJ/site#39]
http://sass-lang.com/

**Comment by quantum5** [comment]
SCSS or SASS? Translation: Python-style or C-style?

Well I think SASS is better as we use Python-style Jade already.

**Comment by Xyene** [comment]
Indeed, SASS.

**Comment by quantum5** [comment]
There is support for integration with django: http://stephengoeddel.com/blog/post/14/

**Comment by quantum5** [comment]
#136 adds `django_compressor` which is needed for the integration of SASS. However, SASS is a ruby gem and it requires loading ruby to use it, which is probably just as slow as loading the jvm.

**Comment by Xyene** [comment]
JRuby is actually supposedly faster than Ruby.

**Comment by Xyene** [comment]
And on the plus side we can use [Nailgun](http://www.martiansoftware.com/nailgun/) to avoid a constant startup cost.

**Comment by quantum5** [comment]
IDK if nailgun is actually worth is since the CSS is only generated on the first request and cached IDK how long, though I don't really want the first request to be too slow. Nailgun basically will consume a lot of memory on the server while idling.

**Comment by Xyene** [comment]
[style.css as SASS](https://gist.github.com/Xyene/abfa957d2d0b965d6847)

**Comment by quantum5** [comment]
It would be even better if we use Pleeease! after implementing #85, as there will be no need to add vendor prefixes.

**Comment by Xyene** [comment]
With SASS we can have a sane layout of stylesheets: instead of one bloated style.css we could have things like widgets.css, users.css, rating.css, and merge them all into one style.css for usage in templates.

**Comment by quantum5** [comment]
We could already do that with `cat` though, but I admit it's worse than SASS.

**Comment by Xyene** [comment]
You don't say.

**Comment by Xyene** [comment]
In the commit above I also removed all vendor prefixes in anticipation of #85

**Comment by quantum5** [comment]
I think we have enough SASS now.
