### ISSUE TITLE
Help me

### ISSUE THREAD

**Issue by SuperMegaDuck** [DMOJ/site#391]
Hello guys, your project is awesome, so I wanna try it on my hosting. But I followed the wiki and I was completely lost after Step 5. So can somebody help me what to do from now? Thank you :)
Luke

**Comment by WallE256** [comment]
Hey @SuperMegaDuck . If my memory does not fail me, firstly you have to compile the translation files: `python manage.py compilemessages` and `python manage.py compilejsi18n`. Then you just need to run `python manage.py migrate` for the database to be initialized, and `python manage.py runserver <ip>:<port>`, and as ip you can use `0.0.0.0` for the server is accessible from anywhere. For making a superuser (admin) you need to run `python manage.py createsuperuser` and go through what it asks you. If something does not work, come back with a message.

**Comment by SuperMegaDuck** [comment]
Thank you for your respond. I tried the first command: `python manage.py compilemessages`
But all I got was
> Traceback (most recent call last):
>  File "manage.py", line 8, in <module>
>    from django.core.management import execute_from_command_line
>ImportError: No module named django.core.management
Can you help me with this? Thank you.

**Comment by WallE256** [comment]
Is the virtualenv activated? If not, you have to do `source <envname>/bin/activate`

**Comment by SuperMegaDuck** [comment]
Yes, I activated the virtualenv. I believe so before any lines in terminal there is `(site)`

**Comment by WallE256** [comment]
Try now everything I wrote before.

**Comment by SuperMegaDuck** [comment]
I have done `source <envname>/bin/activate`, in my case `source site/bin/activate`. But the `ImportError: No module named django.core.management` keeps apearing.

**Comment by WallE256** [comment]
Did the `pip install -r requirements.txt` run successfully?

**Comment by SuperMegaDuck** [comment]
Yep, it ran successfully without any error.

**Comment by WallE256** [comment]
And still nothing? Weird... Maybe @Xyene or @quantum5 have any idea.

**Comment by SuperMegaDuck** [comment]
I run `python manage.py compilemessages` again, and now this shows up

> Traceback (most recent call last):
>   File "manage.py", line 10, in <module>
>     execute_from_command_line(sys.argv)
>   File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
>     utility.execute()
>   File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 327, in execute
>     django.setup()
>   File "/usr/local/lib/python2.7/dist-packages/django/__init__.py", line 18, in setup
>     apps.populate(settings.INSTALLED_APPS)
>   File "/usr/local/lib/python2.7/dist-packages/django/apps/registry.py", line 108, in populate
>     app_config.import_models(all_models)
>   File "/usr/local/lib/python2.7/dist-packages/django/apps/config.py", line 202, in import_models
>     self.models_module = import_module(models_module_name)
>   File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
>     __import__(name)
>   File "/root/code/site/judge/models.py", line 8, in <module>
>     from django.contrib.auth.models import User
>   File "/usr/local/lib/python2.7/dist-packages/django/contrib/auth/models.py", line 4, in <module>
>     from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
>   File "/usr/local/lib/python2.7/dist-packages/django/contrib/auth/base_user.py", line 49, in <module>
>     class AbstractBaseUser(models.Model):
>   File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py", line 108, in __new__
>     new_class.add_to_class('_meta', Options(meta, app_label))
>   File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py", line 299, in add_to_class
>     value.contribute_to_class(cls, name)
>   File "/usr/local/lib/python2.7/dist-packages/django/db/models/options.py", line 263, in contribute_to_class
>     self.db_table = truncate_name(self.db_table, connection.ops.max_name_length())
>   File "/usr/local/lib/python2.7/dist-packages/django/db/__init__.py", line 36, in __getattr__
>     return getattr(connections[DEFAULT_DB_ALIAS], item)
>   File "/usr/local/lib/python2.7/dist-packages/django/db/utils.py", line 212, in __getitem__
>     backend = load_backend(db['ENGINE'])
>   File "/usr/local/lib/python2.7/dist-packages/django/db/utils.py", line 116, in load_backend
>     return import_module('%s.base' % backend_name)
>   File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
>     __import__(name)
>   File "/usr/local/lib/python2.7/dist-packages/django/db/backends/mysql/base.py", line 28, in <module>
>     raise ImproperlyConfigured("Error loading MySQLdb module: %s" % e)
> django.core.exceptions.ImproperlyConfigured: Error loading MySQLdb module: No module named MySQLdb

**Comment by WallE256** [comment]
Much better. `pip install mysqlclient`

**Comment by SuperMegaDuck** [comment]
After doing that and installing WebSocket aferward, I faced this error

> /usr/local/lib/python2.7/dist-packages/django/utils/six.py:808: RemovedInDjango110Warning: SubfieldBase has been deprecated. Use Field.from_db_value instead.
>   return meta(name, bases, d)
> 
> Traceback (most recent call last):
>   File "manage.py", line 10, in <module>
>     execute_from_command_line(sys.argv)
>   File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
>     utility.execute()
>   File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 327, in execute
>     django.setup()
>   File "/usr/local/lib/python2.7/dist-packages/django/__init__.py", line 18, in setup
>     apps.populate(settings.INSTALLED_APPS)
>   File "/usr/local/lib/python2.7/dist-packages/django/apps/registry.py", line 108, in populate
>     app_config.import_models(all_models)
>   File "/usr/local/lib/python2.7/dist-packages/django/apps/config.py", line 202, in import_models
>     self.models_module = import_module(models_module_name)
>   File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
>     __import__(name)
>   File "/root/code/site/judge/models.py", line 29, in <module>
>     from judge import event_poster as event
>   File "/root/code/site/judge/event_poster.py", line 14, in <module>
>     from .event_poster_ws import last, post
>   File "/root/code/site/judge/event_poster_ws.py", line 6, in <module>
>     from websocket import create_connection, WebSocketException
> ImportError: cannot import name create_connection
>

**Comment by WallE256** [comment]
Try `websocket-client`

**Comment by SuperMegaDuck** [comment]
I have successfully run `python manage.py compilemessages`, but then I ran `python manage.py compilejsi18n` and got this

> Traceback (most recent call last):
>   File "manage.py", line 10, in <module>
>     execute_from_command_line(sys.argv)
>   File "/root/code/site/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
>     utility.execute()
>   File "/root/code/site/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 327, in execute
>     django.setup()
>   File "/root/code/site/local/lib/python2.7/site-packages/django/__init__.py", line 18, in setup
>     apps.populate(settings.INSTALLED_APPS)
>   File "/root/code/site/local/lib/python2.7/site-packages/django/apps/registry.py", line 108, in populate
>     app_config.import_models(all_models)
>   File "/root/code/site/local/lib/python2.7/site-packages/django/apps/config.py", line 202, in import_models
>     self.models_module = import_module(models_module_name)
>   File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
>     __import__(name)
>   File "/root/code/site/judge/models.py", line 8, in <module>
>     from django.contrib.auth.models import User
>   File "/root/code/site/local/lib/python2.7/site-packages/django/contrib/auth/models.py", line 4, in <module>
>     from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
>   File "/root/code/site/local/lib/python2.7/site-packages/django/contrib/auth/base_user.py", line 49, in <module>
>     class AbstractBaseUser(models.Model):
>   File "/root/code/site/local/lib/python2.7/site-packages/django/db/models/base.py", line 108, in __new__
>     new_class.add_to_class('_meta', Options(meta, app_label))
>   File "/root/code/site/local/lib/python2.7/site-packages/django/db/models/base.py", line 299, in add_to_class
>     value.contribute_to_class(cls, name)
>   File "/root/code/site/local/lib/python2.7/site-packages/django/db/models/options.py", line 263, in contribute_to_class
>     self.db_table = truncate_name(self.db_table, connection.ops.max_name_length())
>   File "/root/code/site/local/lib/python2.7/site-packages/django/db/__init__.py", line 36, in __getattr__
>     return getattr(connections[DEFAULT_DB_ALIAS], item)
>   File "/root/code/site/local/lib/python2.7/site-packages/django/db/utils.py", line 212, in __getitem__
>     backend = load_backend(db['ENGINE'])
>   File "/root/code/site/local/lib/python2.7/site-packages/django/db/utils.py", line 116, in load_backend
>     return import_module('%s.base' % backend_name)
>   File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
>     __import__(name)
>   File "/root/code/site/local/lib/python2.7/site-packages/django/db/backends/mysql/base.py", line 28, in <module>
>     raise ImproperlyConfigured("Error loading MySQLdb module: %s" % e)
> django.core.exceptions.ImproperlyConfigured: Error loading MySQLdb module: No module named MySQLdb

**Comment by SuperMegaDuck** [comment]
oh nevermind I solved that :p

**Comment by SuperMegaDuck** [comment]
Running `python manage.py compilejsi18n` now return in this

> /root/code/site/local/lib/python2.7/site-packages/django/utils/six.py:808: RemovedInDjango110Warning: SubfieldBase has been deprecated. Use Field.from_db_value instead.
>   return meta(name, bases, d)
> 
> /root/code/site/local/lib/python2.7/site-packages/six.py:808: RemovedInDjango110Warning: SubfieldBase has been deprecated. Use Field.from_db_value instead.
>   return meta(name, bases, d)
> 
> /root/code/site/local/lib/python2.7/site-packages/django/core/management/base.py:265: RemovedInDjango110Warning: OptionParser usage for Django management commands is deprecated, use ArgumentParser instead
>   RemovedInDjango110Warning)
> 
> Traceback (most recent call last):
>   File "manage.py", line 10, in <module>
>     execute_from_command_line(sys.argv)
>   File "/root/code/site/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
>     utility.execute()
>   File "/root/code/site/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 345, in execute
>     self.fetch_command(subcommand).run_from_argv(self.argv)
>   File "/root/code/site/local/lib/python2.7/site-packages/django/core/management/base.py", line 348, in run_from_argv
>     self.execute(*args, **cmd_options)
>   File "/root/code/site/local/lib/python2.7/site-packages/django/core/management/base.py", line 399, in execute
>     output = self.handle(*args, **options)
>   File "/root/code/site/local/lib/python2.7/site-packages/django/core/management/base.py", line 584, in handle
>     return self.handle_noargs(**options)
>   File "/root/code/site/local/lib/python2.7/site-packages/statici18n/management/commands/compilejsi18n.py", line 64, in handle_noargs
>     settings.STATICI18N_OUTPUT_DIR)
>   File "/root/code/site/lib/python2.7/posixpath.py", line 77, in join
>     elif path == '' or path.endswith('/'):
> AttributeError: 'NoneType' object has no attribute 'endswith'

**Comment by WallE256** [comment]
Does the `STATIC_ROOT` folder exist?

**Comment by SuperMegaDuck** [comment]
How to check it? And how to assign it?

**Comment by WallE256** [comment]
In `dmoj/local_settings.py'

**Comment by SuperMegaDuck** [comment]
What dir should I put in the `STATIC_ROOT`?

**Comment by WallE256** [comment]
A folder where the site can create a bunch of javascript files.

**Comment by SuperMegaDuck** [comment]
After running the next command, it returned

> django.db.utils.OperationalError: (1049, "Unknown database 'dmoj'")

I assumed that I haven't created the database. But how?

**Comment by quantum5** [comment]
You need to look at the MySQL documentation on how to do so, or Google for it. [Here](https://www.debuntu.org/how-to-create-a-mysql-database-and-set-privileges-to-a-user/) is a link that may help.

**Comment by SuperMegaDuck** [comment]
Finally, thanks to your help, I have managed to install the server.
But can you help me with some more problems?
- Languages that are written in Unicode character appear as `?`
- How to add some more programming languages?
- How to add some menus in navbar like in [http://dmoj.ca](url)?
Thanks you :D

**Comment by quantum5** [comment]
The lack of Unicode support may be because of browser settings, fonts, or perhaps MySQL using `latin1_swedish_ci` instead of `utf8mb4_general_ci`.

As for menus, that is in admin under navigation bar.

**Comment by SuperMegaDuck** [comment]
I reinstalled the site. When I got to the `./make_style.sh` step, I received this `./make_style.sh: line 4: pleeease: command not found`

**Comment by SuperMegaDuck** [comment]
Oops, I solved this :p

**Comment by SuperMegaDuck** [comment]
When I run `python main.py <bridge hostname> -p <bridge port> [-c <config path>]`, I got this. Does anyone know how to fix this?

> MemoryError
> Traceback (most recent call last):
>   File "main.py", line 4, in <module>
>     main()
>   File "/root/lhpoj/judge/judge.py", line 686, in main
>     judge = ClassicJudge(judgeenv.server_host, judgeenv.server_port)
>   File "/root/lhpoj/judge/judge.py", line 666, in __init__
>     self.packet_manager = packet.PacketManager(host, port, self, env['id'], env['key'])
>   File "/root/lhpoj/judge/packet.py", line 38, in __init__
>     self._connect()
>   File "/root/lhpoj/judge/packet.py", line 48, in _connect
>     self.handshake(self.judge.supported_problems(), self.name, self.key)
>   File "/root/lhpoj/judge/packet.py", line 145, in handshake
>     raise JudgeAuthenticationFailed()
> packet.JudgeAuthenticationFailed
> Exception TypeError: 'shutdown() takes exactly one argument (0 given)' in <bound method PacketManager.__del__ of <packet.PacketManager object at 0xb726ea6c>> ignored
> Exception AttributeError: "'ClassicJudge' object has no attribute '_monitor'" in <bound method ClassicJudge.__del__ of <judge.ClassicJudge object at 0xb726e98c>> ignored
>

**Comment by SuperMegaDuck** [comment]
@WallE256 @quantum5 Can you guys help me with this? :( My teacher is asking for the site

**Comment by SuperMegaDuck** [comment]
I set the `BRIDGED_JUDGE_PORT` in `local_setting.py` to 9999, but when I connect to judge to that port, it said `socket.error: [Errno 111] Connection refused`. Can you help me with this? @quantum5  @WallE256

**Comment by WallE256** [comment]
You have to actually start the bridge with `python manage.py runbridged`

**Comment by SuperMegaDuck** [comment]
When I ran that, it returned

>   File "/root/lhpoj/site/local/lib/python2.7/site-packages/django/db/models/options.py", line 582, in get_field
>     raise FieldDoesNotExist('%s has no field named %r' % (self.object_name, field_name))
> django.core.exceptions.FieldDoesNotExist: Judge has no field named 'online'

**Comment by SuperMegaDuck** [comment]
When I run that, it returned @WallE256 

> Traceback (most recent call last):
>   File "manage.py", line 10, in <module>
>     execute_from_command_line(sys.argv)
>   File "/root/lhpoj/site/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
>     utility.execute()
>   File "/root/lhpoj/site/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 345, in execute
>     self.fetch_command(subcommand).run_from_argv(self.argv)
>   File "/root/lhpoj/site/local/lib/python2.7/site-packages/django/core/management/base.py", line 348, in run_from_argv
>     self.execute(*args, **cmd_options)
>   File "/root/lhpoj/site/local/lib/python2.7/site-packages/django/core/management/base.py", line 399, in execute
>     output = self.handle(*args, **options)
>   File "/root/lhpoj/site/judge/management/commands/runbridged.py", line 12, in handle
>     judge_server = JudgeServer(settings.BRIDGED_JUDGE_HOST, settings.BRIDGED_JUDGE_PORT, DjangoJudgeHandler)
>   File "/root/lhpoj/site/judge/bridge/judgeserver.py", line 20, in __init__
>     reset_judges()
>   File "/root/lhpoj/site/judge/bridge/judgeserver.py", line 14, in reset_judges
>     Judge.objects.update(online=False, ping=None, load=None)
>   File "/root/lhpoj/site/local/lib/python2.7/site-packages/django/db/models/manager.py", line 122, in manager_method
>     return getattr(self.get_queryset(), name)(*args, **kwargs)
>   File "/root/lhpoj/site/local/lib/python2.7/site-packages/django/db/models/query.py", line 626, in update
>     query.add_update_values(kwargs)
>   File "/root/lhpoj/site/local/lib/python2.7/site-packages/django/db/models/sql/subqueries.py", line 126, in add_update_values
>     field = self.get_meta().get_field(name)
>   File "/root/lhpoj/site/local/lib/python2.7/site-packages/django/db/models/options.py", line 582, in get_field
>     raise FieldDoesNotExist('%s has no field named %r' % (self.object_name, field_name))
> django.core.exceptions.FieldDoesNotExist: Judge has no field named 'online'
>

**Comment by WallE256** [comment]
Apparently, as far as I understand, the bridged judge connection was broke by  db086027115fa7bd0454acc894a3e38c9603f6c4 , so you have to connect the judge to RabbitMQ and instead of `runbridged` you use `runamqpd`, and as a address for the judge you use `amqp://<serveradress>/<vhost>` where you replace serveradress and vhost with the ones used when installing the site.

**Comment by SuperMegaDuck** [comment]
When I used `runamqpb`, it returned

> File "/root/lhpoj/site/local/lib/python2.7/site-packages/pika/adapters/blocking_connection.py", line 395, in _flush_output
>     raise exceptions.ConnectionClosed()
> pika.exceptions.ConnectionClosed

And by the address for the judge, you mean the one in `python main.py <bridge hostname> -p <bridge port> [-c <config path>]` ?

**Comment by WallE256** [comment]
Is the rabbitmq server on? And at the judge part, instead of bridge address and bridge port, you just supply a link to the server as I said above

**Comment by SuperMegaDuck** [comment]
Oops... the node is down. I tried to restart the service but it didn't work. How can I get the server to run normally again?

**Comment by SuperMegaDuck** [comment]
When I add

> [
>   {rabbit, [
>     {auth_backends, [rabbit_auth_backend_internal, rabbit_auth_backend_http]}
>   ]},
>   {rabbitmq_auth_backend_http, [
>     {user_path, "http://localhost/api/judge/auth/rabbitmq/user"},
>     {vhost_path, "http://localhost/api/judge/auth/rabbitmq/vhost"},
>     {resource_path, "http://localhost/api/judge/auth/rabbitmq/resource"}
>   ]}
> ]. 

to the `enabled_plugins` file, Rabbitmq crashed. So is there anything wrong here? I'm using Rabbitmq 3.6.0

**Comment by WallE256** [comment]
You need to add that thing to `rabbitmq.config` , and `enabled_plugins` should have something like `[rabbitmq_auth_backend_http,rabbitmq_management].`

**Comment by SuperMegaDuck** [comment]
I have successfully used `runamqpd`, but then I ran the judge, it responded

> Traceback (most recent call last):
>   File "main.py", line 1, in <module>
>     from judge import main
>   File "/root/lhpoj/judge/judge.py", line 5, in <module>
>     import judgeenv
>   File "/root/lhpoj/judge/judgeenv.py", line 73, in <module>
>     env = yaml.safe_load(init_file)
> AttributeError: 'NoneType' object has no attribute 'safe_load'
>

**Comment by Xyene** [comment]
You must install `pyyaml` via `pip install pyyaml` in your virtualenv.

**Comment by SuperMegaDuck** [comment]
Do I need to install Judge inside the Site folder, or outside? Because Judge folder don't have the bin/activate to run virtualenv

**Comment by Xyene** [comment]
You should install it outside of the site; if you don't have a virtualenv for it, then installing those modules to whatever global Python install it's using is sufficient.

**Comment by SuperMegaDuck** [comment]
When I connect the Judge, it said `ChannelClosed`

**Comment by SuperMegaDuck** [comment]
Now I got `ProbableAuthenticationError` :(, although I sure that my Rabbitmq password is corrected

**Comment by SuperMegaDuck** [comment]
And the judge is connecting to port 5672, instead of port 15672 of Rabbitmq

**Comment by WallE256** [comment]
Did you define the judge in the admin panel? And also note that you have to run the `runserver` and `runamqpd` at the same time when you boot the judge. And also you need to add the port to the rabbitmq config if `runserver` runs on a specific port.

**Comment by SuperMegaDuck** [comment]
How to add the port in the rabbitmq config?

Date: Sat, 20 Feb 2016 10:14:45 -0800

**Comment by SuperMegaDuck** [comment]
How to add the port into the rabbitmq config file?

**Comment by SuperMegaDuck** [comment]
How to add the port into the rabbitmq config file?

**Comment by SuperMegaDuck** [comment]
And is the node port as same as rabbitmq's port?

**Comment by SuperMegaDuck** [comment]
Thank you guys. After 4 days, I was managed to run the server, thanks to your help :D
