### ISSUE TITLE
CCC Test-Data has extra space (CCC 2010 S3 Firehose)

### ISSUE THREAD

**Issue by MathBunny** [DMOJ/site#392]
I emailed CEMC back in December and they fixed it on their site. There's an extra space so with Java if you use BufferedReader and readLine() you get an Invalid Return (it passes in C++ or if you do .trim()):

https://dmoj.ca/submission/155766 (AC except for one IR)
https://dmoj.ca/submission/155813 (AC but checking for that space)

**Comment by quantum5** [comment]
Issues for the DMOJ problem set should be reported to https://github.com/DMOJ/problems/issues

**Comment by MathBunny** [comment]
Okay thanks, I forwarded the problem there.
