### ISSUE TITLE
Submission pages for private problems

### ISSUE THREAD

**Issue by cheesycake** [DMOJ/site#394]
Users are currently able to access problem submissions pages even if they are marked as private. Potentially dangerous bug. Contestants participating in virtual contests can check their solution's correctness before actually entering the contests if they were able to obtain the problem statement ahead of time.

**Comment by Xyene** [comment]
Fixed; introduced a helper method that we can use from now on to check if a problem is accessible by a user.

**Comment by cheesycake** [comment]
Users are still able to submit by some unknown means. A more solid fix would be to check problem accessibility after submission.
