### ISSUE TITLE
Problem Adding API

### ISSUE THREAD

**Issue by WallE256** [DMOJ/site#397]
The problem adding progress is a pain in the ass. Even experienced problem setters as @Xyene and @cheesycake can tell you that is a tedious process. For newcomers, this is even a bigger problem. For the future problem setters of DMOJ, an external app (companion) would be useful. This is were this API comes in. Each user that is granted a specific permission would get a API key, which the app will use for communication with the server. Problems added still need to be approved by an admin. Besides all the information a problem holds, the submitted problem will hold an extra link to the place where the problem setter has the test data generated using the app. This still needs to be done manual at the moment.

**Comment by quantum5** [comment]
Superseded by #467.
