### ISSUE TITLE
Dangerous methods should be marked so

### ISSUE THREAD

**Issue by quantum5** [DMOJ/site#400]
@Xyene got real baited in 2a259efd010129918fe8401c50e86934fe8a07b4. Let's not let him rejudge random stuff from a template.

[From Django documentation](https://docs.djangoproject.com/en/1.9/ref/templates/api/#variables-and-lookups):

> Obviously, there can be side effects when calling some variables, and it’d be either foolish or a security hole to allow the template system to access them.
> 
> A good example is the delete() method on each Django model object. The template system shouldn’t be allowed to do something like this:
> 
> ``` HTML+Django
> I will now delete this valuable data. {{ data.delete }}
> ```
> 
> To prevent this, set an alters_data attribute on the callable variable. The template system won’t call a variable if it has alters_data=True set, and will instead replace the variable with string_if_invalid, unconditionally. The dynamically-generated `delete()` and `save()` methods on Django model objects get `alters_data=True` automatically. Example:
> 
> ``` python
> def sensitive_function(self):
>     self.database_record.delete()
> sensitive_function.alters_data = True
> ```

**Comment by Xyene** [comment]
There are no more data-altering methods that are not marked so.
