### ISSUE TITLE
Optional subscription to newsletter on registeration page

### ISSUE THREAD

**Issue by quantum5** [DMOJ/site#401]
Users may not know about the subscription. An opt-in subscription on the registration page would help.

**Comment by quantum5** [comment]
Is added and appears to work.

**Comment by Xyene** [comment]
Real duplicate of https://github.com/DMOJ/site/issues/382 though.

**Comment by quantum5** [comment]
Oh man I searched newsletter and didn't find any. Turns out I forgot synonym mailing list.
