### ISSUE TITLE
Newsletter subscription on the edit profile page

### ISSUE THREAD

**Issue by quantum5** [DMOJ/site#402]
Would seem like a good idea to be able to change your mind after all!

And no, payment not required.

**Comment by Xyene** [comment]
Would also remove the need to convert [all these templates](https://github.com/DMOJ/site/tree/master/templates/newsletter) into Jade.

**Comment by quantum5** [comment]
The newsletter app still uses them...

**Comment by Xyene** [comment]
Things like [the newsletter list](https://github.com/DMOJ/site/blob/master/templates/newsletter/newsletter_list.jade) will never be seen by user eyes.

**Comment by quantum5** [comment]
This is implemented.
