### ISSUE TITLE
Spectate contest mode

### ISSUE THREAD

**Issue by Xyene** [DMOJ/site#405]
Organizers of contests should have their Join buttons replaced by a Spectate button, which gives them the full contest duration on their timer and automatically excludes them from rankings/ratings. Would be implemented by a `spectator` `BooleanField` in the `ContestParticipation` model.

If the ranking exclusion works, this could be a base for virtual contests in #24.

**Comment by quantum5** [comment]
You mean `ContestParticipation`?

**Comment by Xyene** [comment]
Too tired.

**Comment by quantum5** [comment]
This is pretty trivial. Just one migration, and override the start/end time logic on the participation, and then simply filter when doing rankings.

**Comment by Xyene** [comment]
Potential improvement: allow users to "Spectate contest" after their timer ends. However, this wouldn't work as-is with the currently-added `ContestProfile` uniqueness.

**Comment by Xyene** [comment]
The goals of this ticket have been accomplished. Spectate mode is now a special subset of virtual mode where `virtual = -1`. See the ticket for virtual participation, #24.
