### ISSUE TITLE
api, contest list and external

### ISSUE THREAD

**Issue by aropan** [DMOJ/site#408]
Please, pass flag in get parameters `?external=True` for get contest list throught api in this [line](https://github.com/DMOJ/site/blob/8115b90fdb06cbfc452d3306d6abc4f5c59dda1c/judge/views/api.py#L16)?

**Comment by Xyene** [comment]
Hi, thanks for noticing; the contest API hasn't been touched in a long time.

I've made the JSON response contain external contests as well now, with a new "labels" node denoting whether they are external or not, in preparation for #377. To check whether a contest is external, query whether 'external' exists in 'contest.labels'.

Hope that helps!

**Comment by aropan** [comment]
Yep, thanks for fast fix.
