### ISSUE TITLE
Please help. Exception in loading home page due to Internationalization and localization settings.

### ISSUE THREAD

**Issue by shuklarahul142** [DMOJ/site#413]
First of all, thanks a lot of creating such awesome product! 
Words won't be enough to show the gratitude.

I am facing a problem for a long time now, tried everything I could

I am uploading an image here, I am getting exception in the html file. This code is getting auto-generated from djangojs.js(I think this file is related to Internationalization and localization). I feel something is wrong with my settings. Please help me.

This is my settings

`
STATIC_ROOT = os.path.join(BASE_DIR, 'static')
 STATICFILES_DIRS = [
     os.path.join(BASE_DIR, 'resources'),
 ]
 STATIC_URL = '/static/'
`
I hope you would help me soon.

**Comment by shuklarahul142** [comment]
![jserror](https://cloud.githubusercontent.com/assets/19421176/15347980/1eeb99d2-1ce4-11e6-94bf-13eba58dee64.png)

**Comment by quantum5** [comment]
Chances are you need to use our own version of [`pyjade`](https://github.com/DMOJ/pyjade). They haven't pulled in our pull request yet, so this is the temporary solution.

**Comment by shuklarahul142** [comment]
Thanks a lot for such a quick reply!
Sorry for my naiveness, If there any way we can do away with djangojs.js(which is generating this js in HTML)? I am only looking for the quickest way to setup DMOJ doesn't matter how many hacks need to put. After that I can try to fix these issue.
Please help.

**Comment by shuklarahul142** [comment]
I installed pyjade version which you provided. Restarted the server, still getting same error. Please let me know, what I have missed? 
Please help.

**Comment by WallE256** [comment]
Hey @shuklarahul142 . I also had this problem on my deployment of the site, and the changed pyjade didn't help. For solving my problem, I manually changed in `templates/base.jade` that the script should not be inline, and just served. That solved the issue in my setup.

**Comment by shuklarahul142** [comment]
Thanks a lot for you reply WallE256!!
I couldn't get what I need to change in `templates/base.jade` file. Could you please help me by providing your changes file?
Thanks a lot.
Please help.

**Comment by WallE256** [comment]
This is the output from `git diff` for base.jade. It also contains a fix for one other problem, but don't mind that. http://pastebin.com/cvt4UP6Y

**Comment by shuklarahul142** [comment]
Thanks a ton!! You are awesome!
Thanks again!
This is the first time app is running without any error in console!
Now when I try to register, I am always getting 'Your chosen username is already taken.' Could you please point me what could be wrong?

**Comment by WallE256** [comment]
@shuklarahul142 hmm... Try creating your user with `python manage.py createsuperuser`. If this doesn't help, you have to check the database. Also, note that the docs are not up to date with the recent changes (we dropped RabbitMQ). I will update them in about 1 month.

**Comment by shuklarahul142** [comment]
Thanks a ton again! I was playing around RabbitMQ thinking I had done some mistake.
Now finally I am logged in! Thanks again!
