### ISSUE TITLE
Pre-SNI browser support

### ISSUE THREAD

**Issue by quantum5** [DMOJ/site#415]
Let's detect ancient browsers and just use `dmoj.ca` to serve statics for them. This will allow DMOJ to work once again on my Windows NT 4.0 VM.

**Comment by Xyene** [comment]
Except most of the stylesheets don't work, so the site looks highly poor.

**Comment by quantum5** [comment]
Yes it does look kinda poor, especially with `flex`.

**Comment by quantum5** [comment]
This is moot after we put `dmoj.ca` on Cloudflare.
