### ISSUE TITLE
Display last IP in judge admin

### ISSUE THREAD

**Issue by Xyene** [DMOJ/site#416]
Would be useful to check if your judge has somehow been compromised.

**Comment by quantum5** [comment]
Parsing log files is clearly not acceptable, so we need an extra field.

**Comment by quantum5** [comment]
Implemented. But @Xyene, how will you know what the real IP address is? Should we implement a field to store it, and perhaps block authentication if the IP is incorrect?

**Comment by Xyene** [comment]
Nice! If we do, it should be in a separate ticket, though it'd be somewhat redundant for the common use cases (since we have auth keys anyway).
