### ISSUE TITLE
Use case_points for submission ranking

### ISSUE THREAD

**Issue by Xyene** [DMOJ/site#417]
Currently we use awarded points, which makes ranking fail when rounding does not produce expected results:

<https://dmoj.ca/submission/251338>

This is a historical mistake on our part, but fixing it now is a pain. Rather than using total case points, ranking pages use the awarded points, which involves rounding. For almost all problems this is fine, though in the one above 4.95 rounds to 5.0 (full points).

Changing the rankings to use case points in itself is easy, but there are problems where the case points were updated without all prior submissions being rejudged (as in the case where a problemsetter changes data without rejudging their own submissions). Unless we want to break rankings on those problems, we need to rejudge all non-conforming submissions.

As the site has no knowledge of problem data (which is stored only on judge servers), this requires a bit of work with querying the judges. We can create a mapping of `problem id:case points` using the judge API, import that into the site, and rejudge all non-conforming submissions.

**Comment by quantum5** [comment]
I hesitate to declare this a historical mistake, since rankings were originally using awarded points, until someone came by and made a zero point problem.

**Comment by Xyene** [comment]
```python
import os
from operator import attrgetter

import yaml

from dmoj import judgeenv
from dmoj.config import ConfigNode

if __name__ == '__main__':
    judgeenv.load_env(cli=True)

    mapping = {}

    for problem, mtime in judgeenv.get_supported_problems():
        init = os.path.join(judgeenv.get_problem_root(problem), 'init.yml')
        if not os.path.isfile(init):
            continue
        print problem
        with open(init, 'r') as f:
            init = ConfigNode(yaml.load(f.read()))
            case_points = sum(map(attrgetter('points'), init.test_cases))
            mapping[problem] = case_points
    print mapping
```

Resulted in this monster: https://gist.githubusercontent.com/Xyene/287a2d96d0e56081da2b6c5f6bd7f085/raw/f7d47796feceb54d0908c42318e6dc8e65c0b1f3/case_points.txt

**Comment by Xyene** [comment]
This is about as good as it's going to get - 3 decimal places of precision for points. It's likely that we could allow full float precision without rounding, but that sounds like the kind of change that'll lead to hard-to-find bugs later down the road. 3 places is more than plenty for any sane problem.
