### ISSUE TITLE
Comment improvements

### ISSUE THREAD

**Issue by Xyene** [DMOJ/site#426]
The current comment system works, but leaves things to be desired from a UX standpoint. A couple ideas towards its improvement:
- <del>use moment.js to format comment times like we do for submissions</del>
- <del>somehow highlight the comments which you've voted on (`color`? `text-shadow`?)</del>
- <del>remove comment titles from non-root comments (they're almost all "Re: " chains anyway)</del>
  - <del>if we do, we need to think about how we'll handle the comment box, since we'll either have to remove the comment title input field or disable it</del>
- <del>adding onto the last bullet, most comment titles are typically just additions to the comment body, so we can consider getting rid of them to begin with</del>
  - if we do, we'll have to somehow merge old comments, and this may be a manual process (so that useless titles like "Note" are removed, but those that are questions themselves are merged into the body)
  - <del>likewise if this is done, the comment stream (which is short of space) can be simplified</del>
- <del>rewrite comment styles to look better, especially when nested many levels deep</del>
  - <del>rectangle boxes? style more similar to the edit profile page? bigger gravatar?</del>

**Comment by quantum5** [comment]
Voting is fully implemented.

**Comment by Xyene** [comment]
Also another point to note is that the current comment edit form does not validate the fields like the comment submit form does.

**Comment by Xyene** [comment]
By the last point, I mean that you can edit a comment to have an empty title.

**Comment by Xyene** [comment]
Users should not be allowed to edit comment titles. Having titles changed to "NVM" without any such revision history public is not ideal, nor should we include comment title revisions in the history view.

**Comment by BinAccel** [comment]
Can the page be refreshed after you edit a comment? Right now you have to refresh manually for the edits to take effect.

**Comment by quantum5** [comment]
Why are comment titles still in the database? Obviously if they are lost, no one has really complained, so why do they still live?
