### ISSUE TITLE
Runtime version updates

### ISSUE THREAD

**Issue by Xyene** [DMOJ/site#429]
After DMOJ/judge#197, a number of views require changes.
- Runtime info pages (e.g., https://dmoj.ca/runtime/AWK)
  - We could do away with these entirely, and just add fancy copy-like tooltips stating version over each judge runtime in the status tables. The links would then be changed to point to the runtime listing page, with an appropriate anchor.
- Auto-generated runtime page (https://dmoj.ca/runtimes/)
- Runtime versions on judge pages (https://dmoj.ca/judge/Herculaneum), perhaps collapsed like we do for problem groups in user profiles.

**Comment by quantum5** [comment]
How is this going?

**Comment by Xyene** [comment]
Language pages aren't autogenerated. (I don't particularly feel the urge to implement that anytime soon, though.)

**Comment by Xyene** [comment]
This has been completed. The weird spacing bug keeping this from happening in appears to have been fixed in recent versions of Django.
