### ISSUE TITLE
License field on Problem model

### ISSUE THREAD

**Issue by Xyene** [DMOJ/site#43]
Some problems may be licensed, in which case it would be good to have a general mode to display licenses, in the info-float or similar. For example, <http://www.dmoj.ca/problem/origami>

We could even store license texts on the DMOJ for easy reading.

**Comment by Xyene** [comment]
Using a CC license as an example, the short text portion along with possibly an icon should be displayed, `float:right`, under the bottom `<hr>`. Care should be taken to ensure that this change is made for the raw view used for PDF generation, such that the license text appears there as well.

**Comment by quantum5** [comment]
It now clearly links to the license page. The license page in #44 needs improvement, but there is not much you can do here.
