### ISSUE TITLE
List of UI issues that bother me

### ISSUE THREAD

**Issue by Xyene** [DMOJ/site#431]
This isn't really a typical issue, it's more of a place to list the parts of the UI that bother me but don't deserve their own tickets. Most of these are minor, but have become exasperating after seeing them every day. There's a separate list of these for bugs in the admin site, but at least those don't impact users.

---
- <del>wildly varying font sizes, even on the same page (4 below)</del>

![image](https://cloud.githubusercontent.com/assets/1403503/17351903/9b24bc1a-5900-11e6-82cf-ba906e6ba482.png)

---
- <del>the styling for the category search feature (or lack thereof)</del>

![image](https://cloud.githubusercontent.com/assets/1403503/17351931/cf09ff68-5900-11e6-87c9-b0f2b44a7d73.png)

---
- the contest timer

![image](https://cloud.githubusercontent.com/assets/1403503/17351944/e6ba0a90-5900-11e6-8aa6-c7e375a0ff64.png)

---
- <del>the memory icon, though I couldn't find a better one and the info area looks weird without them now</del>

![image](https://cloud.githubusercontent.com/assets/1403503/17351963/fdfcb34c-5900-11e6-939f-4bf2060285e1.png)

---
- <del>this weird border that's a regression from sometime; the entire table CSS is a mess too</del>

![image](https://cloud.githubusercontent.com/assets/1403503/17351976/14978ca8-5901-11e6-885a-bfa58381eadf.png)

---
- <del>ranking column is probably too wide</del>

![image](https://cloud.githubusercontent.com/assets/1403503/17352007/4c2c19f4-5901-11e6-8cc1-f0320dfd0f2e.png)

---
- <del>organizations overlap with username in small screens, made rankings difficult to read during DMPG</del>

![image](https://cloud.githubusercontent.com/assets/1403503/17352025/6ba053cc-5901-11e6-895d-c3d27f0a9052.png)

---
- <del>shadow appears to appear "over" navbar dropdown, since it's transparent</del>

![image](https://cloud.githubusercontent.com/assets/1403503/17352041/972dc7ea-5901-11e6-9463-77ef1fe5a396.png)

---
- I can totally understand when these contests took place... wait, no I can't.

![image](https://cloud.githubusercontent.com/assets/1403503/17352068/d4227812-5901-11e6-8e55-43eb3ae77aa6.png)
![image](https://cloud.githubusercontent.com/assets/1403503/17352087/e85bd9e0-5901-11e6-8edb-7fb5e3358bd0.png)

---
- problem types / allowed languages expand from a corner, causing a split-second where it's totally unreadable; either change to expanding from top or have it expand immediately

![image](https://cloud.githubusercontent.com/assets/1403503/17352137/27c13a6c-5902-11e6-8b3c-fe87ff9078a4.png)

---
- same thing for problems in user profiles; these actually lag when opening so the transition isn't even smooth

![image](https://cloud.githubusercontent.com/assets/1403503/17352153/4b492576-5902-11e6-8b3d-c569dbaf9b36.png)

---
- <del>uneven spacing between paginator and submission list</del>

![image](https://cloud.githubusercontent.com/assets/1403503/17352174/7eec2f36-5902-11e6-948f-69b1b4e5deb3.png)

---
- <del>this text really doesn't look vertically aligned</del>

![image](https://cloud.githubusercontent.com/assets/1403503/17352194/aa7c1620-5902-11e6-81bf-040770e20229.png)

---
- <del>wrapping of the time, under all circumstances</del>

![image](https://cloud.githubusercontent.com/assets/1403503/17352244/05a59d46-5903-11e6-952e-3dad4a3b554e.png)

**Comment by quantum5** [comment]
The last one is because it's a div and not a span for some unfanthomable reason.

**Comment by Xyene** [comment]
For the last one, we really should get around to removing it entirely and using the fancy countdown we use pre-contest.

**Comment by quantum5** [comment]
Are you done here? Clearly the remaining "issues" do not bother you enough...

**Comment by Xyene** [comment]
I'm still very bothered by organization overlap in contests, but haven't thought of a good way to do it yet.

**Comment by Xyene** [comment]
The majority of this has been completed to a satisfactory extent, especially that awful organization listing in rankings.
