### ISSUE TITLE
License model

### ISSUE THREAD

**Issue by Xyene** [DMOJ/site#44]
For wherever we need to link licenses, it would be good to have them on-site along with a link off-site to their official pages.

References #43

**Comment by quantum5** [comment]
Suggested fields: key, link, full name, text.

DO NOT VERSION.

**Comment by Xyene** [comment]
Thoughts on a comments section for any possible clarification requests?

**Comment by quantum5** [comment]
Comment section is trivial matter. `CommentedDetailView` is too amazing. But what would clarification be about? We are not lawyers and since we don't hold copyright it is unlikely that we can grant any permissions.

**Comment by FatalEagle** [comment]
At first I thought @Xyene  was talking about clarification request during contest...

**Comment by quantum5** [comment]
Should problems be single licensed or potentially multi-licensed?

**Comment by Xyene** [comment]
Dual licensed problems sound ultra sketchy, but we probably should in case we ever come across one.

**Comment by quantum5** [comment]
Please remember to create a migration. This is Django 1.7 now.

**Comment by Xyene** [comment]
Possibly an optional icon URL field, for displaying things like the CC icon.

**Comment by quantum5** [comment]
Should include a `display` string field, defaulting to `This work is licensed under the <name>`, so we can override it as being displayed like: "This work is licensed under a Creative Commons Attribution-ShareAlike 3.0 Unported License." This is important for the public domain which takes the preposition `in`.

Stupid English...

**Comment by quantum5** [comment]
Do we agree on the schema?

```python
class License(models.Model):
    key = models.CharField(max_length=20)
    link = models.CharField(max_length=256)
    name = models.CharField(max_length=256)
    display = models.CharField(max_length=256, blank=True)
    icon = models.CharField(max_length=256, blank=True) # URL
    text = models.TextField() # Markdown
```

**Comment by quantum5** [comment]
The license template is not finished.

**Comment by Xyene** [comment]
See my comment on #58 

Specifically,

> For all intents and purposes that we currently have (and the small amount of problems that are actually licensed on the DMOJ), the current implementation is sufficient.

There is not much more we can display: most (all?) license texts link `link`, so displaying it twice is redundant. `icon`? I'm not convinced we should display it on the license page.

**Comment by quantum5** [comment]
Note how the license page has `info-float` but no content.

**Comment by Xyene** [comment]
I asketh for a close.

**Comment by quantum5** [comment]
I have been framed.

**Comment by Xyene** [comment]
I used my psychic powers to read the future. In the future, you asketh'd for the space.
