### ISSUE TITLE
Use Mathoid for Math

### ISSUE THREAD

**Issue by quantum5** [DMOJ/site#440]
Wikimedia Foundation's new math server `mathoid` is obviously going to be better than anything I can spin up, so we might as well add some support for it, as MediaWiki is doing for their `Extension:Math`.

**Comment by quantum5** [comment]
Mathoid works great except when it hangs.

**Comment by quantum5** [comment]
Perhaps we can now improve math in RSS feeds.

**Comment by Xyene** [comment]
> Assuming people use the RSS feeds

**Comment by quantum5** [comment]
Literally doing this for myself.

**Comment by quantum5** [comment]
Mathoid hangs when there are unescaped `$` in the math.

**Comment by quantum5** [comment]
Mathoid does not hang anymore I think.
