### ISSUE TITLE
CSP prevents image preview without #444

### ISSUE THREAD

**Issue by quantum5** [DMOJ/site#446]
We do not plan to use #444 for comments, however CSP (#268) prevents the comment preview from working at all. Hence, we must do something secure, yet would not prevent the preview from working.

Solution is either to use #444, or have a special view to generate the `camo` URL securely, without leaking the secret key.

/cc @Xyene

**Comment by quantum5** [comment]
I believe the solution is to use #444, since the preview will not be accurate otherwise, defeating the whole point.

**Comment by Xyene** [comment]
However previews for comments don't need to be accurate; they need to be fast and easy to use. Most comments don't need fancy Markdown, so the accuracy that is a must for problem statements is not needed, and indeed the usability of pagedown surpasses that of #446 for small text snippets.

**Comment by quantum5** [comment]
I disagree. Look at GitHub issue comments. Preview is unnecessary for trivial comments like this, yet when needed I'd rather it be accurate.

**Comment by quantum5** [comment]
This is solved. Auto-preview will be tracked in #444.
