### ISSUE TITLE
Link contest submissions

### ISSUE THREAD

**Issue by Xyene** [DMOJ/site#448]
Suggested by @WallE256. For example,

![image](https://cloud.githubusercontent.com/assets/1403503/17829096/ce70c276-6670-11e6-8f44-5df114f9b327.png)

Notes:
- displays fine in mobile
- would naturally omit during contests

Undecided:
- should we show this in submission rankings?

**Comment by quantum5** [comment]
The practical answer to showing in submission rankings is no. While it is not as raw SQL as it was before, it still makes it annoying should I need to change the way it is implemented.

**Comment by Xyene** [comment]
This has been implemented.

![image](https://cloud.githubusercontent.com/assets/1403503/23292547/90da1bea-fa2e-11e6-86fe-25ffb1c9316b.png)

Automagically works for ranking pages, too.

**Comment by quantum5** [comment]
What the hell do you think you are doing? You are running two queries per row!

![default](https://cloud.githubusercontent.com/assets/461885/23292864/89b05418-fa30-11e6-9733-ae9e88b6568e.png)
