### ISSUE TITLE
Registration improvements

### ISSUE THREAD

**Issue by Xyene** [DMOJ/site#449]
The user registration page could do some work. We should:
- <del>update the UI to be less awkward</del>
- <del>implement a way for users to see password requirements "(?)"</del>
- <del>fix location autodetect; it no longer works</del>
- <del>display form errors in a more sane manner</del>
- Ajax the organizations list, since it may grow very large
- If the organization a user wants doesn't exist, use select2 magic to allow them to define it on the spot
  - we can add a message stating that troll organizations will be removed, and users banned etc.

**Comment by Xyene** [comment]
We should also use [this](https://www.w3.org/TR/html5/forms.html#attr-fe-autocomplete) so we don't rely on browser heuristics.

**Comment by quantum5** [comment]
What exactly are you saying? Turning it off so browsers won't fill in the registration form in any way, shape, or form?

**Comment by quantum5** [comment]
So, what exactly are we going to do about the organization list? Since there is no search, it is more efficient to do it with ajax. Unless of course, we are adding a search, or we are hacking select2 to respect input order.
