### ISSUE TITLE
Have multiline LATEX displayed as inline

### ISSUE THREAD

**Issue by atarw** [DMOJ/site#452]
Very helpful for displaying matrices and other stuff. 

For example, currently, the below must be formatted onto one line in order to display properly, which is inconvenient.

```
A =
\begin{bmatrix}
    a_{11} & a_{12} & \dots & a_{1n} \\
    a_{21} & a_{22} & \dots & a_{2n} \\
    \vdots & \vdots & \ddots & \vdots \\
    a_{m1} & a_{m2} & \dots & a_{mn} \\
\end{bmatrix}
```

**Comment by quantum5** [comment]
It is believed that adding `re.S` to our regex will fix this issue. However, that may pose trouble with MathJax. It is necessary to find out if MathJax works with multiline math, or whether we need to replace line endings with space.

/cc @Xyene

**Comment by Xyene** [comment]
Judging by [this](http://www.martinkeefe.com/math/mathjax2), MathJax can do it just fine.

**Comment by quantum5** [comment]
It works now. Note that you need to double the backslashes at the end of the line due to markdown.
