### ISSUE TITLE
Line numbers are not spaced out properly

### ISSUE THREAD

**Issue by ZeekyueffEmgeebee** [DMOJ/site#453]
Line numbers might not begin or end at the correct line. Issue seems to stem from lines numbers not taking up more than one line. Example at: https://dmoj.ca/src/267324

**Comment by Xyene** [comment]
Cause is the `pre { white-space: pre-wrap; }` CSS style; removing it fixes the line number issue but adds scrollbars to wide submissions.

**Comment by Xyene** [comment]
This is done.
