### ISSUE TITLE
Can't check "Check all" box

### ISSUE THREAD

**Issue by Xyene** [DMOJ/site#454]
Filing for @WallE256:

![image](https://cloud.githubusercontent.com/assets/1403503/18131073/759476c8-6f5f-11e6-9f90-8c3c6509e98f.png)

**Comment by Xyene** [comment]
We can just remove the explicit height declaration or set it to 28em. I'm not sure why the height declaration was in there in the first place, seeing as it sizes correctly even without it. @quantum5, do you happen to remember?

**Comment by quantum5** [comment]
[A simple `blame` shows that it was you.](https://github.com/DMOJ/site/commit/78d1c2486eaebe32cba5c573c763ea2eb8f956e3)

**Comment by Xyene** [comment]
Does it really matter now? I do remember it used to be bad, but that's no longer the case.

**Comment by Xyene** [comment]
This should be fixed. However, the only reason it was broken is because of a "fix" from a while ago, so if the issue resurfaces in any way please reopen this ticket.
