### ISSUE TITLE
Make admin changelist author search easier

### ISSUE THREAD

**Issue by Xyene** [DMOJ/site#455]
Filing on behalf of @1-d:

![image](https://cloud.githubusercontent.com/assets/1403503/18131198/eae80d9a-6f5f-11e6-857a-f22c33eccf1e.png)

We could make this easier to navigate if we were to use Select2.

**Comment by quantum5** [comment]
That's something in `django-wpadmin`.

**Comment by quantum5** [comment]
Issue rectified in 762a13657a18402ab08387c5d8eddfbaa9488b1b.
