### ISSUE TITLE
Make short username search easier

### ISSUE THREAD

**Issue by Xyene** [DMOJ/site#458]
_Some people_ have really short names that make them really hard to be searched for.

Instead of requesting them to change their names, we can treat a trailing space in the search as a end of a name, and use some other mechanism (`get`?) instead of `filter` to retrieve the user.

**Comment by quantum5** [comment]
That is a valid solution. Simply filter with `__exact` instead of `__icontains`, query ends with whitespace, which are not allowed in usernames.

**Comment by Xyene** [comment]
This is done.
