### ISSUE TITLE
Coloring of ranked names on submission pages

### ISSUE THREAD

**Issue by Xyene** [DMOJ/site#46]
As for rating, like http://www.dmoj.ca/user/quantum/rating

**Comment by quantum5** [comment]
Admin and grandmasters are in sort of conflict.

**Comment by Xyene** [comment]
Not what this enhancement is meant to accomplish: its target is the color of the link in the header.

**Comment by FatalEagle** [comment]
We can always pick another color for admin, like bright orange (Topcoder) or bold black (Codeforces)

**Comment by Xyene** [comment]
But that's not the scope of this ticket! It's not about coloring names based on rank, but coloring the link to the user profile on submission pages.

**Comment by FatalEagle** [comment]
Still, coloring based on rating might be a better idea, considering that you can't tell apart an average user from a top user just by looking at the submissions page right now. It will also make contest scoreboard more exciting.

**Comment by Xyene** [comment]
That's a different issue; a separate ticket should be opened for it.

**Comment by Xyene** [comment]
#205

**Comment by kiritofeng** [comment]
Direct scope of ticket has been addressed, and new ones can be created to directly address resultant issues.
