### ISSUE TITLE
Finalizing submission filtering

### ISSUE THREAD

**Issue by Xyene** [DMOJ/site#461]
We have a submission filter, but we need to figure out how it would play with stats (which it has replaced on the all submissions list). It would be nice to have the filter on all ranking pages too, but there is not enough space for both it and the status table.

We have `/stats/language/`, which could be reused in some form to provide new stats under a different form, but where would these go? Lightbox feels like a good place, but it might take too long to open, with all its fancy animations and whatnot.

Needless to say, this needs more thought.

**Comment by quantum5** [comment]
@Xyene what does this mean how that you have crammed the filter and the stats table on the same page?

**Comment by Xyene** [comment]
Means it's closed.
