### ISSUE TITLE
Visual indicators of problem status (Solved/Attempted/Not attempted)

### ISSUE THREAD

**Issue by nathanlo99** [DMOJ/site#463]
This may help so users don't have to check their "My Submissions" page to see whether they've attempted a question yet.

**Comment by Xyene** [comment]
Proposal: an orange stop sign.

![image](https://cloud.githubusercontent.com/assets/1403503/18258074/dc4d202c-739c-11e6-9ea9-3c41e89ce3b1.png)

**Comment by Xyene** [comment]
This is done.
