### ISSUE TITLE
Problem Tester Field for Problem Admin

### ISSUE THREAD

**Issue by ZeekyueffEmgeebee** [DMOJ/site#468]
It would be a convenience for problem setters (especially those who cannot view every problem in admin) to be able to set problem testers: users who can view the problem admin and submit while the problem is private without being listed as problem author.

**Comment by Xyene** [comment]
I think having a field for authors in all-but-name is a bit too lax, security-wise.

A cautious problemsetter would remove testers from the problem anyway; if testers were to be able to _edit_ the problem, an untrustworthy problem tester would be able to kick the problem author, or make themselves authors too!

I would be in favour for the implementation of this feature strictly to the extent where it would allow testers to view the problem statement and submit, but not be able to administrate it.

**Comment by quantum5** [comment]
a.k.a. `CAP_SYS_ADMIN` is the new `root`.

**Comment by ZeekyueffEmgeebee** [comment]
Viewing the problem and being able to submit to it should be enough for a problem tester.

**Comment by Xyene** [comment]
This is done.
