### ISSUE TITLE
Running event_socket_server

### ISSUE THREAD

**Issue by parkjs814** [DMOJ/site#470]
It seems like RabbitMQ is replaced by event_socket_server few months ago, but I have no idea how to run it.
I'm running judge, bridge, and site without any problem.
Can somebody help me out?
Pre-thanks!

**Comment by quantum5** [comment]
In `local_settings.py`:

```py
## Bridge controls.
# The judge connection address and port; where the judges will connect to the site.
# You should change this to something your judges can actually connect to 
# (e.g., a port that is unused and unblocked by a firewall).
BRIDGED_JUDGE_HOST = 'localhost'
BRIDGED_JUDGE_PORT = 9999

# The bridged daemon bind address and port to communicate with the site.
#BRIDGED_DJANGO_HOST = 'localhost'
#BRIDGED_DJANGO_PORT = 9998
```

You run judge as `dmoj -c <config> <BRIDGED_JUDGE_HOST> -p <BRIDGED_JUDGE_PORT>`.

You only need to change `BRIDGED_JUDGE_*` if the port is already used.

**Comment by WallE256** [comment]
If you need additional help, be sure to check the `docsreview` branch at https://github.com/DMOJ/docs, or online at http://dmoj.readthedocs.io/en/docsreview/ as it's more up to date than what you will find on the `master` branch.  Anyway, the people responsible and the community around DMOJ has gathered on a Slack server. You can join for more help with an invite that you can get from https://slack.dmoj.ca. See you there 😄 .

**Comment by parkjs814** [comment]
It works now :) Thanks @quantum5 @WallE256
