### ISSUE TITLE
Allow contest setters to test contest before start

### ISSUE THREAD

**Issue by ZeekyueffEmgeebee** [DMOJ/site#472]
Contest setters should be allowed to participate in their own contest before the start time in order to make sure that everything is working as intended (for example, pretests).

**Comment by Xyene** [comment]
Could be implemented as allowing _Spectate_ to work before contest start time.

**Comment by quantum5** [comment]
This appears to be done, but requires testing.

**Comment by quantum5** [comment]
Tested. Reopen if you see any issues.
