### ISSUE TITLE
Outdated upsolving implementation nullifies pretests

### ISSUE THREAD

**Issue by Xyene** [DMOJ/site#473]
The current implementation of upsolving (pre-#24) allows users to access full data once their window is over, making pretests rather worthless.

**Comment by quantum5** [comment]
You mean if a problem is only accessible through having a contest, it should use its pretest settings? What if it is accessible through multiple contests? I assume it is pretest-only iff all contests are pretest and it's not public?

**Comment by quantum5** [comment]
This is impossible to do with current setup. Proposed solution is to create a field on the `Problem` object and expose it in the `ContestProblem` inline. Obviously, that field can only be modified by the author of the problem. Also I refuse to call this a bug, when the "pretest" system is really a bug.

**Comment by quantum5** [comment]
This is ridiculous. Now that we have #24 and #405, we can simply deny access to non-public problems that is not in the *current* contest.

**Comment by quantum5** [comment]
I believe this is finally fixed.
