### ISSUE TITLE
Meta-description for problem pages

### ISSUE THREAD

**Issue by Xyene** [DMOJ/site#480]
#475 proved very nice for contest pages, but other pages would benefit from proper meta descriptions too:

![image](https://cloud.githubusercontent.com/assets/1403503/18805261/4214172a-81d6-11e6-8e70-289cbe07e533.png)

@quantum5

**Comment by quantum5** [comment]
Well, providing them will make this look better for sure, but the first paragraph of a problem with a nice story is not a good summary, although there is little we can do about that.

**Comment by quantum5** [comment]
Can add a `summary` field.

**Comment by Xyene** [comment]
Doubt many problemsetters would actually bother to set one, though.

**Comment by quantum5** [comment]
It's something you want to have, along with `og_image`.

**Comment by quantum5** [comment]
This is implemented.
