### ISSUE TITLE
Interactive timezone map on registration/user edit views

### ISSUE THREAD

**Issue by Xyene** [DMOJ/site#49]
Much easier to click on where you live than to scroll/search through a combobox. Also gives the site a modern feel, which is important to prospective users.

**Comment by quantum5** [comment]
The choice is hard:

* [Moment timezone](http://momentjs.com/timezone/) is pretty small, and have zooming.
* [jQuery timezone picker](http://timezonepicker.com/) has auto-detect, and claims to be small but seems larger.

**Comment by Xyene** [comment]
The jQuery timezone picker has a nice map feel (similar in style to that from Ubuntu installation), but doesn't zoom. Size shouldn't be too great a priority since the pages where the picker would be used are rarely loaded anyways.

**Comment by quantum5** [comment]
The map can be easily replaced.

**Comment by quantum5** [comment]
Here's an example:

![](http://i.imgur.com/j5ByEdh.jpg)

**Comment by Xyene** [comment]
That's great, let's use that.

**Comment by quantum5** [comment]
Pick a world texture map:

* [![](http://www.shadedrelief.com/natural3/images/no_ice_clouds.jpg)](http://www.shadedrelief.com/natural3/)
* [![](http://planetpixelemporium.com/images/mappreviews/earthmapthumb.jpg)](http://planetpixelemporium.com/earth.html)

Those two are what I used for punyverse.

**Comment by Xyene** [comment]
I like the blue marble, https://github.com/Xyene/SpaceTorus/blob/master/space_torus/assets/worlds/solar_system/earth.jpg

**Comment by quantum5** [comment]
@Xyene you should style this so it's not just one giant map out on no where.

**Comment by quantum5** [comment]
@Xyene are you happy now?
