### ISSUE TITLE
No Embedded Reference to a User's profile

### ISSUE THREAD

**Issue by Phoenix1369** [DMOJ/site#490]
There should be a way to reference a user profile in the formatted parts of the site (problem statement / blog posts), other than raw HTML:

`<a href="/user/grikukan"><span style="color:blue;font-weight:bold">grikukan</span></a>`

**Comment by quantum5** [comment]
@Phoenix1369 @Xyene @FatalEagle, please determine the best syntax to use.

**Comment by FatalEagle** [comment]
[user:Xyene] seems like a reasonable suggestion.

**Comment by Xyene** [comment]
This feels like the type of thing that'd need a Pagedown change to let people know it's possible.

**Comment by quantum5** [comment]
Is there anything else that would need this feature? Currently implemented for problems, blog posts, contests, and comments. Also does anyone have too much time on their hands to convert everything to use the new syntax?

**Comment by Phoenix1369** [comment]
It would be very much appreciated if it was implemented for flatpages as well.

Wouldn't the best plan of action be to change the references as we encounter them (eg. someone comments on the relevant page), rather than have someone go and hunt them down?

**Comment by BinAccel** [comment]
I would be willing to do the changes, but I don't have access perms for most this stuff.

I could start by doing it on problem statements, but that seems kinda stupid.

**Comment by quantum5** [comment]
It can be done with gradually, but I was wondering if someone is willing to do that...

I will implement it for flatpages when I have time. Anything else?

**Comment by BinAccel** [comment]
On a barely related note, why not have an auto-generator for the contest winners?

**Comment by WallE256** [comment]
That usually means editing a blog post, which is not related to this issue.

On Nov 14, 2016 6:11 AM, "BinAccel" <notifications@github.com> wrote:

On a barely related note, why not have an auto-generator for the contest
winners?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/DMOJ/site/issues/490#issuecomment-260244723>, or mute
the thread

**Comment by quantum5** [comment]
The feature is implemented. Extensions to this feature will be separate tickets.
