### ISSUE TITLE
Separate models.py into packages

### ISSUE THREAD

**Issue by Xyene** [DMOJ/site#493]
`models.py` has gotten to the point where it is impossible to navigate without Ctrl+F searching. Since this is far from optimal, we should look into [splitting up our models.py file](https://docs.djangoproject.com/en/1.9/topics/db/models/#organizing-models-in-a-package) into more manageable packages.

**Comment by quantum5** [comment]
This is definitely a win for i18n (#337) since the line numbers won't be messed up as easily, as in by every change to `models.py`.

**Comment by quantum5** [comment]
This is done.
