### ISSUE TITLE
OpenID/Facebook registration

### ISSUE THREAD

**Issue by Xyene** [DMOJ/site#50]
Would make it easier for new users to register than having to log into their email and click a link.

**Comment by Xyene** [comment]
For Facebook, there is https://github.com/tschellenbach/Django-facebook

> Django Facebook enables your users to easily register using the Facebook API. It converts the Facebook user data and creates regular User and Profile objects. This makes it easy to integrate with your existing Django application.

And according to [this](http://stackoverflow.com/questions/2123369/whats-the-best-solution-for-openid-with-django), https://launchpad.net/django-openid-auth is good for OpenID.

**Comment by Xyene** [comment]
This also looks good: https://github.com/omab/python-social-auth

> Python Social Auth is an easy-to-setup social authentication/registration mechanism with support for several frameworks and auth providers.

"several" as in "a couple dozen", including Facebook and OpenID.

**Comment by Xyene** [comment]
Probably we'd just use Google/Yahoo/OpenID/Twitter/Facebook, and maybe Github/Bitbucket since we're targeting developers.

**Comment by quantum5** [comment]
`python-social-auth` looks good, but I don't know how it interacts with the existing users, and whether it creates actual Django user accounts, and etc. We should create a test app to evaluate it.

**Comment by quantum5** [comment]
I think we can skip the sample application since I found a ["tutorial"](http://www.artandlogic.com/blog/2014/04/tutorial-adding-facebooktwittergoogle-authentication-to-a-django-application/) and it does seem to create actual django accounts. We need to make sure such registration create a `Profile` object though.

**Comment by quantum5** [comment]
On a second thought I don't actually want to screw over the database.

**Comment by quantum5** [comment]
Only authentication backends that provides verified email addresses can be used, because otherwise people can forge accounts to hijack other users.

**Comment by quantum5** [comment]
OpenID could not be realized due to the easiness of hijacking an account by using the same email on a sketchy custom OpenID host. Otherwise, facebook is implemented long time ago.
