### ISSUE TITLE
Switch Markdown renderer

### ISSUE THREAD

**Issue by Xyene** [DMOJ/site#509]
[Mistune](https://github.com/lepture/mistune) looks very promising, being under active development. [It's a lot faster](https://github.com/lepture/mistune/issues/1) than Markdown2, and has an extensible syntax allowing for [easy implementations of things like math support](https://github.com/lepture/mistune-contrib/blob/master/mistune_contrib/math.py). We could definitely get rid of many xpath postprocessors with this, and save even more on rendering times.

It's likely there will be some quirks in rendering, but for the most part all documents should continue rendering the same.

**Comment by quantum5** [comment]
This is not to including the fact that the `markdown2` people seem to think URLencoding an URL is a good idea! That project is going pretty downhill...

**Comment by quantum5** [comment]
The only thing that remains is getting `reference` to run directly in mistune, but we have some trouble with this, as our friend @Xyene's pet experiment with the module is currently ongoing, and to merge it will break his pet experiment.

**Comment by BinAccel** [comment]
Mistune also seems to dislike spaces between the property and equals sign: `<img src = "image.png"` will not be treated as plain text.

**Comment by quantum5** [comment]
? If you write HTML like `<img src = "image.png"`, you should be punished.

**Comment by BinAccel** [comment]
My bad I meant `<img src = "image.png">`

**Comment by quantum5** [comment]
I think at this point the pet experiment part might as well be a separate issue... `mistune` cannot be undone now.
