### ISSUE TITLE
Replying to registration email

### ISSUE THREAD

**Issue by Xyene** [DMOJ/site#51]
Some more new sites allow you to confirm your registration to a service by replying to the registration email sent rather than having to click a link.

Worth considering.

**Comment by Xyene** [comment]
Probably won't play nice with our current Mailgun setup, though.

**Comment by quantum5** [comment]
It plays very nicely but it adds a dependency on mailgun. Mailgun has an API to post when an email is received, which we can use for activation.

**Comment by quantum5** [comment]
We can write a mailgun view which accepts the post request and inspect the mail body for the activation key, and if so, activate the sender. Sounds good @Xyene?

**Comment by quantum5** [comment]
This works.
