### ISSUE TITLE
Marker for currently selected comment

### ISSUE THREAD

**Issue by Xyene** [DMOJ/site#52]
For example, the blue bar in this mockup:

![...](https://sc-cdn.scaleengine.net/i/646b96ffedce52a5e8f559f9617c3c9e.png)

A comment would be selected when visiting it through the comment stream on the main page or replying to it.

**Comment by FatalEagle** [comment]
Why limit it to currently selected comment? How about all new comments from the last time the user visited the page like Codeforces?

**Comment by quantum5** [comment]
Remembering visited comments is not a trivial and quickly bloats DB.

**Comment by quantum5** [comment]
Please post style here as you have already done it.

**Comment by Xyene** [comment]
I haven't; that was a mockup made in paint.

**Comment by quantum5** [comment]
Not actually done yet. That's only the styling part... Now we have to change links.
