### ISSUE TITLE
Warn on default language deselection

### ISSUE THREAD

**Issue by Xyene** [DMOJ/site#528]
If a user's default language is not available for a problem, a warning message among the lines of

> Your default language ({language name}) is not available for this problem, and so has been deselected.

...would likely save some frustration for new users. The message would ideally be placed above the editor, and be dismiss-able.

**Comment by BinAccel** [comment]
Can we see a mock up of the message?

**Comment by Xyene** [comment]
This has been implemented.

![image](https://cloud.githubusercontent.com/assets/1403503/23098959/4e5273a2-f629-11e6-88f3-e8b16b00efbf.png)
