### ISSUE TITLE
Performance point frontend updates

### ISSUE THREAD

**Issue by BinAccel** [DMOJ/site#536]
Because my memory is ~bad~ basically non-functional, I'll need to put this here.

- [x] Override "Points" with PP
- [x] Add a list for the user showing where PP comes from, see OSU profiles.
- [x] Restructuring profile page 
- [x] Table needs more results
- [x] (Barely related but w/e) Minimize problem groups on Profile.
- [ ] Add PP to API

**Comment by Xyene** [comment]
This feature has been rolled out! The remaining item, API, is not frontend-related and can be tracked under #506.
