### ISSUE TITLE
Compatibility with older browsers

### ISSUE THREAD

**Issue by FatalEagle** [DMOJ/site#54]
Ensure all new features (and old features) are compatible with certain older browsers important people (contest organizers from other countries) might use i.e. IE8.

**Comment by quantum5** [comment]
The navigation bar simply doesn't work with IE8.

/cc @Xyene

**Comment by Xyene** [comment]
![...](http://qph.is.quoracdn.net/main-qimg-a7571499899da3aeec5c329488f275e0?convert_to_webp=true)

**Comment by quantum5** [comment]
This thing now works rather nicely in IE8.

**Comment by Xyene** [comment]
A lot of places where we use the `rgba` function we use the alpha channel just to modulate the saturation of color and not to actually provide transparency (i.e. where the background is white and a=0.5 is specified).

For these cases (if I'm not mistaken, all except for the navbar), the rgb components can just be premultiplied instead.

**Comment by quantum5** [comment]
The other case is the comment nesting, but they look fine in IE8. Honestly though, IE8 should be expected to not look as nice.

**Comment by Xyene** [comment]
As a (pleasant) side effect to #205, the navbar has the potential to work in IE8. However, due to other circumstances a bunch of styles fail to display on IE8.

**Comment by Xyene** [comment]
This is a no-go. Too much of DMOJ nowadays relies on features modern browsers tend to have (e.g. flexbox), and maintaining more stylesheets for IE is a highly nontrivial and time-consuming task &mdash; resources can be better allocated elsewhere.

Relevant analytics data: 1.2% of our visitors use IE, and of that, 93% use IE 11, where the site displays fairly well. There are a couple of issues in both IE 11 and Edge, but they will be fixed as a separate issue (they're not old browsers).
