### ISSUE TITLE
Editorials rework

### ISSUE THREAD

**Issue by Xyene** [DMOJ/site#542]
* [x] ~Autogenerate editorials index~ no longer pursuing
* [x] Remove URL column from database
* [x] Add an authors column to database
* [x] Address #541
* [x] Add editorial link to contest pages
* [x] Change editorials to inlines on problem page

**Comment by quantum5** [comment]
You mean an `authors` join table for a `ManyToMany`?

**Comment by Xyene** [comment]
So apparently, we already have an `authors` column. It just isn't shown in the admin, so nobody knows about it.

**Comment by quantum5** [comment]
Implemented.
