### ISSUE TITLE
License view

### ISSUE THREAD

**Issue by Xyene** [DMOJ/site#58]
For exposing the model in #44

**Comment by quantum5** [comment]
License body should probably be markdown.

**Comment by Xyene** [comment]
Probably, though for all intents and purposes an unstyled <pre> block looks just as fine. Probably more "authentic", as that's how they're officially displayed for the GPL family.

**Comment by quantum5** [comment]
Some licenses are fancier, for example Creative Commons having fancy nested ordered lists.

**Comment by Xyene** [comment]
For all intents and purposes that we currently have (and the small amount of problems that are actually licensed on the DMOJ), the current implementation is sufficient.
