### ISSUE TITLE
More help texts for problem admin

### ISSUE THREAD

**Issue by Xyene** [DMOJ/site#582]
Targets include `time_limit` and `memory_limit` (since too many people are confused about the unit), as well as anything else that doesn't have a help-text so far.

Required before #546.

**Comment by Xyene** [comment]
`time_limit` and `memory_limit` are done now. @quantum5 @kiritofeng can you think of any other fields?

**Comment by quantum5** [comment]
>Every field.
>What do mean every field?
>EVERY FIELD!!!!!
