### ISSUE TITLE
Standard Licenses

### ISSUE THREAD

**Issue by quantum5** [DMOJ/site#59]
We should be prepared to add a list of common licenses for #44 and #58.

Some I can think of are:
- GNU Free Documentation License
- Creative Commons by(?:-nc)?(?:-sa)? licenses.

**Comment by quantum5** [comment]
Also remember to note: no license doesn't mean you can do WTF you want.

We should also have public domain as well.

**Comment by Xyene** [comment]
WTFPL; https://www.gnu.org/philosophy/license-list.html#OtherLicenses

**Comment by quantum5** [comment]
Let's do it this way.

> This work is released into the public domain. If this is not possible is your jurisdiction, the work is instead usable under the terms of WTFPL.

**Comment by Xyene** [comment]
@FatalEagle Have you come across any others used for contest problems?

**Comment by FatalEagle** [comment]
Codeforces license: The essence of it is that you cannot reproduce any of their data on an online judge.

**Comment by quantum5** [comment]
This looks like we can use some help and put it into #226.

**Comment by Xyene** [comment]
We haven't really used licenses since they were implemented. This ticket doesn't imply a site change, and any fixture for licenses is better tracked in #226.
