### ISSUE TITLE
ACM style scoring

### ISSUE THREAD

**Issue by wwyhsu** [DMOJ/site#599]
Is is possible to add ACM ICPC style scoring?
Users ranked by # of problems solved first, then by the total time used, and then penalitize by 20mins for each unsuccessful attempt (not accounted unless achieving AC).

**Comment by BinAccel** [comment]
The first two are already implemented; if all your problems have the same point values then users will be ranked by # of problems solved first, then by total time used.

Effectively, this ticket boils down to "implement time penalty for contest problems."

**Comment by wwyhsu** [comment]
Yup! That's right.
I am doing a hack by summing the attempts using SQL queries, but it is just too dirty to hook it on to the main system :)

**Comment by Xyene** [comment]
Superseded by #697.
