### ISSUE TITLE
Markdown editor for comments

### ISSUE THREAD

**Issue by Xyene** [DMOJ/site#60]
The comment editor should use the same widget as the admin interface. The only thing preventing this from being done is the fact that the icons do not have a transparent background. There's only one texture to edit, so removing the background should be trivial.

**Comment by quantum5** [comment]
This should also be done for the ajax editing view, while carefully not breaking the non-ajax version of the view (which no one actually uses).

**Comment by quantum5** [comment]
Implementation note: we currently use the widget on the `OrganizationEdit` view.

**Comment by quantum5** [comment]
Magic must be done as featherlight doesn't execute js in the lightbox.

**Comment by quantum5** [comment]
Fully working.
