### ISSUE TITLE
Contest ranking scoreboard is timezone-sensitive

### ISSUE THREAD

**Issue by gozzarda** [DMOJ/site#606]
I am running my own DMOJ server, and have set Django's `TIME_ZONE `setting to my local timezone (Australia/Perth, UTC+8), as this is where most of my users will be. When running a contest, the scoreboard has a slight presentation issue, however: 

![capture](https://user-images.githubusercontent.com/5536671/28656376-293ca006-72d4-11e7-90a7-ecac48e328fb.PNG)

Note this issue appears to be purely aesthetic and does not affect score or rankings in any way I can find.

I have managed to track this issue down to the [`base_contest_ranking_list`](https://github.com/DMOJ/site/blob/700f59fd0ba37bf96e3b5bf1aca1acfd31e9db0f/judge/views/contests.py#L387) function in `judge.views.contests`. This function takes a timezone-naive timestamp from the database, and so is in UTC. It then uses `make_aware` and the `TIME_ZONE` setting to make it aware, and hence incorrectly converts it from UTC to UTC+8 without applying any offset. When the participation start time is then subtracted from this, it produces a negative time difference.

Ultimately I think this is a result of using custom SQL instead of making the query through Django. as Django normally handles timezones for us, and the call to `make_aware` that is attempting to fix the issue here inadvertently assumes the timezone is UTC.

**Comment by gozzarda** [comment]
Please note I was able to fix this issue by redefining `base_contest_ranking_list` as follows:

    def base_contest_ranking_list(contest, problems, queryset, for_user=None):
        problems = list(contest.contest_problems.select_related('problem').defer('problem__description').order_by('order'))

        def make_ranking_profile(participation):
            return get_participation_ranking_profile(contest, participation, problems)

        return map(make_ranking_profile, queryset.select_related('user__user', 'rating')
               .defer('user__about', 'user__organizations__about'))

I believe the only potential issue with this is it may be slower than the original code. This is sufficient for my purposes, however, as I am running a server for a relatively small community.

**Comment by quantum5** [comment]
Well, changing `TIME_ZONE` is not supposed to be done, since in DMOJ timezone is managed per-user. The default use timezone setting is actually `DEFAULT_USER_TIME_ZONE`.

But yes, that code clearly tried to handle timezones and failed, so therefore must be fixed.
