### ISSUE TITLE
NoReverseMatch error

### ISSUE THREAD

**Issue by monouno** [DMOJ/site#607]
Adding a user through  admin background (/admin/auth/user/add/) throws an exception at (/admin/auth/user/8/change/)

> Traceback (most recent call last):
>   File "/root/dmojsite/local/lib/python2.7/site-packages/django/core/handlers/exception.py", line 42, in inner
>     response = get_response(request)
>   File "/root/dmojsite/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
>     response = self._get_response(request)
>   File "/root/dmojsite/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 217, in _get_response
>     response = self.process_exception_by_middleware(e, request)
>   File "/root/dmojsite/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 215, in _get_response
>     response = response.render()
>   File "/root/dmojsite/local/lib/python2.7/site-packages/django/template/response.py", line 109, in render
>     self.content = self.rendered_content
>   File "/root/dmojsite/local/lib/python2.7/site-packages/django/template/response.py", line 86, in rendered_content
>     content = template.render(context, self._request)
>   File "/root/dmojsite/local/lib/python2.7/site-packages/django/template/backends/django.py", line 66, in render
>     return self.template.render(context)
>   File "/root/dmojsite/local/lib/python2.7/site-packages/django/template/base.py", line 208, in render
>     return self._render(context)
>   File "/root/dmojsite/local/lib/python2.7/site-packages/django/template/base.py", line 199, in _render
>     return self.nodelist.render(context)
>   File "/root/dmojsite/local/lib/python2.7/site-packages/django/template/base.py", line 994, in render
>     bit = node.render_annotated(context)
>   File "/root/dmojsite/local/lib/python2.7/site-packages/django/template/base.py", line 961, in render_annotated
>     return self.render(context)
>   File "/root/dmojsite/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 174, in render
>     return compiled_parent._render(context)
>   File "/root/dmojsite/local/lib/python2.7/site-packages/django/template/base.py", line 199, in _render
>     return self.nodelist.render(context)
>   File "/root/dmojsite/local/lib/python2.7/site-packages/django/template/base.py", line 994, in render
>     bit = node.render_annotated(context)
>   File "/root/dmojsite/local/lib/python2.7/site-packages/django/template/base.py", line 961, in render_annotated
>     return self.render(context)
>   File "/root/dmojsite/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 174, in render
>     return compiled_parent._render(context)
>   File "/root/dmojsite/local/lib/python2.7/site-packages/django/template/base.py", line 199, in _render
>     return self.nodelist.render(context)
>   File "/root/dmojsite/local/lib/python2.7/site-packages/django/template/base.py", line 994, in render
>     bit = node.render_annotated(context)
>   File "/root/dmojsite/local/lib/python2.7/site-packages/django/template/base.py", line 961, in render_annotated
>     return self.render(context)
>   File "/root/dmojsite/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 174, in render
>     return compiled_parent._render(context)
>   File "/root/dmojsite/local/lib/python2.7/site-packages/django/template/base.py", line 199, in _render
>     return self.nodelist.render(context)
>   File "/root/dmojsite/local/lib/python2.7/site-packages/django/template/base.py", line 994, in render
>     bit = node.render_annotated(context)
>   File "/root/dmojsite/local/lib/python2.7/site-packages/django/template/base.py", line 961, in render_annotated
>     return self.render(context)
>   File "/root/dmojsite/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 70, in render
>     result = block.nodelist.render(context)
>   File "/root/dmojsite/local/lib/python2.7/site-packages/django/template/base.py", line 994, in render
>     bit = node.render_annotated(context)
>   File "/root/dmojsite/local/lib/python2.7/site-packages/django/template/base.py", line 961, in render_annotated
>     return self.render(context)
>   File "/root/dmojsite/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 70, in render
>     result = block.nodelist.render(context)
>   File "/root/dmojsite/local/lib/python2.7/site-packages/django/template/base.py", line 994, in render
>     bit = node.render_annotated(context)
>   File "/root/dmojsite/local/lib/python2.7/site-packages/django/template/base.py", line 961, in render_annotated
>     return self.render(context)
>   File "/root/dmojsite/local/lib/python2.7/site-packages/django/template/defaulttags.py", line 315, in render
>     return nodelist.render(context)
>   File "/root/dmojsite/local/lib/python2.7/site-packages/django/template/base.py", line 994, in render
>     bit = node.render_annotated(context)
>   File "/root/dmojsite/local/lib/python2.7/site-packages/django/template/base.py", line 961, in render_annotated
>     return self.render(context)
>   File "/root/dmojsite/local/lib/python2.7/site-packages/django/template/defaulttags.py", line 439, in render
>     url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
>   File "/root/dmojsite/local/lib/python2.7/site-packages/django/urls/base.py", line 91, in reverse
>     return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
>   File "/root/dmojsite/local/lib/python2.7/site-packages/django/urls/resolvers.py", line 392, in _reverse_with_prefix
>     (lookup_view_s, args, kwargs, len(patterns), patterns)
> **NoReverseMatch: Reverse for 'judge_profile_change' with arguments '('',)' and keyword arguments '{}' not found. 1 pattern(s) tried: [u'admin/judge/profile/(.+)/change/$']**

**Comment by Xyene** [comment]
Adding a `User` model through the admin panel will always fail, since it doesn't create the necessary `Profile` model (which DMOJ uses to store DMOJ-specific user data, as opposed to the Django-wide `User` model). You should use the regular registration feature (`/accounts/register`), since that creates the `Profile` models itself.

Alternatively, you can create a user from a Django shell:

```python
from judge.models import *

user = User.objects.create_user(username, email, password)
profile = Profile(user=user, language=lang)
profile.save()
```

**Comment by monouno** [comment]
THANKS. I have learned about the cause of the exception, but I have not been able to fix it and can only temporarily close it. Similarly, I also found that when the organization and the contest data table is empty, access `/edit/profile/`  And `/contests/2017/8/` will also throw an exception, temporarily by adding a record to repair.

**Comment by Xyene** [comment]
In theory these types of issues can simply be fixed by having fixtures provide sufficient data (#226). It's impractical at this point to handle all the 0-length corner cases though, and hard to test them too. Invalid data inputted through the UI can always be deleted from a Django shell.
