### ISSUE TITLE
One-click comment hide

### ISSUE THREAD

**Issue by Xyene** [DMOJ/site#615]
Have a trashcan icon for admins to be able to hide comments without having to open up admin.

**Comment by quantum5** [comment]
And no edit history too.

**Comment by quantum5** [comment]
Implemented.

**Comment by Xyene** [comment]
OK maybe 1-click is too little, accidentally went on a hiding spree by clicking the wrong button. Should probably ask for confirmation.

**Comment by quantum5** [comment]
Added confirmation that can be overridden by <kbd>Ctrl</kbd> if you really want a hiding spree, just for you, @Xyene.

**Comment by Xyene** [comment]
👌
