### ISSUE TITLE
Manually add an User

### ISSUE THREAD

**Issue by wwyhsu** [DMOJ/site#626]
Possible bug.
After manually adding an user account through the web interface, only the auth_user database table is updated.
However, the judge_profile table is unaltered. 
So when we click the edit user, a response error is created.
Current solution can be done manually by adding another row into the database judge_profile table.

**Comment by Xyene** [comment]
It's a bad idea to attempt to add users directly from the admin interface; users are meant to be created through the regular registration procedure. As you've encountered, doing otherwise will cause an error. 

We're aware of this, but it is not something that tends to come up past the testing stage of running DMOJ as an online judge -- if you'd like to create a PR addressing this particular case, you are welcome to.

If you're pre-creating accounts for a contest, it might make sense to use a simple script to populate users from e.g. a CSV of usernames and other personal info:

```python
from judge.models import *

username = ...
email = ...
password = ...

user = User.objects.create_user(username, email, password)
profile = Profile(user=user, language=Language.get_python2())
profile.save()
```

Though for regular users, using the regular registration system is the way to go.

**Comment by wwyhsu** [comment]
Thanks :)
Pre-creating and populating anonymous accounts into a private group for a contest was exactly what I was doing. The contest will only be available for the accounts generated.

**Comment by aliir74** [comment]
Hi all. I want to use @Xyene script to creating users from an excel and below error occurred:
```
Traceback (most recent call last):
  File "addesfusers.py", line 1, in <module>
    from judge.models import *
  File "/root/Downloads/site/judge/models/__init__.py", line 4, in <module>
    from judge.models.comment import Comment, CommentVote
  File "/root/Downloads/site/judge/models/comment.py", line 3, in <module>
    from django.contrib.contenttypes.fields import GenericRelation
  File "/root/Downloads/dmojsite/local/lib/python2.7/site-packages/django/contrib/contenttypes/fields.py", line 5, in <module>
    from django.contrib.contenttypes.models import ContentType
  File "/root/Downloads/dmojsite/local/lib/python2.7/site-packages/django/contrib/contenttypes/models.py", line 139, in <module>
    class ContentType(models.Model):
  File "/root/Downloads/dmojsite/local/lib/python2.7/site-packages/django/contrib/contenttypes/models.py", line 140, in ContentType
    app_label = models.CharField(max_length=100)
  File "/root/Downloads/dmojsite/local/lib/python2.7/site-packages/django/db/models/fields/__init__.py", line 1061, in __init__
    super(CharField, self).__init__(*args, **kwargs)
  File "/root/Downloads/dmojsite/local/lib/python2.7/site-packages/django/db/models/fields/__init__.py", line 172, in __init__
    self.db_tablespace = db_tablespace or settings.DEFAULT_INDEX_TABLESPACE
  File "/root/Downloads/dmojsite/local/lib/python2.7/site-packages/django/conf/__init__.py", line 56, in __getattr__
    self._setup(name)
  File "/root/Downloads/dmojsite/local/lib/python2.7/site-packages/django/conf/__init__.py", line 39, in _setup
    % (desc, ENVIRONMENT_VARIABLE))
django.core.exceptions.ImproperlyConfigured: Requested setting DEFAULT_INDEX_TABLESPACE, but settings are not configured. You must either define the environment variable DJANGO_SETTINGS_MODULE or call settings.configure() before accessing settings.
```

my script is and locate in _site_ folder:
```
from judge.models import *


from openpyxl import load_workbook
wb = load_workbook(filename="esfusers.xlsx", read_only=True)
ws = wb['Sheet1']
print('hello')
for row in ws.rows:
        username= row[2]
        firstname = row[0]
        lastname = row[1]
        password = row[3]
        print(row)
        if(username == 'user'):
                continue

        user = User.objects.create_user(username, email, password)
        profile = Profile(user=user, language=Language.get_python2())
        profile.save()
```

**Comment by Xyene** [comment]
This needs to be run within a Django shell, i.e. `python manage.py shell`; running it by itself won't load the necessary Django components.

**Comment by aliir74** [comment]
Thanks @Xyene, previous problem solved but this error occurred:
```
Traceback (most recent call last):
  File "<console>", line 9, in <module>
NameError: name 'User' is not defined
```

**Comment by Xyene** [comment]
@aliir74 you're missing an import to the `User` model from Django's auth models.

**Comment by aliir74** [comment]
Thanks, my problem solved with add this to the code:
```
from django.contrib.auth.models import *
```

**Comment by aliir74** [comment]
But in this method we shouldn't add a username with ```.@space``` because when User page load a blue page with error
