### ISSUE TITLE
error at /accounts/register/  - [Errno 111] Connection refused

### ISSUE THREAD

**Issue by gjigandi** [DMOJ/site#628]
Hi guys,

Thanks a lot for the effort you are putting into this. I managed to install the website and the judge. It looks like the system is working fine, the judge is connected and I can see from the admin panel that it's online.

However, when I try to register a user (using the *Register* link), the following error gets thrown:

error at /accounts/register/  
[Errno 111] Connection refused  
Request Method: POST
Request URL: http://<SERVER_IP>/accounts/register/
Django Version: 1.11.7
Exception Type: error
Exception Value: [Errno 111] Connection refused
Exception Location: /usr/lib/python2.7/socket.py in create_connection, line 575
Python Executable: /home/ubuntu/site/uwsgi
Python Version: 2.7.12
Python Path: ['/home/ubuntu/site/',
 '.',
 '/home/ubuntu/site',
 '/home/ubuntu/dmojsite/lib/python2.7',
 '/home/ubuntu/dmojsite/lib/python2.7/plat-x86_64-linux-gnu',
 '/home/ubuntu/dmojsite/lib/python2.7/lib-tk',
 '/home/ubuntu/dmojsite/lib/python2.7/lib-old',
 '/home/ubuntu/dmojsite/lib/python2.7/lib-dynload',
 '/usr/lib/python2.7',
 '/usr/lib/python2.7/plat-x86_64-linux-gnu',
 '/usr/lib/python2.7/lib-tk',
 '/home/ubuntu/dmojsite/local/lib/python2.7/site-packages',
 '/home/ubuntu/dmojsite/src/django-pagedown',
 '/home/ubuntu/dmojsite/src/dmoj-wpadmin',
 '/home/ubuntu/dmojsite/src/pyjade',
 '/home/ubuntu/dmojsite/lib/python2.7/site-packages']

Could you help please?
Thanks a lot.

**Comment by gjigandi** [comment]
I figured out that I haven't setup an email backend yet, so the registration fails because it cannot send the validation email. (Maybe this can be mentioned on the guide?)

Thanks.

**Comment by weeee9** [comment]
hi, I got the errno 111 too, but i got this error when i try to connect the judge server to the site.
I can't figure it out why I got this error, I've try many ways to solve, but I failed, can you tell me how do you connect judge and site?
I'm using the site-docker to build the site.

thanks for you help, and sorry for my poor english.
