### ISSUE TITLE
Judge runtime version matrix

### ISSUE THREAD

**Issue by Xyene** [DMOJ/site#634]
A page, e.g. https://dmoj.ca/status/matrix, having judges as columns and runtimes as rows. Each cell would contain the runtime version of that specific judge. The newest version(s) should be highlighted in e.g. green, and anything older in red.

|    | Iscandar | Centurion | Lemuria |
|---|---|---|---|
| C++ 17 | `gcc 6.3` | &mdash; | `gcc 6.0` |
| C++14 | `gcc 6.3` | `gcc 5.4` | `gcc 6.3` |
| Java 8 | `...` | `...` | `...` |
| ... | `...` | `...`| `...` |

This would be very useful for admins to keep runtimes updated.

**Comment by quantum5** [comment]
This is done.
