### ISSUE TITLE
Jinja2 template conversion

### ISSUE THREAD

**Issue by Xyene** [DMOJ/site#635]
It's time to switch off PyJade.

* It's unmaintained
* Jinja2 is less hostile to potential new contributors (more HTML and Python, less magic)
* [We've been running our own fork for years](https://github.com/DMOJ/pyjade)
* Syntax is unwieldy, some cases use Jade syntax, while others use Python syntax
* Pycharm consistently breaks it on autoformat
* It's slow
* No idealistic design choices forced in Jinja2 (`{% for n in range(1,10) %}` !!!)

This'll be a pretty big effort, but should be accelerated by using PyJade to dump Jinja2 templates, Pycharm to autoformat, and then manual labour to fix further issues.

**Comment by quantum5** [comment]
We shall now abandon pyjadism and embrace the one and true belief, jinjatwism.

**Comment by quantum5** [comment]
The conversion is complete.
