### ISSUE TITLE
In profile edit and registration, rename "Location" to "Timezone"

### ISSUE THREAD

**Issue by Xyene** [DMOJ/site#637]
Causes people a lot of confusion when registering, since they expect to find their city there (and often email us about adding their city), when in reality it's just https://en.wikipedia.org/wiki/Tz_database

This goes against the point of using tzinfo as a more user-friendly alternative to UTC offsets.

**Comment by quantum5** [comment]
>This goes against the point of using tzinfo as a more user-friendly alternative to UTC offsets.
False. The tzdata database only creates new "cities" when the timezone history diverges. Therefore, the full tzinfo name is required to properly transition DST and other things.

Be sure to remind the users that they are supposed to select the nearest city.

**Comment by Xyene** [comment]
Regardless of what tzdata's actual goal is, we've been using it as a user-friendly alternative to UTC offsets.

**Comment by quantum5** [comment]
We have not. UTC offsets will not allow DST adjustment.
