### ISSUE TITLE
edit/profile not working 

### ISSUE THREAD

**Issue by thangdnsf** [DMOJ/site#642]
![image](https://user-images.githubusercontent.com/7885424/33802235-fc3e58f6-dda4-11e7-8044-5563c3e734ac.png)

**Comment by monouno** [comment]
I guess you didn't configure the math engine server, so the submitted form data lack of 'math_engine' causes it to not work.
Annotate this line of code should be ok.
https://github.com/DMOJ/site/blob/d0648dbc791dd99ab1874b4f20f08bc915d248e9/templates/user/edit-profile.html#L115

**Comment by yhylord** [comment]
Hey I got the same problem, and commenting out `{% if has_math_config %}` doesn't work. Any help?

**Comment by yhylord** [comment]
OK found out that I didn't actually comment it out. For anyone encountering this problem, make sure to use `{# COMMENT #}` in jinja2 rather than `# COMMENT`.

**Comment by Xyene** [comment]
@kiritofeng has fixed this.
