### ISSUE TITLE
IOError: [Errno 2] No such file or directory: u'/tmp/static/jsi18n/en/djangojs.js'

### ISSUE THREAD

**Issue by aliir74** [DMOJ/site#672]
Hi. I add a hostname to my local_setting.py and after few years see this error as a admin view of site and site dosent see anymore.

```
IOError: [Errno 2] No such file or directory: u'/tmp/static/jsi18n/en/djangojs.js'
```

**Comment by aliir74** [comment]
I accidentally see [_updating site_](https://docs.dmoj.ca/en/latest/site/updating/) page in documents and run update commands and my problem fixed. but I didn't know why this needed.

**Comment by Xyene** [comment]
Sounds like you didn't change `STATIC_ROOT` to something permanent as per [the instruction to do so](https://github.com/DMOJ/docs/blob/master/sample_files/local_settings.py#L121-L124). During the installation process you ran 

```bash
(dmojsite) $ ./make_style.sh
(dmojsite) $ python manage.py collectstatic
(dmojsite) $ python manage.py compilemessages
(dmojsite) $ python manage.py compilejsi18n
```

which generated the necessary files into `STATIC_ROOT`. Then your machine rebooted and `/tmp` was purged, and your static files disappeared. Change `STATIC_ROOT` to something permanent to prevent this.
