### ISSUE TITLE
COMPRESS_ROOT defaults to STATIC_ROOT, please define either

### ISSUE THREAD

**Issue by PandaWhoCodes** [DMOJ/site#676]
File "/usr/local/lib/python2.7/dist-packages/compressor/conf.py", line 101, in configure_root
    'STATIC_ROOT, please define either')
django.core.exceptions.ImproperlyConfigured: COMPRESS_ROOT defaults to STATIC_ROOT, please define either

**Comment by quantum5** [comment]
You might want to configure `local_settings.py`. Please read the file carefully and follow the instructions in the comments.

**Comment by PandaWhoCodes** [comment]
there is no local_settings.py
it has been added to gitignore

**Comment by PandaWhoCodes** [comment]
@quantum5

**Comment by quantum5** [comment]
Please read [the documentation](https://docs.dmoj.ca/en/latest/site/installation/). It clearly says that you need to:

>You will now need to configure dmoj/local_settings.py. You should make a copy [of this sample settings file](https://github.com/DMOJ/docs/blob/master/sample_files/local_settings.py) and read through it, making changes as necessary. Most importantly, you will want to update MySQL credentials.

Please feel free to follow the instructions and not pester me.

**Comment by PandaWhoCodes** [comment]
just what I was searching for.

**Comment by RedoC-github** [comment]
Thanks, @PandaWhoCodes! I had the same problem, but I figured the way out as your question!
