### ISSUE TITLE
Judge cannot connect to site server with "error: [Errno 111] Connection refused"

### ISSUE THREAD

**Issue by kaijianwang** [DMOJ/site#678]
I followed instructions and installed judge and site in default port configuration on 2 separate ubuntu virtual machines. However, every trial of connecting judge to bridged instance fails with `error: [Errno 111] Connection refused`.
Detailed error log of `dmoj -c config.yml <site host name>` is here:

> INFO 2018-04-28 01:52:46,539 15408 packet Preparing to connect to [oj]:9999 as: judge1
INFO 2018-04-28 01:52:46,540 15408 packet TLS not enabled.
INFO 2018-04-28 01:52:46,546 15408 packet Opening connection to: [oj]:9999
ERROR 2018-04-28 01:52:46,548 15408 packet Connection failed due to socket error: [oj]:9999
Traceback (most recent call last):
  File "/home/judge/judge/dmoj/packet.py", line 120, in _do_reconnect
    self._connect()
  File "/home/judge/judge/dmoj/packet.py", line 84, in _connect
    self.conn = socket.create_connection((self.host, self.port), timeout=5)
  File "/usr/lib/python2.7/socket.py", line 571, in create_connection
    raise err
error: [Errno 111] Connection refused

A judge named with "judge1" has been created in admin site with the same judge key in `config.yml`.
My site and bridged instances are all launched by nginx with default port configurations.

I'm sure that site:9999 has been listened by the bridged instance because of the following output by command `sudo netstat -ntlp | grep LISTEN`:

> tcp        0      0 127.0.0.1:3306          0.0.0.0:*               LISTEN      1379/mysqld     
tcp        0      0 127.0.1.1:9998          0.0.0.0:*               LISTEN      13582/python    
tcp        0      0 127.0.0.1:9999          0.0.0.0:*               LISTEN      13582/python    
tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN      13630/nginx     
tcp        0      0 127.0.1.1:53            0.0.0.0:*               LISTEN      1891/dnsmasq    
tcp        0      0 127.0.0.1:631           0.0.0.0:*               LISTEN      10650/cupsd     
tcp        0      0 127.0.0.1:15100         0.0.0.0:*               LISTEN      11123/node      
tcp        0      0 127.0.0.1:15101         0.0.0.0:*               LISTEN      11123/node      
tcp        0      0 127.0.0.1:15102         0.0.0.0:*               LISTEN      11123/node      
tcp6       0      0 :::80                   :::*                    LISTEN      13630/nginx     
tcp6       0      0 ::1:631                 :::*                    LISTEN      10650/cupsd

Is there anyone have some insights?

**Comment by kaijianwang** [comment]
Sorry for the spam.

I successfully connect judge to the server after changing `BRIDGED_JUDGE_ADDRESS` to "0.0.0.0".

**Comment by KaiserW** [comment]
Hi, is the `BRIDGED_JUDGE_ADDRESS` ['0.0.0.0', 9999]?
