### ISSUE TITLE
Can't submit solution

### ISSUE THREAD

**Issue by tsaohao** [DMOJ/site#679]
**My local site can't submit solution, it shows like:**

![image](https://user-images.githubusercontent.com/8297811/39904711-e822b162-550b-11e8-88a9-ecdfdf826c44.png)

**And on the problem page, all "allowed language" are strikethrough, like:** 

![image](https://user-images.githubusercontent.com/8297811/39904805-6586c670-550c-11e8-88aa-867fb5bbe015.png)

**In admin page, I've checked these languages, like:**

![image](https://user-images.githubusercontent.com/8297811/39904755-2c5c6a80-550c-11e8-8bef-0080c9de8b4c.png)

**And the judger works fine, like:**

![image](https://user-images.githubusercontent.com/8297811/39904775-3c67ee68-550c-11e8-9ff6-93a478c70bc0.png)

Any idea to solve this?

Thanks.

**Comment by tsaohao** [comment]
BTW, I use docker for both site and judge.

**Comment by Xyene** [comment]
@maxwell0212 read the sample config for `problem_storage_root`; it's likely you misconfigured it.
