### ISSUE TITLE
Extra judge controls in admin

### ISSUE THREAD

**Issue by Xyene** [DMOJ/site#696]
There are occasionally misbehaving judges that need to be dealt with at inconvenient times. SSHing into a particular judge from e.g. a phone to turn it off is not ideal, and it would be straightforward to add some basic level of control in the judge admin.

In particular, I'm referring to:

* A button to send a new `disconnect` packet to the judge, which performs graceful cleanup
* A button to forcefully drop the connection
* A checkbox to block authentication of the judge, even if the key is correct (potentially useful with connection dropping)

**Comment by quantum5** [comment]
Implemented.
