### ISSUE TITLE
Contest time penalty controls

### ISSUE THREAD

**Issue by Xyene** [DMOJ/site#697]
Necessitates the addition of two fields:

* `time_penalty_incorrect_solution` timedelta for how much to penalize per non-full-AC solution
* `time_penalty_strict` boolean for whether CE verdict is included as an incorrect solution

**Comment by kiritofeng** [comment]
With the new contest format configuration from #842, this should be changed into a `penalty` and `bonus` field on each `ContestSubmission` object, and their computation should be handled by the contest format.

The values can be specified by using the JSON format provided.

**Comment by quantum5** [comment]
I think this is no longer relevant. Since the goal here is to replicate an ACM contest, we should just add an ACM contest format.

Hence, superseded by #958.
