### ISSUE TITLE
Use numerical IDs for organization pages

### ISSUE THREAD

**Issue by Xyene** [DMOJ/site#704]
Having to think of a 6-character short ID that never really matches is suboptimal. IDs are far cleaner in the URL, and we could maintain a simple redirect map for the organizations we already have.

**Comment by quantum5** [comment]
How about we do `id-slug` like most websites do? So like `1-don-mills-collegiate-institute`

**Comment by Xyene** [comment]
I'm fine with that approach too. Just not with the current one.

**Comment by quantum5** [comment]
Implemented.
