### ISSUE TITLE
Contest page pagination

### ISSUE THREAD

**Issue by quantum5** [DMOJ/site#721]
The contest page is too long as is, and should probably be paginated. However, we must first discuss how present and future contests will be paginated, i.e. will they only show on first page or every page? I am leaning towards the former.

/cc @Xyene

**Comment by xiaowuc1** [comment]
CF shows present/future contests on every page - see https://codeforces.com/contests/page/2 for an example

AtCoder has an explicit archive for past contests at https://atcoder.jp/contests/archive and recent contests from the past at https://atcoder.jp/contests (I assume there's a section for future contests but there isn't one scheduled at the current point in time).

**Comment by Xyene** [comment]
This is done. Contest _search_ is another issue.
