### ISSUE TITLE
Contest calendar missing month name

### ISSUE THREAD

**Issue by quantum5** [DMOJ/site#723]
Contest calendar is missing month name:

![default](https://user-images.githubusercontent.com/461885/46262090-73339b80-c4ca-11e8-86e3-4b9bc2fc3e89.png)

It should say `Contests in September 2018`.

**Comment by motatoes** [comment]
I've been trying to figure this out today and everything seems to be correct, but I'm not sure why the date filter is not working in the line:

[{% set title = _('Contests in %(month)s', month=month|date(_("F Y"))) %}](https://github.com/DMOJ/site/blob/master/templates/contest/calendar.html#L6)

I tried to render the value of `month` in the template and it does show the data of form `yyyy-mm-dd` so I can't figure out what's wrong with the date filter. Will be playing with it again later as well
