### ISSUE TITLE
Prepare for 7 digit submission count

### ISSUE THREAD

**Issue by quantum5** [DMOJ/site#729]
Changing the total submission count to 7 digits causes an ugly line wrap:

![default](https://user-images.githubusercontent.com/461885/46262281-14bbec80-c4cd-11e8-8e1d-e18cedb06b50.png)

Since we are hitting 7 digits soon, this should be fixed.

**Comment by Xyene** [comment]
I was actually just thinking of scrapping this and going with an interactive pie chart the other day.

**Comment by motatoes** [comment]
Where does the line wrap occur? I tried to use the dev inspector to add an extra digit to `Total` but the display is still fine for me

![](https://i.imgur.com/1JyAR01.png)

**Comment by motatoes** [comment]
But I am up replacing the stats table with a chart if that's needed
