### ISSUE TITLE
Navigation bar link path length limit is too small

### ISSUE THREAD

**Issue by Xyene** [DMOJ/site#75]
<https://github.com/DMOJ/site/blob/master/judge/models.py#L493>

**Comment by quantum5** [comment]
I don't think the limit will ever be hit when the navigation bar is only 2 levels deep. @Xyene needs to style it better to achieve more levels.

**Comment by Xyene** [comment]
What? No... that's the URL that the navigation bar points to. I tried renaming "Redmine" to "Issues" and pointing to this repository, but the link was too long.

**Comment by quantum5** [comment]
OK external links could actually hit the limit. Internal links getting more than 30 chars requires at least 3 levels.

**Comment by Xyene** [comment]
The line I point to in the original issue specifies that this issue is about external links.

**Comment by quantum5** [comment]
How long do you want it to be? I don't want too many migrations on this one issue.

**Comment by Xyene** [comment]
Just go for 300. Guaranteed to never have problems again!

**Comment by quantum5** [comment]
inb4 issue 65536: "Navigation Bar causing massive database load"
