### ISSUE TITLE
Display Available Judges

### ISSUE THREAD

**Issue by FatalEagle** [DMOJ/site#78]
Display which judges are currently good for judging a problem, since different judges have different specs and users will eventually notice the difference. Also serves as a hint as to whether the time limit is strict, in which case only one cluster of judges will judge the problem.

**Comment by Xyene** [comment]
Where would this be displayed?

**Comment by FatalEagle** [comment]
Just like allowed languages. "Available Judges"

**Comment by Xyene** [comment]
This might be interesting.

**Comment by Xyene** [comment]
This'd definitely be nice for admins, but in the case of admins the information could be presented as part of #79.

**Comment by Xyene** [comment]
This doesn't seem to be too offensive:

![image](https://user-images.githubusercontent.com/1403503/46188499-7efb4400-c2b7-11e8-87a2-0d55ce94b285.png)
