### ISSUE TITLE
Organization Private Problems Count Towards Score

### ISSUE THREAD

**Issue by jsumabat** [DMOJ/site#789]
Since organization problems are private, they should not count towards the total score towards the leaderboard.

**Comment by Xyene** [comment]
They are also visible in the API, and possibly other places. Would appreciate if someone takes this on.

**Comment by Xyene** [comment]
@kiritofeng still visible in comment RSS feed.

**Comment by Xyene** [comment]
Patched by @Ninjaclasher today.
