### ISSUE TITLE
502 error page

### ISSUE THREAD

**Issue by Xyene** [DMOJ/site#81]
For when we have service outages, inspired by <https://github.com/502>

**Comment by Xyene** [comment]
Thoughts?

![](https://sc-cdn.scaleengine.net/i/ca32e67df9157119912b324e4eb42b8f.png)

**Comment by FatalEagle** [comment]
Legit.

**Comment by quantum5** [comment]
Where is this page?

**Comment by quantum5** [comment]
[Failed W3C validation.](http://validator.w3.org/check?uri=http%3A%2F%2Fwww.dmoj.ca%2F502.html&charset=%28detect+automatically%29&doctype=Inline&group=0)

**Comment by quantum5** [comment]
Note: http://github.com/502 is actually the `504 Gateway Timeout` page. The actual 502 reads:

> No server is currently available to service your request.
> Sorry about that. Please try refreshing and contact us if the problem persists.

**Comment by Xyene** [comment]
The page works as intended.
