### ISSUE TITLE
The problem status does not update - At the latest version

### ISSUE THREAD

**Issue by TuanPi** [DMOJ/site#816]
I have successfully installed the system.
Thank you for sharing a great system. 
However, there is only one error. The status of the problem is not updated. I did not find the error?
![solved](https://user-images.githubusercontent.com/36060217/49073663-8d3cf080-f265-11e8-8dee-0364d51f2c54.PNG)
![2](https://user-images.githubusercontent.com/36060217/49073754-b493bd80-f265-11e8-894e-56eba642843d.PNG)
Please help me, thanks  :)

**Comment by josedanielr** [comment]
You are using the default [cache backend settings](https://github.com/DMOJ/docs/blob/146b960c833aa59ef13cee5ee08e8122accf71f6/sample_files/local_settings.py#L28).

You should be using redis or memcached instead. I recommend memcached, it is very easy to set up.

**Comment by TuanPi** [comment]
Thank you very much. A great support. 👍 
I solved the problem.
