### ISSUE TITLE
Show PDF not right aligned on IE

### ISSUE THREAD

**Issue by quantum5** [DMOJ/site#84]
This is IE 11. Must fix.

**Comment by Xyene** [comment]
Also Dolphin 10.0.0

**Comment by Xyene** [comment]
I'm once again out of battery.

**Comment by quantum5** [comment]
The version of Dolphin on my android emulator doesn't like flexbox in general. IDK about actual phones.

**Comment by quantum5** [comment]
Dolphin is of no concern when the ticket is about IE.
