### ISSUE TITLE
Cookieless domains

### ISSUE THREAD

**Issue by quantum5** [DMOJ/site#86]
For example http://sstatic.net/, and a lot of other sites are doing this too. I have registered `dmoj.ml`, and may be we can use that for this purpose.

http://sstatic.net/ shows some advantages of the practice. I will leave this open for discussion.

/cc @FatalEagle @Xyene

**Comment by Xyene** [comment]
We don't have enough content to make this practically worthwhile, but we might as well do everything right if we can.

**Comment by FatalEagle** [comment]
What does this save in practice? A few bytes?

**Comment by Xyene** [comment]
Saves sending all the cookies for every request to an image, so a lot more than a few bytes.

**Comment by quantum5** [comment]
Over 200 bytes of cookies per request. We don't have too many resource files, but what's interesting is our `mathtex.cgi`, which is request for many, many times on a page with math.

**Comment by quantum5** [comment]
Note that there will be zero byte of code changes, only `local_settings.py` updated and some DNS records and `nginx` config.

**Comment by FatalEagle** [comment]
Even if a page has 50 pieces of latex, 10kb is pretty negligible compared to other things. But if it's fast and easy to do, why not.

**Comment by Xyene** [comment]
Surprising and related:

![](https://sc-cdn.scaleengine.net/i/4e92d767b4dd68c59dc6ffc227302eec.png)

**Comment by quantum5** [comment]
What are you suggesting? To use font awesome for it?

**Comment by Xyene** [comment]
Why not. It loads in ~100ms, faster than the arrow anyways.

**Comment by Xyene** [comment]
Same for the PDF icon:

![](https://sc-cdn.scaleengine.net/i/db4e434283f3477900901bfffc8b155e.png)

Even more sketchy for the above is that we link adobe.com

**Comment by quantum5** [comment]
Well I tried using font awesome for the PDF icon.

**Comment by quantum5** [comment]
Implemented. `dmoj.ml` is now used for all assets except those on other CDNs.

**Comment by quantum5** [comment]
Bonus: a page for http://dmoj.ml/

**Comment by quantum5** [comment]
Using CloudFlare to serve http://dmoj.ml/. Should be effective in 24 hours globally.
