### ISSUE TITLE
Questions about query cache system

### ISSUE THREAD

**Issue by SchrodingerZhu** [DMOJ/site#860]
Hello, due to my team's own need, we decided to migrate the site to `Python 3/Django 2.0+`. The progress is almost finished, but we have some trouble refactoring the [`use_straight_join`](https://github.com/DMOJ/site/blob/73a806163d97d329271e93a0356c33a1e3011fd8/judge/utils/raw_sql.py#L55) function in `raw_sql.py`. I do not quite understand what is this function for. Becuase the API `clone()` has changed, we currently write it in this way:
```python3
def use_straight_join(queryset):
    if connections[queryset.db].vendor != 'mysql':
        return
    # TODO: Understand what is this
    x = queryset.query.clone()
    x.__dict__.update(straight_join_cache)
    queryset.query = x
```
Could you please give us some advice?

**Comment by SchrodingerZhu** [comment]
And our migration branch is [here](https://github.com/SchOJ/site/tree/refactor_upgrade). But the change history is not ready to be looked at now. The workflow need to be tidied, we will do that soon.

**Comment by kiritofeng** [comment]
The purpose of the function is described in #434:

>Django doesn't use `STRAIGHT_JOIN`s for MySQL, and this has led to trivial queries running ridiculously slowly (over 100x slowdown). To fix this we can introduce a `django-mysql` dependency and use its magic.

The original implementation, at https://github.com/DMOJ/site/blob/9cdd66644c77b9c3ca4239902112a4502f7bfd20/judge/utils/raw_sql.py#L38, might make more sense in terms of what it is trying to accomplish.

**Comment by quantum5** [comment]
I suspect all that's needed to make `use_straight_join` on Django 2.x is

```diff
diff --git a/judge/utils/raw_sql.py b/judge/utils/raw_sql.py
index 1823cc8a..78676ed5 100644
--- a/judge/utils/raw_sql.py
+++ b/judge/utils/raw_sql.py
@@ -51,7 +51,12 @@ def make_straight_join_query(QueryType):

 straight_join_cache = CacheDict(make_straight_join_query)

+
 def use_straight_join(queryset):
     if connections[queryset.db].vendor != 'mysql':
         return
-    queryset.query = queryset.query.clone(straight_join_cache[type(queryset.query)])
+    try:
+        cloner = queryset.query.chain
+    except AttributeError:
+        cloner = queryset.query.clone
+    queryset.query = cloner(straight_join_cache[type(queryset.query)])
```
