### ISSUE TITLE
Move submission source out of Submission model

### ISSUE THREAD

**Issue by Xyene** [DMOJ/site#872]
We limit submission source lengths at 64kb; this makes sources the largest part of the `Submission` model by a large margin. Furthermore, while we only display the sources in one or two places, most queries involving `Submission` models implicitly pull the source, only for it to be ignored.

This is suboptimal. A simple fix is to simply move submission source into a new `SubmissionSource` model, and rewrite the one or two queries that actually _do_ need to access the source.

**Comment by kiritofeng** [comment]
This is now in production.
