### ISSUE TITLE
Managing Problems Through the Site Interface

### ISSUE THREAD

**Issue by kenneth-l-i** [DMOJ/site#880]
I found that the problems test data and yml file added by the site interface will saved to dmoj site folder.
Is it correct?
Is there any way to change the default path?
Since I config the dmoj to scan the site folder for problems, the dmoj is very unstable. May be the site folder is very large.
Then I reconfig the dmoj to scan another path (e.g. /home/myproblems) it become usable.

**Comment by Ninjaclasher** [comment]
You can add a setting called `PROBLEM_DATA_ROOT` to your `local_settings.py` to change the default path. E.g `PROBLEM_DATA_ROOT='/code/site/problems/'`
