### ISSUE TITLE
give in-contest submissions higher priority than out-of-contest submissions

### ISSUE THREAD

**Issue by xiaowuc1** [DMOJ/site#884]
Rejudges currently are lower priority than live submissions, as the feedback for the rejudges is not likely to be as pressing as feedback for live submissions (and the rejudge is likely to take a long time).

In a similar vein, submissions in a contest should be higher than submissions outside of a contest - the contest runs more smoothly and mitigates some unfairness issues when the site is experiencing more load from people outside of the contest.

Virtual participations can or can not get this higher priority - but live participations are expected to get higher priority.

**Comment by Xyene** [comment]
This is done.
