### ISSUE TITLE
Green Tick icon in problem list

### ISSUE THREAD

**Issue by kenneth-l-i** [DMOJ/site#886]
I login as a normal user, submit a correct solution, and the system return "AC".
When I click "PROBLEM" to list all problems, the icon at the left of solved problem still showing a red stop icon. But when i restart the site with "superivosorctl restart all",  reload the same page will show the GREEN Tick. 
Is there any thing wrong in my setup?

**Comment by quantum5** [comment]
My psychic powers tell me that you are not using a shared cache (e.g. redis, memcached) between the site workers and the bridge, instead using local memory cache. This makes it impossible for the bridge to purge the cache of the site workers.
