### ISSUE TITLE
Comment Muted Individuals Cannot Edit Profile

### ISSUE THREAD

**Issue by kiritofeng** [DMOJ/site#888]
## Reproduction Steps

Start by preventing a user from posting comments (via `comment mute` in the `admin profile` interface).

Have said user navigate to `/edit/profile/`.

## Expected Behaviour

The user will be greeted with the `Edit profile` page.

## Actual Behaviour:

When this user attempts to go to `/edit/profile`, they will be greeted by a 404 Page Not Found. This is also true for any administrator that is impersonating the account.

**Comment by quantum5** [comment]
Expected behaviour: comment muting is used to block all forms of disruption, including through the user page.

**Comment by quantum5** [comment]
This is literally in the code:

````python
@login_required
def edit_profile(request):
    profile = Profile.objects.get(user=request.user)
    if profile.mute:
        raise Http404()
```
