### ISSUE TITLE
More icons for forms/widgets

### ISSUE THREAD

**Issue by Xyene** [DMOJ/site#89]
Forms could really benefit from font awesome. Refs #88 

This is a quick test on the login page:

![](https://sc-cdn.scaleengine.net/i/6fdbf09fdb37b6412bf7cc5f706f841b.png)

Placeholders instead of labels also look very modern, but even with a polyfill for pre HTML 5 browsers, they're hopeless without JS enabled (#54).

Thoughts?

/cc @quantum5 @FatalEagle

**Comment by Xyene** [comment]
The "Recent comments" and "Recent added problems" bars on the main page could each have an icon, right-justified, in their headers.

**Comment by Xyene** [comment]
Could use http://fontawesome.io/icon/star/ to show sticky posts (right now they're hard to tell apart from normal posts).

**Comment by quantum5** [comment]
Adding icons for recent comments and problems.

**Comment by Xyene** [comment]
Most pages could have an icon in their header.

http://fontawesome.io/icon/user/ - User profile page
http://fontawesome.io/icon/home/ - Home (or not)
http://fontawesome.io/icon/server/ - Judge list
http://fontawesome.io/icon/trophy/ - Contest list (but not contest)
http://fontawesome.io/icon/bars/ - Problem list (not sure; looks like hamburger menu) or http://fontawesome.io/icon/list/

**Comment by Xyene** [comment]
I think we're done with this.
