### ISSUE TITLE
Newsletter interface

### ISSUE THREAD

**Issue by Xyene** [DMOJ/site#9]
Such that contestants can be notified of upcoming contests.

**Comment by quantum5** [comment]
It would help if I actually got around to set it up.

**Comment by quantum5** [comment]
Regardless, this is not actually part of the site.

**Comment by quantum5** [comment]
The system is working perfectly, but the templates look ugly. I should try making the `newsletter/common.html` template work reasonably so we can actually deploy this feature.

**Comment by quantum5** [comment]
We have been using the system rather nicely, but many templates still remain untranslated.

**Comment by Xyene** [comment]
"[R]ather nicely" is an overstatement, but it is unlikely that the newsletter integration will see more development.
