### ISSUE TITLE
Better form errors display

### ISSUE THREAD

**Issue by Xyene** [DMOJ/site#90]
They're pretty badly displayed right now.

**Comment by Xyene** [comment]
For the login form:

![](https://sc-cdn.scaleengine.net/i/a97c1a36cc1d9d18eac7b5e3ce7a320e.png)

**Comment by Xyene** [comment]
Could use http://fontawesome.io/icon/exclamation-triangle/

**Comment by quantum5** [comment]
Instead of

> Your email provider is not allowed due to history of abuse.
> Please use a reputable email provider

Error message contained nothing. Would not buy again.

![](http://i.imgur.com/ObuUND9.png)

**Comment by Xyene** [comment]
[I can do this one in 30 times and still have a 97% positive feedback though.](https://xkcd.com/325/)

**Comment by quantum5** [comment]
[You probably don't really like those users anyway.](https://xkcd.com/810/) (see title text)

**Comment by quantum5** [comment]
Why is there even a `#{form.parent}` in the registration form??

Also, I suggest we make `#form-errors` a class instead so we can simply do:

```jade
if form.field.errors
   .form-errors
        | #{form.field.errors}

**Comment by quantum5** [comment]
This is so outdated.
