### ISSUE TITLE
Cache submission statistics table on main page

### ISSUE THREAD

**Issue by Xyene** [DMOJ/site#903]
On the current live instance of DMOJ, the submission statistics table is patched out. The submission table has grown too large, so computing the simple aggregate over it takes a sizable amount of time.

The problem: when the query cache is busted after a submission completes, all connected clients will trigger an Ajax request (at the same time) to obtain the updated chart, which runs the expensive query dozens, sometimes hundreds, of times concurrently. MySQL chokes and site becomes unresponsive.

Exclusively for `/submissions`, the chart data should be cached. When there are thousands of submissions, a couple dozen won't have an effect on the overall distribution of statuses.

**Comment by quantum5** [comment]
This is now cached. A proposal for having live updates _and_ caching will be implemented later.
