### ISSUE TITLE
Extended judge feedback

### ISSUE THREAD

**Issue by Xyene** [DMOJ/site#909]
For some problems, the 64-byte string we allow inline in testcases is not enough. For these, I propose the addition of an extended feedback field in the test case model. From a checker's point of view, this would be a new keyword argument in `CheckerResult` (or we could automatically use the extended field when the length is over 64).

![image](https://user-images.githubusercontent.com/1403503/54066778-2fc12400-4204-11e9-8812-ef1464251f63.png)

**Comment by quantum5** [comment]
This is on production now.
