### ISSUE TITLE
Automatic Timeanddate for Contests

### ISSUE THREAD

**Issue by FatalEagle** [DMOJ/site#92]
It sucks having to manually add a time and date link every time. It would be nice if it was auto updated.

**Comment by quantum5** [comment]
What do you use time and date for anyways?

**Comment by FatalEagle** [comment]
To give people convenient absolute time conversion on contests, regardless of whether the site knows their location (i.e. Vancouver).

**Comment by quantum5** [comment]
This seems trivial.

http://<span></span>www.timeanddate.com/worldclock/fixedtime.html?msg=<event name>&iso=`YYYYMMDD`T`HHMM`, where the time in UTC.

**Comment by Xyene** [comment]
This ties into #205, and should be done before the first DMOPC.

**Comment by Xyene** [comment]
This is done.
