### ISSUE TITLE
Your submission is being processed but judge is already done

### ISSUE THREAD

**Issue by ZiYiBear** [DMOJ/site#924]
I have some questions, My site shows Your submission is being processed when i send the code and keep stuck in that message, even the judge show its done.

![image](https://user-images.githubusercontent.com/17896080/54553253-bdfb8e00-49ec-11e9-8427-9bbfa23cc71b.png)

![image](https://user-images.githubusercontent.com/17896080/54553341-f1d6b380-49ec-11e9-9f80-c55573641ccd.png)

And when i shows the submissions page, it shows the result success.

![image](https://user-images.githubusercontent.com/17896080/54553487-3febb700-49ed-11e9-893e-4d880193233b.png)

is there another port need to be opened? I used port 80 and 9999 for judge. Also is there any way to batch add student account and default password?

thanks

**Comment by Xyene** [comment]
If you do not have an event server running, this is expected behaviour (you will need to refresh the submission status page).

There is a `manage.py adduser` command for the purpose of automatically creating accounts.

Also, as the startup warning indicates, please do not run the judge as root.

**Comment by ZiYiBear** [comment]
thanks i have success to add account, but still stuck in event server, i tried to start it and faild.

when i check the supervisorctl status, i found wsevent is not running.
![image](https://user-images.githubusercontent.com/17896080/54701694-7140c000-4b70-11e9-983c-1b0da2436c43.png)

and when i extract the error.log in  /tmp/wsevent.stderr.log, it shows

![image](https://user-images.githubusercontent.com/17896080/54701824-ad742080-4b70-11e9-95e8-fbc10e4f746f.png)

is there any way to fix it? thanks

**Comment by quantum5** [comment]
Looks like you are using an *ancient* version of `node`. It is a good idea to upgrade.

**Comment by ZiYiBear** [comment]
> Looks like you are using an _ancient_ version of `node`. It is a good idea to upgrade.

thanks it work!

**Comment by giorzang** [comment]
I'm having the same problem. But my `wevent` status is `RUNNING`. When I check the file `/tmp/wsevent.stderr.log`, it is empty. I restarted all services but it didn't work.
![image](https://user-images.githubusercontent.com/84860408/183239287-fe72436e-86f6-4fb4-8b70-548a1abc51bf.png)
![image](https://user-images.githubusercontent.com/84860408/183239294-004fa7d8-f12c-4fab-a387-d0104760aa8a.png)
