### ISSUE TITLE
Reduce amount of static files and inline stylesheets

### ISSUE THREAD

**Issue by quantum5** [DMOJ/site#93]
This includes merging all the JS and CSS files that will get loaded for sure after using the site into one file to save connections. We should also move most inline stylesheets, which are mostly a development convenience, into the main `style.css` if they are used a lot so we don't repetitively send it on every request.

**Comment by quantum5** [comment]
For most pages, thanks to the introduction of #39, #136, #147, #150, and #151 , only one JS and one CSS is loaded.

**Comment by quantum5** [comment]
The inline stylesheet part needs work.

**Comment by Xyene** [comment]
There are basically no more non-critical inline stylesheets.
