### ISSUE TITLE
Intersecting text on contest page

### ISSUE THREAD

**Issue by quantum5** [DMOJ/site#97]
Let some Chrome emulated phone be my evidence:

![](http://i.imgur.com/YMCtoGF.png)

**Comment by FatalEagle** [comment]
If you're using a phone to do a contest, then I've got some bad news for you...

**Comment by Xyene** [comment]
Same hack is used to display organizations during contests, among other things.

**Comment by quantum5** [comment]
Aero snap might be more popular in contests than you'd think, and school computers have pretty narrow screens.

**Comment by quantum5** [comment]
Fixed a while ago as a rogue feature.

**Comment by Xyene** [comment]
Only really fixed for Past Contests and not Upcoming Contests, which don't have the vertical space to shove the date at the bottom.
