### ISSUE TITLE
Access Levels for problems

### ISSUE THREAD

**Issue by FatalEagle** [DMOJ/site#98]
Instead of having a boolean publicly visible and a user permissions to access all problems or just their own, it would be more flexible to have access levels, where a user can see all problems <= their access level. This allows some trusted users (like bruce) to see hidden problems, while not allowing them to see more secret problems, like contest problems from GFSSOC or a future DMOPC, and prevents people like nullptr from seeing ECOO problems if they are added in advance.

**Comment by quantum5** [comment]
Access level must be stored in both `Problem` and `Profile`.

**Comment by Xyene** [comment]
This has been resolved through the introduction of curators (#522) and testers. As we're moving more towards #546, this is less of an issue than it was 2 years ago.
